<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Business\Job;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use App\Http\Resources\BaseResource;
use App\Http\Resources\BaseCollectionResource;
use App\Mail\VerificationUser;
use App\Rules\CheckValidGeo;
use App\User;
use App\User\Resume\Availability;
use App\User\Resume\BasicInfo;
use App\User\Resume\Preference;
use App\Business;
use App\Business\Location;
use App\Business\JobLocation;
use App\Candidate\Candidate;
use App\Candidate\CandidateWave;
use App\User\UserVideo;
use App\User\UserExpoToken;

class Job2Controller extends Controller
{
    public function get(Request $request, $job_id)
    {
    	$job = Job::findOrFail($job_id);

    	$job->load([
    		'business',
    	]);

    	return response()->resource($job);
	}
	
	public function apply(Request $request, $job_id)
    {
		
		$job = Job::findOrFail($job_id);
    	$business = Business::where('id', $job->business_id)->firstOrFail();
    	$user_video = null;


		if ($request->input('user.video_id')) {
			$user_video = UserVideo::where('id', $request->input('user.video_id'))->first();
		} else if ($request->input('video_id')) { // for old JM app
			$user_video = UserVideo::where('id', $request->input('video_id'))->first();
		}

    	$validation_rules = [];
		$user = auth()->user();
		$user_was_created = false;

		if ($user) {
			$user->load([
				'businesses',
				'preference',
			]);
		} else  {
			$user = User::where('email', $request->input('user.email'))->with([
				'businesses',
				'preference',
			])->first();

	    	if ($user) {
	    		$validation_rules['user.password'] = [
	    			'required',
	    			'string',

					function ($attribute, $value, $fail) use ($user) {
						if (!$user->doesPasswordEqual($value)) {
							$fail('Please enter a valid password.');
						}
					},
	    		];
	    	} else {
	    		$validation_rules['user.first_name'] = 'required|string';
	    		$validation_rules['user.last_name'] = 'required|string';
	    		$validation_rules['user.mobile_phone'] = 'string|nullable';
	    		$validation_rules['user.phone_country_code'] = 'required_with:user.phone_code,user.phone_number|string';
	    		$validation_rules['user.phone_code'] = 'required_with:user.phone_country_code,user.phone_number|string';
	    		$validation_rules['user.phone_number'] = 'required_with:user.phone_country_code,user.phone_code|string';
	    		$validation_rules['user.city'] = 'required|string';
	    		$validation_rules['user.region'] = 'required|string';
	    		$validation_rules['user.country'] = 'required|string';
	    		$validation_rules['user.country_code'] = 'required|string';
	    		$validation_rules['user.language_prefix'] = 'string|nullable';
	    		$validation_rules['user.image'] = 'file';
	    		$validation_rules['user.resume'] = 'file|nullable';
	    		$validation_rules['user.expo_token'] = 'string|nullable';
	    	}

	    	validator()->make($request->all(), $validation_rules)->validate();

			// ------------------------------------------------------------------ //

	    	if (!$user) {
	    		DB::beginTransaction();

	    		try {
		    		$user_autogenerated_password = str_random(8);
		    		$user = new User;
		    		$user->fill($request->input('user'));
		    		$user->password = bcrypt($user_autogenerated_password);
		    		$user->language_prefix = $request->input('user.language_prefix', 'en');
					$user->verification_code = md5(str_random(32));
					$user->verification_date = time();
					$user->show_tooltip = 'on';
					$user->type = 'student';
					$user->username = strtolower($user->first_name . $user->last_name) . rand('1111', '9999');
			    	$user->save();

			        if ($request->hasFile('user.image')) {
			            if ($request->file('user.image')->isValid()) {
			                try {
			                    ini_set('memory_limit', '-1');
			                    $inputImage = $request->file('user.image');

			                    if ($inputImage->getClientSize() < 24000000) {
			                        $ext = $inputImage->getClientOriginalExtension();
			                        $fileName = md5('user-resume-pic-' . $user->id);
			                        $storage = 'user/' . $user->id . '/resume/';
			                        $originalImage = $fileName . '.' . $ext;
			                        //save original image
			                        $inputImage->storeAs($storage, $originalImage);

			                        //create image crop by user crop area
			                        $cropImage = Image::make($inputImage->getRealPath())->orientate();
			                        // $cropImage->crop((int)$imageCropData->width, (int)$imageCropData->height, (int)$imageCropData->x, (int)$imageCropData->y);
			                        Storage::put($storage . 'crop_' . $originalImage, $cropImage->encode());
			                        //create thumbnail 200x200
			                        $cropImage->resize(200, 200);
			                        Storage::put($storage . '200.200.' . $originalImage, $cropImage->encode());
			                        //create thumbnail 100x100
			                        $cropImage->resize(100, 100);
			                        Storage::put($storage . '100.100.' . $originalImage, $cropImage->encode());
			                        //create thumbnail 50x50
			                        $cropImage->resize(50, 50);
			                        Storage::put($storage . '50.50.' . $originalImage, $cropImage->encode());

			                        $user['user_pic'] = $originalImage;
			                        $user['user_pic_original'] = $originalImage;
			                        $user['user_pic_custom'] = 1;
			                        $user['user_pic_filter'] = Input::get('filter');
			                        $user->save();
			                    }
			                } catch (\Exception $e) {}
			            }
			        }

			        if ($request->hasFile('user.resume')) {
			            if ($request->file('user.resume')->isValid()) {
			                $inputImage = $request->file('user.resume');

			                try {
			                    ini_set('memory_limit', '-1');
			                    $inputImage = $request->file('user.resume');

			                    if ($inputImage->getClientSize() < 10000000) {
			                        //$ext = $inputImage->getClientOriginalExtension();
			                        //$fileName = md5('user-resume-attach-' . $this->auth->id);
			                        $fileName = $inputImage->getClientOriginalName();
			                        $storage = 'user/' . $user->id . '/resume/';
			                        $originalImage = $fileName;// . '.' . $ext;
			                        $inputImage->storeAs($storage, $originalImage);
			                        $user->attach_file = $originalImage;
			                        $user->save();
			                    }
			                } catch (\Exception $e) {}
			            }
			        }

		    		$user_preference = new Preference;
			        $user_preference->user_id = $user->id;
			        $user_preference->save();
			        $user->setRelation('preference', $user_preference);

			        $user_availability = new Availability;
			        $user_availability->user_id = $user->id;
			        $user_availability->save();

			        $user_basic_info = new BasicInfo;
			        $user_basic_info->user_id = $user->id;
			        $user_basic_info->headline = '';
			        $user_basic_info->about = '';
			        $user_basic_info->save();

			        $user->setRelation('businesses', collect());
			    } catch (\Exception $exception) {
		            DB::rollback();
		            throw $exception;
		        }

		        DB::commit();
	            $user_was_created = true;

	    		Mail::to($user->email)->queue(new VerificationUser(
	                $user,
                    app()->getLocale(),
	                'INITIAL',
	                ['tmp_password' => $user_autogenerated_password]
	            ));
	    	}

	    	if ($request->input('user.expo_token')) {
		    	if (!$user->expo_tokens()->where('value', $request->input('user.expo_token'))->first()) {
		        	$user_expo_token = new UserExpoToken;
		        	$user_expo_token->user_id = $user->id;
		        	$user_expo_token->value = $request->input('user.expo_token');
		        	$user_expo_token->save();
		    	}
		    }
		}

		$user->preference->transform_yes_no_fields_to_boolean = true;

    	// ---------------------------------------------------------------------- //

    	$candidate_query = Candidate::query();
    	$candidate_query->where('user_id', $user->id);
    	$candidate_query->where('business_id', $business->id);
    	$candidate_query->where('job_id', $job->id);

    	if (!$candidate = $candidate_query->first()) {
    		$candidate = new Candidate;
    		$candidate->user_id = $user->id;
	        $candidate->business_id = $business->id;
	        $candidate->location_id = null;
	        $candidate->job_id = $job->id ?? null;
	        $candidate->pipeline = 'new';
	        $candidate->user_video_id = $user_video->id ?? null;
	        $candidate->source = $request->input('source');
	        $candidate->save();
    	}

        if ($business->admin->user->verification_code) { // BUSINESS NOT CONFIRMED
            Mail::to($business->admin->user->email)->queue(new \App\Mail\CandidateCreated(
                $business->admin->user,
                $business,
                $user,
                $job,
                null,
                false,
                'INITIAL',
                app()->getLocale()
            ));
        } else { // BUSINESS CONFIRMED
            Mail::to($business->admin->user->email)->queue(new \App\Mail\CandidateCreated(
                $business->admin->user,
                $business,
                $user,
                $job,
                null,
                true,
                'INITIAL',
                app()->getLocale()
            ));
        }

    	// ---------------------------------------------------------------------- //

    	return response()->resource([
			'user' => $user->makeVisible([
				'api_token',
				'realtime_token',
			]),

			'user_was_created' => $user_was_created,
    	]);
    }
}
