<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CertificationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('certificates')->delete();
        DB::statement('ALTER TABLE certificates AUTO_INCREMENT = 1');

        $data = [
            [ "name" => "Certificate in Investment Performance Measurement", "name_fr" => "Certificat en mesure du rendement des placements" ],
            [ "name" => "Chartered Financial Analyst", "name_fr" => "Analyste financier agréé" ],
            [ "name" => "Chartered Market Technician", "name_fr" => "Technicien de marché agréé" ],
            [ "name" => "Chartered Alternative Investment Analyst", "name_fr" => "Analyste d'investissement alternatif agréé" ],
            [ "name" => "Chartered Management Consultant", "name_fr" => "Consultant en gestion agréé" ],
            [ "name" => "Chartered Global Management Accountant", "name_fr" => "Chartered Global Management Comptable" ],
            [ "name" => "Certified Public Accountant", "name_fr" => "Expert-comptable" ],
            [ "name" => "Certified Financial Planner", "name_fr" => "Planificateur financier agréé" ],
            [ "name" => "Certified Financial Consultant", "name_fr" => "Consultant financier agréé" ],
            [ "name" => "Chartered Life Underwriter", "name_fr" => "Souscripteur à vie agréé" ],
            [ "name" => "Certified Fraud Examiner", "name_fr" => "Examinateur de fraude certifié" ],
            [ "name" => "Certified Internal Auditor", "name_fr" => "Auditeur interne certifié" ],
            [ "name" => "Certification in Risk Management Assurance", "name_fr" => "Certification en assurance de gestion des risques" ],
            [ "name" => "Certified Government Auditing Professional", "name_fr" => "Professionnel certifié en audit du gouvernement" ],
            [ "name" => "Certified Payroll Professional", "name_fr" => "Professionnel de la paie certifié" ],
            [ "name" => "Fundamental Payroll Certification", "name_fr" => "Certification fondamentale de la paie" ],
            [ "name" => "Certified California Municipal Treasurer", "name_fr" => "Trésorier municipal certifié en Californie" ],
            [ "name" => "Certified Government Financial Manager", "name_fr" => "Gestionnaire financier agréé" ],
            [ "name" => "Certified Government Finance Officer", "name_fr" => "Agent des finances du gouvernement certifié" ],
            [ "name" => "Certified Management Accountant", "name_fr" => "Comptable en management accrédité" ],
            [ "name" => "Certified Municipal Finance Officer", "name_fr" => "Agent de finances municipales certifié" ],
            [ "name" => "Certified Public Finance Administrator", "name_fr" => "Administrateur certifié des finances publiques" ],
            [ "name" => "Certified Public Finance Officer", "name_fr" => "Agent des finances publiques certifié" ],
            [ "name" => "Chartered Property Casualty Underwriter", "name_fr" => "Souscripteur de dommages aux biens à charte" ],
            [ "name" => "Certified Defense Financial Manager", "name_fr" => "Gestionnaire financier certifié de la Défense" ],
            [ "name" => "Registered Tax Return Preparer", "name_fr" => "Préparateur de déclarations de revenus enregistré" ],
            [ "name" => "Enrolled Agent", "name_fr" => "Agent inscrit" ],
            [ "name" => "Fraternal Insurance Counselor Fellow", "name_fr" => "Conseiller en fraternité en assurance" ],
            [ "name" => "Fraternal Insurance Counselor", "name_fr" => "Conseiller en assurance fraternelle" ],
            [ "name" => "Certified Corporate FP&A Professional", "name_fr" => "Professionnel certifié FP & A Professional" ],
            [ "name" => "ISSP Sustainability", "name_fr" => "La durabilité de l'ISSP" ],
            [ "name" => "Certified Treasury Professional", "name_fr" => "Certified Treasury Professional" ],
            [ "name" => "Certified Trust and Financial Advisor", "name_fr" => "Conseiller fiduciaire et financier agréé" ],
            [ "name" => "Certified Turnaround Professional", "name_fr" => "Professionnel certifié Turnaround" ],
            [ "name" => "Registered Financial Planner", "name_fr" => "Planificateur financier inscrit" ],
            [ "name" => "Financial Risk Manager", "name_fr" => "Gestionnaire des risques financiers" ],
            [ "name" => "Professional Risk Manager", "name_fr" => "Gestionnaire de risques professionnels" ],
            [ "name" => "Associate of the Society of Actuaries", "name_fr" => "Associé de la Society of Actuaries" ],
            [ "name" => "Fellow of the Society of Actuaries", "name_fr" => "Fellow de la Society of Actuaries" ],
            [ "name" => "Chartered Enterprise Risk Analyst", "name_fr" => "Analyste de risque d'entreprise agréé" ],
            [ "name" => "Associate of the Casualty Actuarial Society", "name_fr" => "Associé de la Casualty Actuarial Society" ],
            [ "name" => "Fellow of the Casualty Actuarial Society", "name_fr" => "Fellow de la Casualty Actuarial Society" ],
            [ "name" => "Member of the American Academy of Actuaries", "name_fr" => "Membre de l'American Academy of Actuaries" ],
            [ "name" => "Associate of the Conference of Consulting Actuaries", "name_fr" => "Associé de la Conférence des actuaires-conseils" ],
            [ "name" => "Fellow of the Conference of Consulting Actuaries", "name_fr" => "Fellow de la Conférence des actuaires-conseils" ],
            [ "name" => "Enrolled Actuary", "name_fr" => "Actuaire inscrit" ],
            [ "name" => "Registered Architect", "name_fr" => "Architecte enregistré" ],
            [ "name" => "Professional Landscape Architect", "name_fr" => "Architecte paysagiste professionnel" ],
            [ "name" => "Registered Interior Designer", "name_fr" => "Architecte d'intérieur inscrit" ],
            [ "name" => "National Council of Architectural Registration Boards Certified", "name_fr" => "Conseil national des commissions d'enregistrement architectural certifié" ],
            [ "name" => "National Council for Interior Design Qualification Certified", "name_fr" => "Conseil national pour la qualification de design d'intérieur Certifié" ],
            [ "name" => "Association of Licensed Architects Member", "name_fr" => "Association of Licensed Architects Membre" ],
            [ "name" => "Association of Licensed Architects Fellow", "name_fr" => "Association des architectes agréés" ],
            [ "name" => "American Institute of Architects Member", "name_fr" => "American Institute of Architects Membre" ],
            [ "name" => "American College of Healthcare Architects", "name_fr" => "Collège américain des architectes de la santé" ],
            [ "name" => "American College of Healthcare Architects Fellow", "name_fr" => "Membre de l'American College of Healthcare Architects" ],
            [ "name" => "American Institute of Architects Fellow", "name_fr" => "Membre de l'American Institute of Architects" ],
            [ "name" => "American Institute of Certified Planners", "name_fr" => "Institut américain des planificateurs certifiés" ],
            [ "name" => "American Society of Interior Designers Member", "name_fr" => "American Society of Interior Designers Membre" ],
            [ "name" => "American Society of Interior Designers Fellow", "name_fr" => "Associé de l'American Society of Interior Designers" ],
            [ "name" => "Council of Educators in Landscape Architecture Member", "name_fr" => "Conseil des éducateurs en architecture du paysage" ],
            [ "name" => "Council of Educators in Landscape Architecture Fellow", "name_fr" => "Conseil des éducateurs en architecture de paysage" ],
            [ "name" => "American Society of Landscape Architects Member", "name_fr" => "American Society of Landscape Architects Membre" ],
            [ "name" => "American Society of Landscape Architects Fellow", "name_fr" => "Bourse de l'American Society of Landscape Architects" ],
            [ "name" => "American Institute of Certified Planners Member", "name_fr" => "American Institute of Certified Planners Membre" ],
            [ "name" => "American Institute of Certified Planners Fellow", "name_fr" => "Membre de l'American Institute of Certified Planners" ],
            [ "name" => "Leadership in Energy and Environmental Design Accredited Professional", "name_fr" => "Leadership en matière d'énergie et de design environnemental Professionnel accrédité" ],
            [ "name" => "Construction Specification Institute Member", "name_fr" => "Construction Specification Institute Membre" ],
            [ "name" => "Construction Document Technologist", "name_fr" => "Technologue de documents de construction" ],
            [ "name" => "Certified Construction Contract Administrator", "name_fr" => "Administrateur de contrat de construction certifié" ],
            [ "name" => "Certified Construction Specifier", "name_fr" => "Spécificateur de construction certifié" ],
            [ "name" => "Certified Construction Product Representative", "name_fr" => "Représentant certifié en produits de construction" ],
            [ "name" => "Certified Association Executive", "name_fr" => "Dirigeant d'association certifié" ],
            [ "name" => "Advanced Certification Administrator", "name_fr" => "Administrateur de certification avancé" ],
            [ "name" => "Basic Certification Administrator", "name_fr" => "Administrateur de certification de base" ],
            [ "name" => "Certified Fundraising Executive", "name_fr" => "Gestionnaire certifié de collecte de fonds" ],
            [ "name" => "Certified Nonprofit Professional", "name_fr" => "Professionnel certifié à but non lucratif" ],
            [ "name" => "Certified Radio Operator", "name_fr" => "Opérateur de radio certifié" ],
            [ "name" => "Certified Television Operator", "name_fr" => "Opérateur de télévision certifié" ],
            [ "name" => "Certified Broadcast Networking Technologist", "name_fr" => "Technologue certifié en réseautage de diffusion" ],
            [ "name" => "Certified Broadcast Technologist", "name_fr" => "Technologue de radiodiffusion certifié" ],
            [ "name" => "Certified Audio Engineer", "name_fr" => "Ingénieur Audio Certifié" ],
            [ "name" => "Certified Broadcast Television Engineer", "name_fr" => "Ingénieur de Télévision Certifiée" ],
            [ "name" => "Certified Broadcast Networking Engineer", "name_fr" => "Ingénieur certifié en réseau de diffusion" ],
            [ "name" => "Certified Senior Broadcast Radio Engineer", "name_fr" => "Ingénieur radio certifié radio senior" ],
            [ "name" => "Certified Senior Broadcast Television Engineer", "name_fr" => "Ingénieur de Télévision Senior Broadcast Certifié" ],
            [ "name" => "Certified Professional Broadcast Engineer", "name_fr" => "Ingénieur de diffusion professionnel certifié" ],
            [ "name" => "Certified -VSB Specialist", "name_fr" => "Spécialiste certifié -VSB" ],
            [ "name" => "Certified AM Directional Specialist", "name_fr" => "Spécialiste certifié AM" ],
            [ "name" => "Certified Digital Radio Broadcast Specialist", "name_fr" => "Spécialiste en radiodiffusion numérique certifié" ],
            [ "name" => "Certified Senior Broadcast Engineer", "name_fr" => "Ingénieur de diffusion senior certifié" ],
            [ "name" => "Certified Radio and Television Broadcast Engineer", "name_fr" => "Ingénieur de radio et de télévision certifié" ],
            [ "name" => "Certified Senior Radio and Television Broadcast Engineer", "name_fr" => "Ingénieur principal certifié en radiodiffusion et télévision" ],
            [ "name" => "Certified Commercial Contract Manager", "name_fr" => "Gestionnaire de contrats commerciaux certifiés" ],
            [ "name" => "Contract and Commercial Management Certification", "name_fr" => "Certification de gestion contractuelle et commerciale" ],
            [ "name" => "Certified Federal Contract Manager", "name_fr" => "Gestionnaire des contrats fédéraux certifiés" ],
            [ "name" => "Certified Professional Contract Manager", "name_fr" => "Gestionnaire de contrat professionnel certifié" ],
            [ "name" => "Defense Acquisition Workforce Improvement Act Contracting Certification", "name_fr" => "Acquisition de la Loi sur l'amélioration du personnel d'acquisition de la Défense" ],
            [ "name" => "Federal Acquisition Certification in Contracting", "name_fr" => "Certification d'acquisition fédérale dans les marchés" ],
            [ "name" => "Industry Certification in Contract Management - Defense", "name_fr" => "Certification de l'industrie en gestion de contrat - Défense" ],
            [ "name" => "Industry Certification in Contract Management - Federal", "name_fr" => "Certification de l'industrie en gestion des contrats - Fédéral" ],
            [ "name" => "Member of the International Association for Energy Economics", "name_fr" => "Membre de l'International Association for Energy Economics" ],
            [ "name" => "Certified Emergency Manager", "name_fr" => "Gestionnaire d'urgence certifié" ],
            [ "name" => "Associate Emergency Manager", "name_fr" => "Associé Emergency Manager" ],
            [ "name" => "Certified Floodplain Manager", "name_fr" => "Gestionnaire de plaine d'inondation certifié" ],
            [ "name" => "Fellow of the Academy of Emergency Management", "name_fr" => "Fellow de l'Academy of Emergency Management" ],
            [ "name" => "Emergency Number Professional", "name_fr" => "Numéro d'urgence professionnel" ],
            [ "name" => "Master Exercise Practitioner", "name_fr" => "Maître praticien de l'exercice" ],
            [ "name" => "Registered Public-Safety Leader", "name_fr" => "Chef de la sécurité publique enregistré" ],
            [ "name" => "Certified Public-Safety Executive", "name_fr" => "Cadre de sécurité publique certifié" ],
            [ "name" => "Certified Fire Executive", "name_fr" => "Directeur des incendies certifié" ],
            [ "name" => "National Crime Prevention Specialist", "name_fr" => "Spécialiste national en prévention du crime" ],
            [ "name" => "Professional Engineer", "name_fr" => "Ingénieur professionnel" ],
            [ "name" => "Model Law Engineer", "name_fr" => "Ingénieur en droit des modèles" ],
            [ "name" => "Professional Land Surveyor", "name_fr" => "Arpenteur-géomètre professionnel" ],
            [ "name" => "Model Law Surveyor", "name_fr" => "Arpenteur-géomètre" ],
            [ "name" => "Structural Engineer", "name_fr" => "Ingénieur en structure" ],
            [ "name" => "Structural Engineering Certification Board", "name_fr" => "Conseil de certification en génie des structures" ],
            [ "name" => "Engineer Intern", "name_fr" => "Ingénieur stagiaire" ],
            [ "name" => "Engineer-in-Training", "name_fr" => "Ingénieur en formation" ],
            [ "name" => "National Institute For Certification In Engineering Technologies", "name_fr" => "Institut national de certification en technologies d'ingénierie" ],
            [ "name" => "Certified Engineering Technician", "name_fr" => "Technicien d'ingénierie certifié" ],
            [ "name" => "Member of the National Academy of Engineering", "name_fr" => "Membre de l'Académie Nationale d'Ingénierie" ],
            [ "name" => "Student Member of the Institute of Electrical and Electronics Engineers", "name_fr" => "Membre étudiant de l'Institut des ingénieurs électriques et électroniques" ],
            [ "name" => "Graduate Student Member of the Institute of Electrical and Electronics Engineers", "name_fr" => "Étudiant diplômé Membre de l'Institut des ingénieurs électriciens et électroniciens" ],
            [ "name" => "Associate Member of the Institute of Electrical and Electronics Engineers", "name_fr" => "Membre associé de l'Institut des ingénieurs électriciens et électroniciens" ],
            [ "name" => "Member of the Institute of Electrical and Electronics Engineers", "name_fr" => "Membre de l'Institut des ingénieurs électriques et électroniques" ],
            [ "name" => "Senior Member of the Institute of Electrical and Electronics Engineers", "name_fr" => "Senior Member de l'Institut de l'électricité et de l'électricité" ],
            [ "name" => "Fellow of the Institute of Electrical and Electronics Engineers", "name_fr" => "Fellow de l'Institut des ingénieurs électriques et électroniques" ],
            [ "name" => "Senior Member of the Institute of Industrial Engineers", "name_fr" => "Membre senior de l'Institut des ingénieurs industriels" ],
            [ "name" => "Certified Drafter", "name_fr" => "Dessinateur certifié" ],
            [ "name" => "Professional Geologist", "name_fr" => "Géologue professionnel" ],
            [ "name" => "Geologist-in-Training", "name_fr" => "Géologue en formation" ],
            [ "name" => "Certified Professional Geologist", "name_fr" => "Géologue professionnel certifié" ],
            [ "name" => "Certified Photogrammetrist", "name_fr" => "Photogrammétriste certifié" ],
            [ "name" => "Credentialed Manager", "name_fr" => "Gestionnaire crédité" ],
            [ "name" => "Certified Municipal Clerk", "name_fr" => "Commis municipal certifié" ],
            [ "name" => "Professional County Collector", "name_fr" => "Collecteur de comté professionnel" ],
            [ "name" => "Certified Meeting Professional", "name_fr" => "Certified Meeting Professional" ],
            [ "name" => "Certified in Exhibition Management", "name_fr" => "Certifié en gestion d'exposition" ],
            [ "name" => "Certified Hospitality Digital Marketer", "name_fr" => "Certified Digitality Hospitaler" ],
            [ "name" => "Certified Revenue Management Executive", "name_fr" => "Gestionnaire certifié de la gestion des revenus" ],
            [ "name" => "Certified in Hospitality Business Acumen", "name_fr" => "Certifié dans l'acuité d'affaires d'hospitalité" ],
            [ "name" => "Certified in Hospitality Sales Competences", "name_fr" => "Certifié en compétences de vente hôtelière" ],
            [ "name" => "Certified Hospitality Sales Executive", "name_fr" => "Directeur des Ventes Hospitalité Certifié" ],
            [ "name" => "Certified Guest Service Professional", "name_fr" => "Professionnel certifié du service client" ],
            [ "name" => "Certified Hospitality Administrator", "name_fr" => "Administrateur certifié en hôtellerie" ],
            [ "name" => "Certified Hospitality Educator", "name_fr" => "Éducateur agréé en hôtellerie" ],
            [ "name" => "Certified Hospitality Instructor", "name_fr" => "Instructeur certifié en hôtellerie" ],
            [ "name" => "Certified Room Division Executive", "name_fr" => "Directeur de la salle certifiée" ],
            [ "name" => "Certified Hospitality Revenue Manager", "name_fr" => "Gestionnaire de recettes d'accueil agréé" ],
            [ "name" => "Certified Lodging Security Director", "name_fr" => "Directeur de la sécurité de l'hébergement certifié" ],
            [ "name" => "Certified Interpretive Guide", "name_fr" => "Guide d'interprétation certifié" ],
            [ "name" => "Certified Park & Recreation Professional", "name_fr" => "Professionnel certifié en parcs et loisirs" ],
            [ "name" => "Certified Park & Recreation Executive", "name_fr" => "Gestionnaire certifié des parcs et des loisirs" ],
            [ "name" => "Certified Playground Safety Inspector", "name_fr" => "Inspecteur certifié de la sécurité des terrains de jeux" ],
            [ "name" => "Certified Youth Sports Administrator", "name_fr" => "Administrateur sportif certifié pour la jeunesse" ],
            [ "name" => "Certified Wedding and Event Planner", "name_fr" => "Mariage certifié et planificateur d'événements" ],
            [ "name" => "Certified Wedding Planner", "name_fr" => "Planificateur de mariage certifié" ],
            [ "name" => "Certified Sommelier", "name_fr" => "Sommelier certifié" ],
            [ "name" => "Master Sommelier", "name_fr" => "Maître Sommelier" ],
            [ "name" => "SHRM Certified Professional", "name_fr" => "SHRM Certified Professional" ],
            [ "name" => "SHRM Senior Certified Professional", "name_fr" => "SHRM Senior Certified Professional" ],
            [ "name" => "Certified Benefits Professional", "name_fr" => "Professionnel certifié des avantages" ],
            [ "name" => "Certified Compensation Professional", "name_fr" => "Professionnel de la rémunération certifié" ],
            [ "name" => "Global Remuneration Professional", "name_fr" => "Professionnel de la rémunération globale" ],
            [ "name" => "Associate Professional in Human Resources", "name_fr" => "Professionnel associé en ressources humaines" ],
            [ "name" => "Professional in Human Resources", "name_fr" => "Professionnel en ressources humaines" ],
            [ "name" => "Senior Professional in Human Resources", "name_fr" => "Professionnel principal en ressources humaines" ],
            [ "name" => "Global Professional in Human Resources", "name_fr" => "Professionnel mondial en ressources humaines" ],
            [ "name" => "Certified Employee Benefits Specialist", "name_fr" => "Spécialiste des avantages sociaux des employés certifiés" ],
            [ "name" => "Group Benefits Associate", "name_fr" => "Associé aux avantages sociaux" ],
            [ "name" => "Compensation Management Specialist", "name_fr" => "Spécialiste en gestion de la rémunération" ],
            [ "name" => "Retirement Plans Associate", "name_fr" => "Associé aux régimes de retraite" ],
            [ "name" => "Certification in Volunteer Administration", "name_fr" => "Certification en administration des bénévoles" ],
            [ "name" => "Certified in Conflict Manager", "name_fr" => "Certifié dans Conflict Manager" ],
            [ "name" => "Certified Computer Examiner", "name_fr" => "Examinateur d'ordinateur certifié" ],
            [ "name" => "Certified Green IT Professional", "name_fr" => "Professionnel certifié en informatique verte" ],
            [ "name" => "Certified Chief Information Security Officer", "name_fr" => "Chef de la sécurité de l'information certifié" ],
            [ "name" => "Certified Ethical Hacker", "name_fr" => "Hacker éthique certifié" ],
            [ "name" => "Certified Forensic Computer Examiner", "name_fr" => "Analyste en informatique légale certifiée" ],
            [ "name" => "CloudMASTER", "name_fr" => "CloudMASTER" ],
            [ "name" => "CyberSec First Responder", "name_fr" => "CyberSec Premier répondant" ],
            [ "name" => "Certified Information Professional", "name_fr" => "Professionnel de l'information certifié" ],
            [ "name" => "Certified Information Systems Auditor", "name_fr" => "Vérificateur certifié de systèmes d'information" ],
            [ "name" => "Certified Information Security Manager", "name_fr" => "Gestionnaire de la sécurité de l'information certifié" ],
            [ "name" => "Certified Information Systems Security Professional", "name_fr" => "Professionnel certifié en sécurité des systèmes d'information" ],
            [ "name" => "Certified Network Professional", "name_fr" => "Professionnel certifié en réseau" ],
            [ "name" => "Certified in Risk and Information Systems Control", "name_fr" => "Certifié en contrôle des risques et des systèmes d'information" ],
            [ "name" => "Certified Scrum Master", "name_fr" => "Master certifié Scrum" ],
            [ "name" => "Certified Scrum Professional", "name_fr" => "Certified Scrum Professional" ],
            [ "name" => "Certified Scrum Product Owner", "name_fr" => "Propriétaire du produit certifié Scrum" ],
            [ "name" => "Certified Secure Computer User", "name_fr" => "Utilisateur certifié d'ordinateur sécurisé" ],
            [ "name" => "Certified Software Tester", "name_fr" => "Testeur de logiciel certifié" ],
            [ "name" => "Certified Virtualization Professional", "name_fr" => "Professionnel certifié en virtualisation" ],
            [ "name" => "Comptia Advanced Security Practitioner", "name_fr" => "Comptia Advanced Security Practitioner" ],
            [ "name" => "Cisco Certified Network Associate", "name_fr" => "Cisco Certified Network Associate" ],
            [ "name" => "Cisco Certified Network Professional", "name_fr" => "Professionnel certifié du réseau Cisco" ],
            [ "name" => "Cisco Certified Internetworking Expert", "name_fr" => "Cisco Certified Internetworking Expert" ],
            [ "name" => "CyberSAFE", "name_fr" => "CyberSAFE" ],
            [ "name" => "Cyber Secure Coder", "name_fr" => "Cyber ​​Secure Coder" ],
            [ "name" => "IT Infrastructure Library Certified", "name_fr" => "Bibliothèque d'infrastructure informatique certifiée" ],
            [ "name" => "Master Mobile Application Developer", "name_fr" => "Maître Mobile Application Developer" ],
            [ "name" => "Master of Mobile Application Security", "name_fr" => "Master de la sécurité des applications mobiles" ],
            [ "name" => "Microsoft Certified Database Administrator", "name_fr" => "Administrateur de base de données Microsoft Certified" ],
            [ "name" => "Microsoft Certified Systems Administrator", "name_fr" => "Administrateur système certifié Microsoft" ],
            [ "name" => "Microsoft Certified Systems Engineer", "name_fr" => "Ingénieur système certifié Microsoft" ],
            [ "name" => "Microsoft Certified Professional", "name_fr" => "Microsoft Certified Professional" ],
            [ "name" => "Microsoft Certified Trainer", "name_fr" => "Microsoft Certified Trainer" ],
            [ "name" => "Modern Certified Classroom Trainer", "name_fr" => "Entraîneur de salle de classe certifié moderne" ],
            [ "name" => "Oracle Certified Professional", "name_fr" => "Professionnel certifié Oracle" ],
            [ "name" => "SAFe Agilist", "name_fr" => "SAFe Agilist" ],
            [ "name" => "SAFe Advanced Scrum Masters", "name_fr" => "SAFe Advanced Scrum Masters" ],
            [ "name" => "Training from the BACK of the Room Certified Trainer", "name_fr" => "Formation du formateur certifié BACK of the Room" ],
            [ "name" => "VMware Certified Professional", "name_fr" => "Professionnel certifié VMware" ],
            [ "name" => "Juris Doctor", "name_fr" => "Juris Docteur" ],
            [ "name" => "Master of Laws", "name_fr" => "Maître des lois" ],
            [ "name" => "Esquire", "name_fr" => "Écuyer" ],
            [ "name" => "Bachelor of Civil Law", "name_fr" => "Baccalauréat en droit civil" ],
            [ "name" => "Justice of the Peace", "name_fr" => "Justice de paix" ],
            [ "name" => "Notary Public", "name_fr" => "Notaire" ],
            [ "name" => "Board Certified Civil Trial Attorney", "name_fr" => "Conseil d'avocat civil certifié" ],
            [ "name" => "Board Certified Criminal Trial Attorney", "name_fr" => "Conseil certifié en matière pénale" ],
            [ "name" => "Board Certified Family Law Attorney", "name_fr" => "Conseil agréé en droit de la famille" ],
            [ "name" => "Certified Legal Assistant", "name_fr" => "Assistant juridique agréé" ],
            [ "name" => "Certified Paralegal", "name_fr" => "Parajuriste certifié" ],
            [ "name" => "Advanced Certified Paralegal", "name_fr" => "Parajuriste certifié avancé" ],
            [ "name" => "Accredited Legal Professional", "name_fr" => "Professionnel juridique agréé" ],
            [ "name" => "Professional Legal Secretary", "name_fr" => "Secrétaire juridique professionnel" ],
            [ "name" => "Professional Paralegal", "name_fr" => "Parajuriste professionnel" ],
            [ "name" => "Registered Paralegal", "name_fr" => "Parajuriste inscrit" ],
            [ "name" => "CORE Registered Paralegal", "name_fr" => "CORE Registered Paralegal" ],
            [ "name" => "Certified Professional Logistician", "name_fr" => "Logisticien professionnel certifié" ],
            [ "name" => "American Board of Professional Psychology", "name_fr" => "Conseil américain de psychologie professionnelle" ],
            [ "name" => "Certified Genetic Counselor", "name_fr" => "Conseiller génétique certifié" ],
            [ "name" => "Certified Health Education Specialist", "name_fr" => "Spécialiste certifié en éducation pour la santé" ],
            [ "name" => "Master Certified Health Education Specialist", "name_fr" => "Spécialiste certifié en éducation à la santé" ],
            [ "name" => "Master of Public Health", "name_fr" => "Master de Santé Publique" ],
            [ "name" => "Certified Director of Assisted Living", "name_fr" => "Directeur certifié de la vie assistée" ],
            [ "name" => "Certified HIPAA Privacy Associate", "name_fr" => "Associé de confidentialité certifié HIPAA" ],
            [ "name" => "Certified HIPAA Privacy Expert", "name_fr" => "Expert en confidentialité certifié HIPAA" ],
            [ "name" => "Certified HIPAA Privacy Security Expert", "name_fr" => "Expert certifié en sécurité HIPAA" ],
            [ "name" => "Certified HIPAA Professional", "name_fr" => "Professionnel certifié HIPAA" ],
            [ "name" => "Certified Professional in Infection Control", "name_fr" => "Professionnel certifié en contrôle des infections" ],
            [ "name" => "Certified Hospice and Palliative Licensed Nurse", "name_fr" => "Hospice certifié et infirmière autorisée en soins palliatifs" ],
            [ "name" => "Certified HIPAA Security Expert", "name_fr" => "Expert en sécurité certifié HIPAA" ],
            [ "name" => "Certified HIPAA Security Specialist", "name_fr" => "Spécialiste certifié en sécurité HIPAA" ],
            [ "name" => "Certified Veterinary Assistant", "name_fr" => "Assistant Vétérinaire Certifié" ],
            [ "name" => "Doctor of Veterinary Medicine", "name_fr" => "Docteur en médecine vétérinaire" ],
            [ "name" => "Diplomate of the American College of Veterinary Internal Medicie", "name_fr" => "Diplomate de l'American College of Veterinary Internal Medicie" ],
            [ "name" => "Doctor of Chiropractic", "name_fr" => "Docteur en chiropratique" ],
            [ "name" => "Doctor of Dental Surgery", "name_fr" => "Docteur en chirurgie dentaire" ],
            [ "name" => "Doctor of Psychology", "name_fr" => "Docteur en psychologie" ],
            [ "name" => "Doctor of Dental Medicine", "name_fr" => "Docteur en médecine dentaire" ],
            [ "name" => "Doctor of Medicine", "name_fr" => "Docteur en médecine" ],
            [ "name" => "Doctor of Naturopathic Medicine", "name_fr" => "Docteur en médecine naturopathique" ],
            [ "name" => "Doctor of Nursing Practice", "name_fr" => "Docteur en pratique infirmière" ],
            [ "name" => "Doctor of Optometry", "name_fr" => "Docteur en optométrie" ],
            [ "name" => "Doctor of Osteopathic Medicine", "name_fr" => "Docteur en médecine ostéopathique" ],
            [ "name" => "Doctor of Podiatric Medicine", "name_fr" => "Docteur en médecine podiatrique" ],
            [ "name" => "Emergency Medical Dispatcher", "name_fr" => "Dispatcher médical d'urgence" ],
            [ "name" => "Nationally Registered Emergency Medical Responder", "name_fr" => "Répondeur médical d'urgence enregistré au niveau national" ],
            [ "name" => "Emergency Medical Technician - Basic", "name_fr" => "Technicien médical d'urgence - Base" ],
            [ "name" => "Nationally Registered Emergency Medical Technician", "name_fr" => "Technicien médical d'urgence enregistré nationalement" ],
            [ "name" => "Emergency Medical Technician - Intermediate/", "name_fr" => "Technicien médical d'urgence - Intermédiaire /" ],
            [ "name" => "Emergency Medical Technician - Intermediate/", "name_fr" => "Technicien médical d'urgence - Intermédiaire /" ],
            [ "name" => "Nationally Registered Advanced Emergency Medical Technician", "name_fr" => "Technicien médical d'urgence avancé enregistré à l'échelle nationale" ],
            [ "name" => "Emergency Medical Technician - Paramedic", "name_fr" => "Technicien médical d'urgence - Paramédic" ],
            [ "name" => "Nationally Registered Paramedic", "name_fr" => "Paramédic national enregistré" ],
            [ "name" => "Licensed Paramedic(Texas)", "name_fr" => "Paramédic autorisé (Texas)" ],
            [ "name" => "Licensed Practical Nurse", "name_fr" => "Infirmière auxiliaire autorisée" ],
            [ "name" => "Registered Nurse", "name_fr" => "Infirmière autorisée" ],
            [ "name" => "Advanced Practice Nurse", "name_fr" => "Infirmière de pratique avancée" ],
            [ "name" => "Advanced Practice Registered Nurse", "name_fr" => "Infirmière autorisée de pratique avancée" ],
            [ "name" => "Certified Massage Therapist", "name_fr" => "Massothérapeute certifié" ],
            [ "name" => "Licensed Massage Therapist", "name_fr" => "Massothérapeute autorisé" ],
            [ "name" => "Licensed Clinical Massage Therapist", "name_fr" => "Massothérapeute clinique autorisé" ],
            [ "name" => "Licensed Midwife", "name_fr" => "Sage-femme autorisée" ],
            [ "name" => "Certified Midwife", "name_fr" => "Sage-femme certifiée" ],
            [ "name" => "Certified Professional Midwife", "name_fr" => "Sage-femme professionnelle certifiée" ],
            [ "name" => "Certified Nurse-Midwife", "name_fr" => "Infirmière-sage-femme certifiée" ],
            [ "name" => "Certified Registered Nurse Anesthetist", "name_fr" => "Anesthésiste diplômé certifié" ],
            [ "name" => "Nurse Practitioner", "name_fr" => "Infirmière praticienne" ],
            [ "name" => "Marine Physician Assistant", "name_fr" => "Assistant de médecine maritime" ],
            [ "name" => "Occupational Therapist", "name_fr" => "Ergothérapeute" ],
            [ "name" => "Physician Assistant", "name_fr" => "Médecin assistant" ],
            [ "name" => "Registered Veterinary Technician", "name_fr" => "Technicien vétérinaire inscrit" ],
            [ "name" => "Physical Therapist", "name_fr" => "Physiothérapeute" ],
            [ "name" => "Physical Therapy Assistant", "name_fr" => "Assistant en physiothérapie" ],
            [ "name" => "Certified in Public Health", "name_fr" => "Certifié en santé publique" ],
            [ "name" => "Medical Laboratory Scientist", "name_fr" => "Scientifique de laboratoire médical" ],
            [ "name" => "Medical Technologist", "name_fr" => "Technologue médical" ],
            [ "name" => "Medical Laboratory Technician", "name_fr" => "Technicien de laboratoire médical" ],
            [ "name" => "Licensed Professional Counselor", "name_fr" => "Conseiller professionnel agréé" ],
            [ "name" => "Licensed Associate Counselor", "name_fr" => "Conseillère associée agréée" ],
            [ "name" => "Licensed Master Social Worker", "name_fr" => "Maître travailleur social licencié" ],
            [ "name" => "Licensed Clinical Social Worker", "name_fr" => "Travailleur social clinique autorisé" ],
            [ "name" => "Licensed Veterinary Technician", "name_fr" => "Technicien vétérinaire autorisé" ],
            [ "name" => "Qualified Clinical Social Worker", "name_fr" => "Travailleur social clinique qualifié" ],
            [ "name" => "Certified Tissue Bank Specialist", "name_fr" => "Spécialiste certifié en banque de tissus" ],
            [ "name" => "Certified Hypnotherapist", "name_fr" => "Hypnothérapeute certifié" ],
            [ "name" => "National Board Certified Clinical Hypnotherapist", "name_fr" => "Hypnothérapeute clinique certifié par le Conseil national" ],
            [ "name" => "National Board Certified Clinical Hypnotherapist in Public Service", "name_fr" => "Hypnothérapeute clinique agréé par le Conseil national dans la fonction publique" ],
            [ "name" => "National Board Certified Diplomate in Clinical Hypnotherapy", "name_fr" => "Diplômé du Conseil national en hypnothérapie clinique" ],
            [ "name" => "National Board Certified Diplomate in Clinical Hypnotherapy in Public Service", "name_fr" => "Diplômé du Conseil national en hypnothérapie clinique dans la fonction publique" ],
            [ "name" => "National Board Certified Fellow in Clinical Hypnotherapy", "name_fr" => "Membre du conseil d'administration de l'hypnothérapie clinique" ],
            [ "name" => "National Board Certified Fellow in Clinical Hypnotherapy in Public Service", "name_fr" => "Membre du conseil d'administration du programme national d'hypnothérapie clinique dans la fonction publique" ],
            [ "name" => "Licensed Acupuncturist", "name_fr" => "Acupuncteur agréé" ],
            [ "name" => "Diplomate in Acupuncture", "name_fr" => "Diplomate en Acupuncture" ],
            [ "name" => "Diplomate in Oriental Medicine", "name_fr" => "Diplomate en médecine orientale" ],
            [ "name" => "Fellow of the American Society for Parenteral and Enteral Nutrition", "name_fr" => "Fellow de la Société américaine de nutrition parentérale et entérale" ],
            [ "name" => "American Geriatrics Society Fellow", "name_fr" => "Membre de la American Geriatrics Society" ],
            [ "name" => "Fellow of the American Academy of Nursing", "name_fr" => "Fellow de l'American Academy of Nursing" ],
            [ "name" => "Fellow of the American Society of Health-System Pharmacists", "name_fr" => "Fellow de la Société américaine des pharmaciens du système de santé" ],
            [ "name" => "Fellow of the American College of Emergency Physicians", "name_fr" => "Fellow de l'American College of Emergency Physicians" ],
            [ "name" => "Fellow of the Aerospace Medical Association", "name_fr" => "Fellow de l'Association médicale aérospatiale" ],
            [ "name" => "Associate Fellow of the Aerospace Medical Association", "name_fr" => "Membre associé de l'Association médicale aérospatiale" ],
            [ "name" => "Certified Aerospace Physiologist", "name_fr" => "Physiologiste aérospatial certifié" ],
            [ "name" => "Aviation Medical Examiner", "name_fr" => "Médecin examinateur de l'aviation" ],
            [ "name" => "Senior Aviation Medical Examiner", "name_fr" => "Médecin-chef de l'aviation" ],
            [ "name" => "Fellow of the American Academy of Pediatrics", "name_fr" => "Fellow de l'American Academy of Pediatrics" ],
            [ "name" => "Fellow of the American College of Cardiology", "name_fr" => "Fellow de l'American College of Cardiology" ],
            [ "name" => "Fellow of the American College of Dentists", "name_fr" => "Fellow de l'American College of Dentists" ],
            [ "name" => "Fellow of the American College of Endocrinology", "name_fr" => "Fellow de l'American College of Endocrinology" ],
            [ "name" => "Fellow of the American College of Physicians", "name_fr" => "Fellow de l'American College of Physicians" ],
            [ "name" => "Fellow of the American College of Surgeons", "name_fr" => "Fellow de l'American College of Surgeons" ],
            [ "name" => "Fellow of the American College of Osteopathic Family Physicians", "name_fr" => "Fellow du Collège américain des médecins de famille ostéopathes" ],
            [ "name" => "Fellow of the American Congress of Obstetricians and Gynecologists", "name_fr" => "Fellow du Congrès américain des obstétriciens et gynécologues" ],
            [ "name" => "Doctor of Pharmacy", "name_fr" => "Docteur en pharmacie" ],
            [ "name" => "Certified Pharmacy Technician", "name_fr" => "Technicien en pharmacie certifié" ],
            [ "name" => "Registered Pharmacist", "name_fr" => "Pharmacien enregistré" ],
            [ "name" => "Registered Respiratory Therapist", "name_fr" => "Thérapeute respiratoire enregistré" ],
            [ "name" => "Registered Respiratory Therapist, Neonatal & Pediatric Specialist", "name_fr" => "Thérapeute respiratoire autorisé, spécialiste en néonatalogie et en pédiatrie" ],
            [ "name" => "Registered Respiratory Therapist, Sleep Disorder Specialist", "name_fr" => "Thérapeute respiratoire autorisé, spécialiste des troubles du sommeil" ],
            [ "name" => "Registered Respiratory Therapist, Adult Critical Care Specialist", "name_fr" => "Thérapeute respiratoire autorisé, spécialiste des soins aux adultes en soins intensifs" ],
            [ "name" => "Respiratory practitioner", "name_fr" => "Respiratoire" ],
            [ "name" => "Certified Respiratory Therapy Technician", "name_fr" => "Technicien en thérapie respiratoire certifié" ],
            [ "name" => "Certified Respiratory Therapist", "name_fr" => "Thérapeute respiratoire certifié" ],
            [ "name" => "Certified Phlebotomy Technician", "name_fr" => "Technicien certifié en phlébotomie" ],
            [ "name" => "Certified Athletic trainer", "name_fr" => "Entraîneur sportif certifié" ],
            [ "name" => "Certified Medical Assistant", "name_fr" => "Assistant médical certifié" ],
            [ "name" => "Nutrition and Dietetics Technician, Registered", "name_fr" => "Technicien en nutrition et diététique, inscrit" ],
            [ "name" => "Registered Dietitian/Nutritionist", "name_fr" => "Diététiste / nutritionniste" ],
            [ "name" => "United States Army", "name_fr" => "Armée des États-Unis" ],
            [ "name" => "United States Army Reserves", "name_fr" => "Réserves de l'armée des États-Unis" ],
            [ "name" => "United States Navy", "name_fr" => "Marine des États-Unis" ],
            [ "name" => "United States Navy Reserve", "name_fr" => "Réserve de la marine américaine" ],
            [ "name" => "United States Air Force", "name_fr" => "Armée de l'air américaine" ],
            [ "name" => "United States Marine Corps", "name_fr" => "Corps des Marines des États-Unis" ],
            [ "name" => "United States Coast Guard", "name_fr" => "Garde côtière des États-Unis" ],
            [ "name" => "Retired", "name_fr" => "Retraité" ],
            [ "name" => "Veteran", "name_fr" => "Vétéran" ],
            [ "name" => "Member of the Appraisal Institute", "name_fr" => "Membre de l'Institut d'évaluation" ],
            [ "name" => "Senior Residential Appraiser", "name_fr" => "Évaluateur résidentiel senior" ],
            [ "name" => "Accredited Member", "name_fr" => "Membre accrédité" ],
            [ "name" => "Accredited Senior Appraiser", "name_fr" => "Évaluateur Senior Accrédité" ],
            [ "name" => "Assessment Administration Specialist", "name_fr" => "Spécialiste en administration de l'évaluation" ],
            [ "name" => "Certified Assessment Evaluator", "name_fr" => "Évaluateur d'évaluation certifié" ],
            [ "name" => "Cadastral Mapping Specialist", "name_fr" => "Spécialiste de la cartographie cadastrale" ],
            [ "name" => "Personal Property Specialist", "name_fr" => "Spécialiste des biens personnels" ],
            [ "name" => "Residential Evaluation Specialist", "name_fr" => "Spécialiste en évaluation résidentielle" ],
            [ "name" => "Master in Residential Marketing ", "name_fr" => "Master en marketing résidentiel" ],
            [ "name" => "Certified Green Professional ", "name_fr" => "Professionnel certifié vert" ],
            [ "name" => "Certified Graduate Builder", "name_fr" => "Constructeur diplômé certifié" ],
            [ "name" => "Certified Graduate Associate", "name_fr" => "Associé diplômé certifié" ],
            [ "name" => "Master Certified New Home Sales Professional ", "name_fr" => "Master Certified Professionnel de la vente de maisons neuves" ],
            [ "name" => "Certified Aging-in-Place Specialist", "name_fr" => "Spécialiste certifié en vieillissement sur place" ],
            [ "name" => "Certified New Home Marketing Professional ", "name_fr" => "Professionnel certifié en marketing résidentiel neuf" ],
            [ "name" => "Housing Credit Certified Professional ", "name_fr" => "Professionnel agréé en crédit immobilier" ],
            [ "name" => "Certified New Home Sales Professional ", "name_fr" => "Professionnel certifié des ventes de maisons neuves" ],
            [ "name" => "Graduate Master Remodeler ", "name_fr" => "Diplômé Master Remodeler" ],
            [ "name" => "Graduate Master Builder", "name_fr" => "Maître bâtisseur diplômé" ],
            [ "name" => "Certified Graduate Remodeler ", "name_fr" => "Remodeleur diplômé certifié" ],
            [ "name" => "Accredited Buyer's Representative", "name_fr" => "Représentant d'acheteur accrédité" ],
            [ "name" => "Graduate Realtor Institute", "name_fr" => "Graduate Realtor Institute" ],
            [ "name" => "Accredited Land Consultant", "name_fr" => "Expert-conseil accrédité" ],
            [ "name" => "Certified International Property Specialist", "name_fr" => "Spécialiste certifié en propriété internationale" ],
            [ "name" => "Certified Property Manager", "name_fr" => "Gestionnaire immobilier agréé" ],
            [ "name" => "Certified Commercial Investment Member", "name_fr" => "Membre certifié en investissement commercial" ],
            [ "name" => "Certified Corporate Housing Professional", "name_fr" => "Professionnel agréé en logement d'entreprise" ],
            [ "name" => "Member of the National Association of Appraisers", "name_fr" => "Membre de l'Association nationale des évaluateurs" ],
            [ "name" => "General Appraiser", "name_fr" => "Évaluateur général" ],
            [ "name" => "Residential Appraiser", "name_fr" => "Évaluateur résidentiel" ],
            [ "name" => "Doctor of Divinity", "name_fr" => "Docteur en Divinité" ],
            [ "name" => "Doctor of Theology", "name_fr" => "Docteur en théologie" ],
            [ "name" => "Doctor of Ministry", "name_fr" => "Docteur du Ministère" ],
            [ "name" => "Master of Theology", "name_fr" => "Maître de Théologie" ],
            [ "name" => "Master of Divinity", "name_fr" => "Maître de la Divinité" ],
            [ "name" => "Master of Theological Studies", "name_fr" => "Maître des études théologiques" ],
            [ "name" => "Certified Church Business Administrator", "name_fr" => "Administrateur d'entreprise certifié de l'Église" ],
            [ "name" => "Knight/Dame of the Equestrian Order of the Holy Sepulchre of Jerusalem", "name_fr" => "Chevalier / Dame de l'Ordre Equestre du Saint-Sépulcre de Jérusalem" ],
            [ "name" => "Knight/Dame Commander of the Equestrian Order of the Holy Sepulchre of Jerusalem", "name_fr" => "Chevalier / Dame Commandeur de l'Ordre Equestre du Saint-Sépulcre de Jérusalem" ],
            [ "name" => "Knight/Dame Commander with Star of the Equestrian Order of the Holy Sepulchre of Jerusalem", "name_fr" => "Chevalier / Dame Commandeur avec l'Etoile de l'Ordre Equestre du Saint Sépulcre de Jérusalem" ],
            [ "name" => "Knight/Dame Grand Cross of the Equestrian Order of the Holy Sepulchre of Jerusalem", "name_fr" => "Chevalier / Dame Grand-Croix de l'Ordre Equestre du Saint-Sépulcre de Jérusalem" ],
            [ "name" => "Professional Surveyor & Mapper", "name_fr" => "Géomètre professionnel" ],
            [ "name" => "Professional Land Surveyor", "name_fr" => "Arpenteur-géomètre professionnel" ],
            [ "name" => "Registered Land Surveyor", "name_fr" => "Arpenteur-Géomètre" ],
            [ "name" => "Surveyor Intern", "name_fr" => "Stagiaire géomètre" ],
            [ "name" => "Land Surveyor Intern", "name_fr" => "Stagiaire en arpentage" ],
            [ "name" => "Land Surveyor-in-Training", "name_fr" => "Arpenteur-géomètre en formation" ],
            [ "name" => "Certified Federal Surveyor", "name_fr" => "Arpenteur fédéral certifié" ],
            [ "name" => "Broadband Installation Professional", "name_fr" => "Professionnel de l'installation à large bande" ],
            [ "name" => "Broadband Premises Technician", "name_fr" => "Technicien des locaux à large bande" ],
            [ "name" => "Broadband Premises Expert", "name_fr" => "Expert des locaux à large bande" ],
            [ "name" => "Business Class Services Specialist", "name_fr" => "Spécialiste des services aux entreprises" ],
            [ "name" => "Broadband Distribution Specialist", "name_fr" => "Spécialiste en distribution à large bande" ],
            [ "name" => "Broadband Transport Specialist", "name_fr" => "Spécialiste du transport à large bande" ],
            [ "name" => "Broadband TelecomCenter Specialist", "name_fr" => "Spécialiste en télécommunications à large bande" ],
            [ "name" => "DOCSIS® Engineering Professional", "name_fr" => "DOCSIS® Ingénieur professionnel" ],
            [ "name" => "Digital Video Engineering Professional", "name_fr" => "Professionnel de l'ingénierie vidéo numérique" ],
            [ "name" => "Internet Protocol Engineering Professional", "name_fr" => "Professionnel en ingénierie de protocole Internet" ],
            [ "name" => "Certified Professional in Learning and Performance", "name_fr" => "Professionnel certifié en apprentissage et performance" ],
            [ "name" => "Accredited Business Communicator", "name_fr" => "Communicateur d'affaires accrédité" ],
            [ "name" => "Accredited in Public Relations", "name_fr" => "Accrédité en relations publiques" ],
            [ "name" => "Associate Safety Professional", "name_fr" => "Associé Safety Professional" ],
            [ "name" => "Associate in Risk Management", "name_fr" => "Associé en gestion des risques" ],
            [ "name" => "Certified Administrative Professional", "name_fr" => "Professionnel administratif certifié" ],
            [ "name" => "Certified Analytics Professional", "name_fr" => "Certified Analytics Professional" ],
            [ "name" => "Certified Anti-Terrorism Specialist", "name_fr" => "Spécialiste certifié antiterroriste" ],
            [ "name" => "Certified Assistant Refrigeration Operator", "name_fr" => "Opérateur certifié en réfrigération" ],
            [ "name" => "Certified Associate in Project Management", "name_fr" => "Associé certifié en gestion de projet" ],
            [ "name" => "Certified Biological Safety Professional", "name_fr" => "Professionnel certifié en sécurité biologique" ],
            [ "name" => "Certified Broadcast Meteorologist", "name_fr" => "Météorologiste certifié" ],
            [ "name" => "Certified Cost Professional", "name_fr" => "Professionnel certifié des coûts" ],
            [ "name" => "Certified Cost Technician", "name_fr" => "Technicien de coût certifié" ],
            [ "name" => "Certified E-Discovery Specialist", "name_fr" => "Spécialiste certifié E-Discovery" ],
            [ "name" => "Certified Estimating Professional", "name_fr" => "Professionnel de l'estimation certifié" ],
            [ "name" => "Certified Experience Analyst", "name_fr" => "Analyste d'expérience certifiée" ],
            [ "name" => "Certified Fire Protection Specialist", "name_fr" => "Spécialiste certifié en protection incendie" ],
            [ "name" => "Certified Forensic Claims Consultant", "name_fr" => "Expert-conseil en sinistres certifié" ],
            [ "name" => "Certified Forensic Interviewer", "name_fr" => "Certified Forensic Interviewer" ],
            [ "name" => "Certified Hazardous Materials Manager", "name_fr" => "Gestionnaire des matières dangereuses certifiées" ],
            [ "name" => "Certified Industrial Refrigeration Operator", "name_fr" => "Opérateur certifié en réfrigération industrielle" ],
            [ "name" => "Certified Manager", "name_fr" => "Gestionnaire certifié" ],
            [ "name" => "Certified Master Anti-Terrorism Specialist", "name_fr" => "Spécialiste certifié antiterroriste" ],
            [ "name" => "Certified Modeling and Simulation Professional", "name_fr" => "Professionnel certifié en modélisation et simulation" ],
            [ "name" => "Certified Professional in Accessibility Core Competencies", "name_fr" => "Professionnel certifié en compétences de base en accessibilité" ],
            [ "name" => "Certified Professional in Web Accessibility", "name_fr" => "Professionnel certifié en accessibilité Web" ],
            [ "name" => "Certified Protection Professional", "name_fr" => "Professionnel certifié de la protection" ],
            [ "name" => "Certified Public Relations Counselor", "name_fr" => "Conseiller en relations publiques agréé" ],
            [ "name" => "Certified Safety Professional", "name_fr" => "Professionnel de la sécurité certifié" ],
            [ "name" => "Certified Scheduling Technician", "name_fr" => "Technicien d'ordonnancement certifié" ],
            [ "name" => "Certified Systems Engineering Professional", "name_fr" => "Professionnel certifié en génie des systèmes" ],
            [ "name" => "Certified Usability Analyst", "name_fr" => "Analyste d'utilisabilité certifié" ],
            [ "name" => "Certified Utility Safety Professional", "name_fr" => "Professionnel certifié de sécurité utilitaire" ],
            [ "name" => "Certified Youth Development Specialist", "name_fr" => "Spécialiste certifié en développement de la jeunesse" ],
            [ "name" => "Decision & Risk Management Professional", "name_fr" => "Professionnel de la gestion des décisions et des risques" ],
            [ "name" => "Doctor of Musical Arts", "name_fr" => "Docteur en arts musicaux" ],
            [ "name" => "Doctor of Education", "name_fr" => "Docteur en éducation" ],
            [ "name" => "Doctor of Philosophy", "name_fr" => "Docteur en philosophie" ],
            [ "name" => "Doctor of Philosophy Candidate", "name_fr" => "Doctor of Philosophy Candidate" ],
            [ "name" => "Doctor of Philosophy Candidate", "name_fr" => "Doctor of Philosophy Candidate" ],
            [ "name" => "Doctor of Public Health", "name_fr" => "Docteur en santé publique" ],
            [ "name" => "Doctorate of Strategic Security", "name_fr" => "Doctorat de sécurité stratégique" ],
            [ "name" => "Earned Value Professional", "name_fr" => "Valeur professionnelle gagnée" ],
            [ "name" => "Editor in the Life Sciences", "name_fr" => "Éditeur dans les sciences de la vie" ],
            [ "name" => "Fellow of The Explorers Club", "name_fr" => "Fellow du club des explorateurs" ],
            [ "name" => "Fellow of the Society of Decision Professionals", "name_fr" => "Fellow de la Society of Decision Professionals" ],
            [ "name" => "French Wine Scholar", "name_fr" => "Chercheur de vin français" ],
            [ "name" => "ISSP Sustainability Associate", "name_fr" => "Associé en durabilité de l'ISSP" ],
            [ "name" => "ISSP Certified Sustainability Professional", "name_fr" => "Professionnel certifié en durabilité de l'ISSP" ],
            [ "name" => "Licensed Funeral Director", "name_fr" => "Directeur des funérailles autorisé" ],
            [ "name" => "Fellow of the National Speleological Society", "name_fr" => "Fellow de la Société nationale de spéléologie" ],
            [ "name" => "Master of Arts", "name_fr" => "Maître des arts" ],
            [ "name" => "Master of Fine Arts", "name_fr" => "Maître des Beaux-Arts" ],
            [ "name" => "Master of Music", "name_fr" => "Maître de la musique" ],
            [ "name" => "Master of Science", "name_fr" => "Master of Science" ],
            [ "name" => "Master of Business Administration", "name_fr" => "Master en administration des affaires" ],
            [ "name" => "Master of Business and Science", "name_fr" => "Master of Business et Science" ],
            [ "name" => "Master of Public Administration", "name_fr" => "Maître de l'administration publique" ],
            [ "name" => "Member of the ACE", "name_fr" => "Membre de l'ACE" ],
            [ "name" => "Member of the ASC", "name_fr" => "Membre de l'ASC" ],
            [ "name" => "Member of the CSA", "name_fr" => "Membre de l'ASC" ],
            [ "name" => "Member of the MPSE", "name_fr" => "Membre du MPSE" ],
            [ "name" => "Mobile Certified Marketer", "name_fr" => "Mobile Certified Marketer" ],
            [ "name" => "Multi Sport Athlete", "name_fr" => "Athlète Multi Sport" ],
            [ "name" => "National Board Certified Teacher", "name_fr" => "Enseignant certifié par le Conseil national" ],
            [ "name" => "NERC Certified System Operator", "name_fr" => "Opérateur de système certifié NERC" ],
            [ "name" => "Planning & Scheduling Professional", "name_fr" => "Professionnel de la planification et de l'ordonnancement" ],
            [ "name" => "Portfolio Management Professional", "name_fr" => "Professionnel en gestion de portefeuille" ],
            [ "name" => "Professional Certified Investigator", "name_fr" => "Investigateur certifié professionnel" ],
            [ "name" => "Professional Manager Certification", "name_fr" => "Certification de gestionnaire professionnel" ],
            [ "name" => "Program Management Professional", "name_fr" => "Professionnel en gestion de programme" ],
            [ "name" => "Project Management Professional", "name_fr" => "Project Management Professional" ],
            [ "name" => "Professional Science Masters", "name_fr" => "Masters en sciences professionnelles" ],
            [ "name" => "Qualified SWPPP Designer", "name_fr" => "Concepteur SWPPP qualifié" ],
            [ "name" => "Qualified SWPPP Practitioner", "name_fr" => "Praticien SWPPP qualifié" ],
            [ "name" => "Registered Business Analyst", "name_fr" => "Analyste d'affaires enregistré" ],
            [ "name" => "Registered Construction Inspector", "name_fr" => "Inspecteur en construction agréé" ],
            [ "name" => "Registered Professional Archaeologist", "name_fr" => "Archéologue professionnel enregistré" ],
            [ "name" => "RETA Authorized Instructor", "name_fr" => "Instructeur autorisé RETA" ],
            [ "name" => "Systems Security Certified Practitioner", "name_fr" => "Praticien certifié en sécurité des systèmes" ],
            [ "name" => "Web Accessibility Specialist", "name_fr" => "Spécialiste de l'accessibilité Web" ],
            [ "name" => "Licensed Vocational Nurse", "name_fr" => "Infirmière professionnelle autorisée" ],
        ];

        DB::table('certificates')->insert($data);


        /*DB::table('certifications')->delete();
        DB::statement('ALTER TABLE certifications AUTO_INCREMENT = 1');

        $data = [
            [ 'title' => 'Certificate in Investment Performance Measurement' ],
            [ 'title' => 'Chartered Financial Analyst' ],
            [ 'title' => 'Chartered Market Technician' ],
            [ 'title' => 'Chartered Alternative Investment Analyst' ],
            [ 'title' => 'Chartered Management Consultant' ],
            [ 'title' => 'Chartered Global Management Accountant' ],
            [ 'title' => 'Certified Public Accountant' ],
            [ 'title' => 'Certified Financial Planner' ],
            [ 'title' => 'Certified Financial Consultant' ],
            [ 'title' => 'Chartered Life Underwriter' ],
            [ 'title' => 'Certified Fraud Examiner' ],
            [ 'title' => 'Certified Internal Auditor' ],
            [ 'title' => 'Certification in Risk Management Assurance' ],
            [ 'title' => 'Certified Government Auditing Professional' ],
            [ 'title' => 'Certified Payroll Professional' ],
            [ 'title' => 'Fundamental Payroll Certification' ],
            [ 'title' => 'Certified California Municipal Treasurer' ],
            [ 'title' => 'Certified Government Financial Manager' ],
            [ 'title' => 'Certified Government Finance Officer' ],
            [ 'title' => 'Certified Management Accountant' ],
            [ 'title' => 'Certified Municipal Finance Officer' ],
            [ 'title' => 'Certified Public Finance Administrator' ],
            [ 'title' => 'Certified Public Finance Officer' ],
            [ 'title' => 'Certified Public Finance Administrator' ],
            [ 'title' => 'Certified Defense Financial Manager' ],
            [ 'title' => 'Registered Tax Return Preparer' ],
            [ 'title' => 'Enrolled Agent' ],
            [ 'title' => 'Fraternal Insurance Counselor Fellow' ],
            [ 'title' => 'Fraternal Insurance Counselor' ],
            [ 'title' => 'Certified Corporate FP&A Professional' ],
            [ 'title' => 'ISSP Sustainability' ],
            [ 'title' => 'Certified Treasury Professional' ],
            [ 'title' => 'Certified Trust and Financial Advisor' ],
            [ 'title' => 'Certified Turnaround Professional' ],
            [ 'title' => 'Registered Financial Planner' ],
            [ 'title' => 'Financial Risk Manager' ],
            [ 'title' => 'Professional Risk Manager' ],
            [ 'title' => 'Associate of the Society of Actuaries' ],
            [ 'title' => 'Fellow of the Society of Actuaries' ],
            [ 'title' => 'Chartered Enterprise Risk Analyst' ],
            [ 'title' => 'Associate of the Casualty Actuarial Society' ],
            [ 'title' => 'Fellow of the Casualty Actuarial Society' ],
            [ 'title' => 'Member of the American Academy of Actuaries' ],
            [ 'title' => 'Associate of the Conference of Consulting Actuaries' ],
            [ 'title' => 'Fellow of the Conference of Consulting Actuaries' ],
            [ 'title' => 'Enrolled Actuary' ],
            [ 'title' => 'Registered Architect' ],
            [ 'title' => 'Professional Landscape Architect' ],
            [ 'title' => 'Registered Interior Designer' ],
            [ 'title' => 'National Council of Architectural Registration Boards Certified' ],
            [ 'title' => 'National Council for Interior Design Qualification Certified' ],
            [ 'title' => 'Association of Licensed Architects Member' ],
            [ 'title' => 'Association of Licensed Architects Fellow' ],
            [ 'title' => 'American Institute of Architects Member' ],
            [ 'title' => 'American College of Healthcare Architects' ],
            [ 'title' => 'American College of Healthcare Architects Fellow' ],
            [ 'title' => 'American Institute of Architects Fellow' ],
            [ 'title' => 'American Institute of Certified Planners' ],
            [ 'title' => 'American Society of Interior Designers Member' ],
            [ 'title' => 'American Society of Interior Designers Fellow' ],
            [ 'title' => 'Council of Educators in Landscape Architecture Member' ],
            [ 'title' => 'Council of Educators in Landscape Architecture Fellow' ],
            [ 'title' => 'American Society of Landscape Architects Member' ],
            [ 'title' => 'American Society of Landscape Architects Fellow' ],
            [ 'title' => 'American Institute of Certified Planners Member' ],
            [ 'title' => 'American Institute of Certified Planners Fellow' ],
            [ 'title' => 'Leadership in Energy and Environmental Design Accredited Professional' ],
            [ 'title' => 'Construction Specification Institute Member' ],
            [ 'title' => 'Construction Document Technologist' ],
            [ 'title' => 'Certified Construction Contract Administrator' ],
            [ 'title' => 'Certified Construction Specifier' ],
            [ 'title' => 'Certified Construction Product Representative' ],
            [ 'title' => 'Certified Association Executive' ],
            [ 'title' => 'Advanced Certification Administrator' ],
            [ 'title' => 'Basic Certification Administrator' ],
            [ 'title' => 'Certified Fundraising Executive' ],
            [ 'title' => 'Certified Nonprofit Professional' ],
            [ 'title' => 'Certified Radio Operator' ],
            [ 'title' => 'Certified Television Operator' ],
            [ 'title' => 'Certified Broadcast Networking Technologist' ],
            [ 'title' => 'Certified Broadcast Technologist' ],
            [ 'title' => 'Certified Audio Engineer' ],
            [ 'title' => 'Certified Broadcast Television Engineer' ],
            [ 'title' => 'Certified Broadcast Networking Engineer' ],
            [ 'title' => 'Certified Senior Broadcast Radio Engineer' ],
            [ 'title' => 'Certified Senior Broadcast Television Engineer' ],
            [ 'title' => 'Certified Professional Broadcast Engineer' ],
            [ 'title' => 'Certified -VSB Specialist' ],
            [ 'title' => 'Certified AM Directional Specialist' ],
            [ 'title' => 'Certified Digital Radio Broadcast Specialist' ],
            [ 'title' => 'Certified Senior Broadcast Engineer' ],
            [ 'title' => 'Certified Radio and Television Broadcast Engineer' ],
            [ 'title' => 'Certified Senior Radio and Television Broadcast Engineer' ],
            [ 'title' => 'Certified Commercial Contract Manager' ],
            [ 'title' => 'Contract and Commercial Management Certification' ],
            [ 'title' => 'Certified Federal Contract Manager' ],
            [ 'title' => 'Certified Professional Contract Manager' ],
            [ 'title' => 'Defense Acquisition Workforce Improvement Act Contracting Certification' ],
            [ 'title' => 'Federal Acquisition Certification in Contracting' ],
            [ 'title' => 'Industry Certification in Contract Management - Defense' ],
            [ 'title' => 'Industry Certification in Contract Management - Federal' ],
            [ 'title' => 'Member of the International Association for Energy Economics' ],
            [ 'title' => 'Certified Emergency Manager' ],
            [ 'title' => 'Associate Emergency Manager' ],
            [ 'title' => 'Certified Floodplain Manager' ],
            [ 'title' => 'Fellow of the Academy of Emergency Management' ],
            [ 'title' => 'Emergency Number Professional' ],
            [ 'title' => 'Master Exercise Practitioner' ],
            [ 'title' => 'Registered Public-Safety Leader' ],
            [ 'title' => 'Certified Public-Safety Executive' ],
            [ 'title' => 'Certified Fire Executive' ],
            [ 'title' => 'National Crime Prevention Specialist' ],
            [ 'title' => 'Professional Engineer' ],
            [ 'title' => 'Model Law Engineer' ],
            [ 'title' => 'Professional Land Surveyor' ],
            [ 'title' => 'Model Law Surveyor' ],
            [ 'title' => 'Structural Engineer' ],
            [ 'title' => 'Structural Engineering Certification Board' ],
            [ 'title' => 'Engineer Intern' ],
            [ 'title' => 'Engineer-in-Training' ],
            [ 'title' => 'National Institute For Certification In Engineering Technologies' ],
            [ 'title' => 'Certified Engineering Technician' ],
            [ 'title' => 'Member of the National Academy of Engineering' ],
            [ 'title' => 'Student Member of the Institute of Electrical and Electronics Engineers' ],
            [ 'title' => 'Graduate Student Member of the Institute of Electrical and Electronics Engineers' ],
            [ 'title' => 'Associate Member of the Institute of Electrical and Electronics Engineers' ],
            [ 'title' => 'Member of the Institute of Electrical and Electronics Engineers' ],
            [ 'title' => 'Senior Member of the Institute of Electrical and Electronics Engineers' ],
            [ 'title' => 'Fellow of the Institute of Electrical and Electronics Engineers' ],
            [ 'title' => 'Senior Member of the Institute of Industrial Engineers' ],
            [ 'title' => 'Certified Drafter' ],
            [ 'title' => 'Professional Geologist' ],
            [ 'title' => 'Geologist-in-Training' ],
            [ 'title' => 'Certified Professional Geologist' ],
            [ 'title' => 'Certified Photogrammetrist' ],
            [ 'title' => 'Credentialed Manager' ],
            [ 'title' => 'Certified Municipal Clerk' ],
            [ 'title' => 'Professional County Collector' ],
            [ 'title' => 'Certified Meeting Professional' ],
            [ 'title' => 'Certified in Exhibition Management' ],
            [ 'title' => 'Certified Hospitality Digital Marketer' ],
            [ 'title' => 'Certified Revenue Management Executive' ],
            [ 'title' => 'Certified in Hospitality Business Acumen' ],
            [ 'title' => 'Certified in Hospitality Sales Competences' ],
            [ 'title' => 'Certified Hospitality Sales Executive' ],
            [ 'title' => 'Certified Guest Service Professional' ],
            [ 'title' => 'Certified Hospitality Administrator' ],
            [ 'title' => 'Certified Hospitality Educator' ],
            [ 'title' => 'Certified Hospitality Instructor' ],
            [ 'title' => 'Certified Room Division Executive' ],
            [ 'title' => 'Certified Hospitality Revenue Manager' ],
            [ 'title' => 'Certified Lodging Security Director' ],
            [ 'title' => 'Certified Interpretive Guide' ],
            [ 'title' => 'Certified Park & Recreation Professional' ],
            [ 'title' => 'Certified Park & Recreation Executive' ],
            [ 'title' => 'Certified Playground Safety Inspector' ],
            [ 'title' => 'Certified Youth Sports Administrator' ],
            [ 'title' => 'Certified Wedding and Event Planner' ],
            [ 'title' => 'Certified Wedding Planner' ],
            [ 'title' => 'Certified Sommelier' ],
            [ 'title' => 'Master Sommelier' ],
            [ 'title' => 'SHRM Certified Professional' ],
            [ 'title' => 'SHRM Senior Certified Professional' ],
            [ 'title' => 'Certified Benefits Professional' ],
            [ 'title' => 'Certified Compensation Professional' ],
            [ 'title' => 'Global Remuneration Professional' ],
            [ 'title' => 'Associate Professional in Human Resources' ],
            [ 'title' => 'Professional in Human Resources' ],
            [ 'title' => 'Senior Professional in Human Resources' ],
            [ 'title' => 'Global Professional in Human Resources' ],
            [ 'title' => 'Certified Employee Benefits Specialist' ],
            [ 'title' => 'Group Benefits Associate' ],
            [ 'title' => 'Compensation Management Specialist' ],
            [ 'title' => 'Retirement Plans Associate' ],
            [ 'title' => 'Certification in Volunteer Administration' ],
            [ 'title' => 'Certified in Conflict Manager' ],
            [ 'title' => 'Certified Computer Examiner' ],
            [ 'title' => 'Certified Green IT Professional' ],
            [ 'title' => 'Certified Chief Information Security Officer' ],
            [ 'title' => 'Certified Ethical Hacker' ],
            [ 'title' => 'Certified Forensic Computer Examiner' ],
            [ 'title' => 'CloudMASTER' ],
            [ 'title' => 'CyberSec First Responder' ],
            [ 'title' => 'Certified Information Professional' ],
            [ 'title' => 'Certified Information Systems Auditor' ],
            [ 'title' => 'Certified Information Security Manager' ],
            [ 'title' => 'Certified Information Systems Security Professional' ],
            [ 'title' => 'Certified Network Professional' ],
            [ 'title' => 'Certified in Risk and Information Systems Control' ],
            [ 'title' => 'Certified Scrum Master' ],
            [ 'title' => 'Certified Scrum Professional' ],
            [ 'title' => 'Certified Scrum Product Owner' ],
            [ 'title' => 'Certified Secure Computer User' ],
            [ 'title' => 'Certified Software Tester' ],
            [ 'title' => 'Certified Virtualization Professional' ],
            [ 'title' => 'Comptia Advanced Security Practitioner' ],
            [ 'title' => 'Cisco Certified Network Associate' ],
            [ 'title' => 'Cisco Certified Network Professional' ],
            [ 'title' => 'Cisco Certified Internetworking Expert' ],
            [ 'title' => 'CyberSAFE' ],
            [ 'title' => 'Cyber Secure Coder' ],
            [ 'title' => 'IT Infrastructure Library Certified' ],
            [ 'title' => 'Master Mobile Application Developer' ],
            [ 'title' => 'Master of Mobile Application Security' ],
            [ 'title' => 'Microsoft Certified Database Administrator' ],
            [ 'title' => 'Microsoft Certified Systems Administrator' ],
            [ 'title' => 'Microsoft Certified Systems Engineer' ],
            [ 'title' => 'Microsoft Certified Professional' ],
            [ 'title' => 'Microsoft Certified Trainer' ],
            [ 'title' => 'Modern Certified Classroom Trainer' ],
            [ 'title' => 'Oracle Certified Professional' ],
            [ 'title' => 'SAFe Agilist' ],
            [ 'title' => 'SAFe Advanced Scrum Masters' ],
            [ 'title' => 'Training from the BACK of the Room Certified Trainer' ],
            [ 'title' => 'VMware Certified Professional' ],
            [ 'title' => 'Juris Doctor' ],
            [ 'title' => 'Master of Laws' ],
            [ 'title' => 'Esquire' ],
            [ 'title' => 'Bachelor of Civil Law' ],
            [ 'title' => 'Justice of the Peace' ],
            [ 'title' => 'Notary Public' ],
            [ 'title' => 'Board Certified Civil Trial Attorney' ],
            [ 'title' => 'Board Certified Criminal Trial Attorney' ],
            [ 'title' => 'Board Certified Family Law Attorney' ],
            [ 'title' => 'Certified Legal Assistant' ],
            [ 'title' => 'Certified Paralegal' ],
            [ 'title' => 'Advanced Certified Paralegal' ],
            [ 'title' => 'Accredited Legal Professional' ],
            [ 'title' => 'Professional Legal Secretary' ],
            [ 'title' => 'Professional Paralegal' ],
            [ 'title' => 'Registered Paralegal' ],
            [ 'title' => 'CORE Registered Paralegal' ],
            [ 'title' => 'Certified Professional Logistician' ],
            [ 'title' => 'American Board of Professional Psychology' ],
            [ 'title' => 'Certified Genetic Counselor' ],
            [ 'title' => 'Certified Health Education Specialist' ],
            [ 'title' => 'Master Certified Health Education Specialist' ],
            [ 'title' => 'Master of Public Health' ],
            [ 'title' => 'Certified Director of Assisted Living' ],
            [ 'title' => 'Certified HIPAA Privacy Associate' ],
            [ 'title' => 'Certified HIPAA Privacy Expert' ],
            [ 'title' => 'Certified HIPAA Privacy Security Expert' ],
            [ 'title' => 'Certified HIPAA Professional' ],
            [ 'title' => 'Certified Professional in Infection Control' ],
            [ 'title' => 'Certified Hospice and Palliative Licensed Nurse' ],
            [ 'title' => 'Certified HIPAA Security Expert' ],
            [ 'title' => 'Certified HIPAA Security Specialist' ],
            [ 'title' => 'Certified Veterinary Assistant' ],
            [ 'title' => 'Doctor of Veterinary Medicine' ],
            [ 'title' => 'Diplomate of the American College of Veterinary Internal Medicie' ],
            [ 'title' => 'Doctor of Chiropractic' ],
            [ 'title' => 'Doctor of Dental Surgery' ],
            [ 'title' => 'Doctor of Psychology' ],
            [ 'title' => 'Doctor of Dental Medicine' ],
            [ 'title' => 'Doctor of Medicine' ],
            [ 'title' => 'Doctor of Naturopathic Medicine' ],
            [ 'title' => 'Doctor of Nursing Practice' ],
            [ 'title' => 'Doctor of Optometry' ],
            [ 'title' => 'Doctor of Osteopathic Medicine' ],
            [ 'title' => 'Doctor of Podiatric Medicine' ],
            [ 'title' => 'Emergency Medical Dispatcher' ],
            [ 'title' => 'Nationally Registered Emergency Medical Responder' ],
            [ 'title' => 'Emergency Medical Technician - Basic' ],
            [ 'title' => 'Nationally Registered Emergency Medical Technician' ],
            [ 'title' => 'Emergency Medical Technician - Intermediate/' ],
            [ 'title' => 'Emergency Medical Technician - Intermediate/' ],
            [ 'title' => 'Nationally Registered Advanced Emergency Medical Technician' ],
            [ 'title' => 'Emergency Medical Technician - Paramedic' ],
            [ 'title' => 'Nationally Registered Paramedic' ],
            [ 'title' => 'Licensed Paramedic(Texas)' ],
            [ 'title' => 'Licensed Practical Nurse' ],
            [ 'title' => 'Registered Nurse' ],
            [ 'title' => 'Advanced Practice Nurse Advanced Practice Registered Nurse' ],
            [ 'title' => 'Certified Massage Therapist' ],
            [ 'title' => 'Licensed Massage Therapist' ],
            [ 'title' => 'Licensed Clinical Massage Therapist' ],
            [ 'title' => 'Licensed Midwife' ],
            [ 'title' => 'Certified Midwife' ],
            [ 'title' => 'Certified Professional Midwife' ],
            [ 'title' => 'Certified Nurse-Midwife' ],
            [ 'title' => 'Certified Registered Nurse Anesthetist' ],
            [ 'title' => 'Nurse Practitioner' ],
            [ 'title' => 'Marine Physician Assistant' ],
            [ 'title' => 'Occupational Therapist' ],
            [ 'title' => 'Physician Assistant' ],
            [ 'title' => 'Registered Veterinary Technician' ],
            [ 'title' => 'Physical Therapist' ],
            [ 'title' => 'Physical Therapy Assistant' ],
            [ 'title' => 'Certified in Public Health' ],
            [ 'title' => 'Medical Laboratory Scientist' ],
            [ 'title' => 'Medical Technologist' ],
            [ 'title' => 'Medical Laboratory Technician' ],
            [ 'title' => 'Licensed Professional Counselor' ],
            [ 'title' => 'Licensed Associate Counselor' ],
            [ 'title' => 'Licensed Master Social Worker' ],
            [ 'title' => 'Licensed Clinical Social Worker' ],
            [ 'title' => 'Licensed Veterinary Technician' ],
            [ 'title' => 'Qualified Clinical Social Worker' ],
            [ 'title' => 'Certified Tissue Bank Specialist' ],
            [ 'title' => 'Certified Hypnotherapist' ],
            [ 'title' => 'National Board Certified Clinical Hypnotherapist' ],
            [ 'title' => 'National Board Certified Clinical Hypnotherapist in Public Service' ],
            [ 'title' => 'National Board Certified Diplomate in Clinical Hypnotherapy' ],
            [ 'title' => 'National Board Certified Diplomate in Clinical Hypnotherapy in Public Service' ],
            [ 'title' => 'National Board Certified Fellow in Clinical Hypnotherapy' ],
            [ 'title' => 'National Board Certified Fellow in Clinical Hypnotherapy in Public Service' ],
            [ 'title' => 'Licensed Acupuncturist' ],
            [ 'title' => 'Diplomate in Acupuncture' ],
            [ 'title' => 'Diplomate in Oriental Medicine' ],
            [ 'title' => 'Fellow of the American Society for Parenteral and Enteral Nutrition' ],
            [ 'title' => 'American Geriatrics Society Fellow' ],
            [ 'title' => 'Fellow of the American Academy of Nursing' ],
            [ 'title' => 'Fellow of the American Society of Health-System Pharmacists' ],
            [ 'title' => 'Fellow of the American College of Emergency Physicians' ],
            [ 'title' => 'Fellow of the Aerospace Medical Association' ],
            [ 'title' => 'Associate Fellow of the Aerospace Medical Association' ],
            [ 'title' => 'Certified Aerospace Physiologist' ],
            [ 'title' => 'Aviation Medical Examiner' ],
            [ 'title' => 'Senior Aviation Medical Examiner' ],
            [ 'title' => 'Fellow of the American Academy of Pediatrics' ],
            [ 'title' => 'Fellow of the American College of Cardiology' ],
            [ 'title' => 'Fellow of the American College of Dentists' ],
            [ 'title' => 'Fellow of the American College of Endocrinology' ],
            [ 'title' => 'Fellow of the American College of Physicians' ],
            [ 'title' => 'Fellow of the American College of Surgeons' ],
            [ 'title' => 'Fellow of the American College of Osteopathic Family Physicians' ],
            [ 'title' => 'Fellow of the American Congress of Obstetricians and Gynecologists' ],
            [ 'title' => 'Doctor of Pharmacy' ],
            [ 'title' => 'Certified Pharmacy Technician' ],
            [ 'title' => 'Registered Pharmacist' ],
            [ 'title' => 'Registered Respiratory Therapist' ],
            [ 'title' => 'Registered Respiratory Therapist, Neonatal & Pediatric Specialist' ],
            [ 'title' => 'Registered Respiratory Therapist, Sleep Disorder Specialist' ],
            [ 'title' => 'Registered Respiratory Therapist, Adult Critical Care Specialist' ],
            [ 'title' => 'Respiratory practitioner' ],
            [ 'title' => 'Certified Respiratory Therapy Technician' ],
            [ 'title' => 'Certified Respiratory Therapist' ],
            [ 'title' => 'Certified Phlebotomy Technician' ],
            [ 'title' => 'Certified Athletic trainer' ],
            [ 'title' => 'Certified Medical Assistant' ],
            [ 'title' => 'Nutrition and Dietetics Technician, Registered' ],
            [ 'title' => 'Registered Dietitian/Nutritionist' ],
            [ 'title' => 'United States Army' ],
            [ 'title' => 'United States Army Reserves' ],
            [ 'title' => 'United States Navy' ],
            [ 'title' => 'United States Navy Reserve' ],
            [ 'title' => 'United States Air Force' ],
            [ 'title' => 'United States Marine Corps' ],
            [ 'title' => 'United States Coast Guard' ],
            [ 'title' => 'Retired' ],
            [ 'title' => 'Veteran' ],
            [ 'title' => 'Member of the Appraisal Institute' ],
            [ 'title' => 'Senior Residential Appraiser' ],
            [ 'title' => 'Accredited Member' ],
            [ 'title' => 'Accredited Senior Appraiser' ],
            [ 'title' => 'Assessment Administration Specialist' ],
            [ 'title' => 'Certified Assessment Evaluator' ],
            [ 'title' => 'Cadastral Mapping Specialist' ],
            [ 'title' => 'Personal Property Specialist' ],
            [ 'title' => 'Residential Evaluation Specialist' ],
            [ 'title' => 'Master in Residential Marketing ' ],
            [ 'title' => 'Certified Green Professional ' ],
            [ 'title' => 'Certified Graduate Builder' ],
            [ 'title' => 'Certified Graduate Associate' ],
            [ 'title' => 'Master Certified New Home Sales Professional ' ],
            [ 'title' => 'Certified Aging-in-Place Specialist' ],
            [ 'title' => 'Certified New Home Marketing Professional ' ],
            [ 'title' => 'Housing Credit Certified Professional ' ],
            [ 'title' => 'Certified New Home Sales Professional ' ],
            [ 'title' => 'Graduate Master Remodeler ' ],
            [ 'title' => 'Graduate Master Builder' ],
            [ 'title' => 'Certified Graduate Remodeler ' ],
            [ 'title' => 'Accredited Buyer\'s Representative' ],
            [ 'title' => 'Graduate Realtor Institute' ],
            [ 'title' => 'Accredited Land Consultant' ],
            [ 'title' => 'Certified International Property Specialist' ],
            [ 'title' => 'Certified Property Manager' ],
            [ 'title' => 'Certified Commercial Investment Member' ],
            [ 'title' => 'Certified Corporate Housing Professional' ],
            [ 'title' => 'Member of the National Association of Appraisers' ],
            [ 'title' => 'General Appraiser' ],
            [ 'title' => 'Residential Appraiser' ],
            [ 'title' => 'Doctor of Divinity' ],
            [ 'title' => 'Doctor of Theology' ],
            [ 'title' => 'Doctor of Ministry' ],
            [ 'title' => 'Master of Theology' ],
            [ 'title' => 'Master of Divinity' ],
            [ 'title' => 'Master of Theological Studies' ],
            [ 'title' => 'Certified Church Business Administrator' ],
            [ 'title' => 'Knight/Dame of the Equestrian Order of the Holy Sepulchre of Jerusalem' ],
            [ 'title' => 'Knight/Dame Commander of the Equestrian Order of the Holy Sepulchre of Jerusalem' ],
            [ 'title' => 'Knight/Dame Commander with Star of the Equestrian Order of the Holy Sepulchre of Jerusalem' ],
            [ 'title' => 'Knight/Dame Grand Cross of the Equestrian Order of the Holy Sepulchre of Jerusalem' ],
            [ 'title' => 'Professional Surveyor & Mapper' ],
            [ 'title' => 'Professional Land Surveyor' ],
            [ 'title' => 'Registered Land Surveyor' ],
            [ 'title' => 'Surveyor Intern' ],
            [ 'title' => 'Land Surveyor Intern' ],
            [ 'title' => 'Land Surveyor-in-Training' ],
            [ 'title' => 'Certified Federal Surveyor' ],
            [ 'title' => 'Broadband Installation Professional' ],
            [ 'title' => 'Broadband Premises Technician' ],
            [ 'title' => 'Broadband Premises Expert' ],
            [ 'title' => 'Business Class Services Specialist' ],
            [ 'title' => 'Broadband Distribution Specialist' ],
            [ 'title' => 'Broadband Transport Specialist' ],
            [ 'title' => 'Broadband TelecomCenter Specialist' ],
            [ 'title' => 'DOCSIS® Engineering Professional' ],
            [ 'title' => 'Digital Video Engineering Professional' ],
            [ 'title' => 'Internet Protocol Engineering Professional' ],
            [ 'title' => 'Certified Professional in Learning and Performance' ],
            [ 'title' => 'Accredited Business Communicator' ],
            [ 'title' => 'Accredited in Public Relations' ],
            [ 'title' => 'Associate Safety Professional' ],
            [ 'title' => 'Associate in Risk Management' ],
            [ 'title' => 'Certified Administrative Professional' ],
            [ 'title' => 'Certified Analytics Professional' ],
            [ 'title' => 'Certified Anti-Terrorism Specialist' ],
            [ 'title' => 'Certified Assistant Refrigeration Operator' ],
            [ 'title' => 'Certified Associate in Project Management' ],
            [ 'title' => 'Certified Biological Safety Professional' ],
            [ 'title' => 'Certified Broadcast Meteorologist' ],
            [ 'title' => 'Certified Cost Professional' ],
            [ 'title' => 'Certified Cost Technician' ],
            [ 'title' => 'Certified E-Discovery Specialist' ],
            [ 'title' => 'Certified Estimating Professional' ],
            [ 'title' => 'Certified Experience Analyst' ],
            [ 'title' => 'Certified Fire Protection Specialist' ],
            [ 'title' => 'Certified Forensic Claims Consultant' ],
            [ 'title' => 'Certified Forensic Interviewer' ],
            [ 'title' => 'Certified Hazardous Materials Manager' ],
            [ 'title' => 'Certified Industrial Refrigeration Operator' ],
            [ 'title' => 'Certified Manager' ],
            [ 'title' => 'Certified Master Anti-Terrorism Specialist' ],
            [ 'title' => 'Certified Modeling and Simulation Professional' ],
            [ 'title' => 'Certified Professional in Accessibility Core Competencies' ],
            [ 'title' => 'Certified Professional in Web Accessibility' ],
            [ 'title' => 'Certified Protection Professional' ],
            [ 'title' => 'Certified Public Relations Counselor' ],
            [ 'title' => 'Certified Safety Professional' ],
            [ 'title' => 'Certified Scheduling Technician' ],
            [ 'title' => 'Certified Systems Engineering Professional' ],
            [ 'title' => 'Certified Usability Analyst' ],
            [ 'title' => 'Certified Utility Safety Professional' ],
            [ 'title' => 'Certified Youth Development Specialist' ],
            [ 'title' => 'Decision & Risk Management Professional' ],
            [ 'title' => 'Doctor of Musical Arts' ],
            [ 'title' => 'Doctor of Education' ],
            [ 'title' => 'Doctor of Philosophy' ],
            [ 'title' => 'Doctor of Philosophy Candidate' ],
            [ 'title' => 'Doctor of Philosophy Candidate' ],
            [ 'title' => 'Doctor of Public Health' ],
            [ 'title' => 'Doctorate of Strategic Security' ],
            [ 'title' => 'Earned Value Professional' ],
            [ 'title' => 'Editor in the Life Sciences' ],
            [ 'title' => 'Fellow of The Explorers Club' ],
            [ 'title' => 'Fellow of the Society of Decision Professionals' ],
            [ 'title' => 'French Wine Scholar' ],
            [ 'title' => 'ISSP Sustainability Associate' ],
            [ 'title' => 'ISSP Certified Sustainability Professional' ],
            [ 'title' => 'Licensed Funeral Director' ],
            [ 'title' => 'Fellow of the National Speleological Society' ],
            [ 'title' => 'Master of Arts' ],
            [ 'title' => 'Master of Fine Arts' ],
            [ 'title' => 'Master of Music' ],
            [ 'title' => 'Master of Science' ],
            [ 'title' => 'Master of Business Administration' ],
            [ 'title' => 'Master of Business and Science' ],
            [ 'title' => 'Master of Public Administration' ],
            [ 'title' => 'Member of the ACE' ],
            [ 'title' => 'Member of the ASC' ],
            [ 'title' => 'Member of the CSA' ],
            [ 'title' => 'Member of the MPSE' ],
            [ 'title' => 'Mobile Certified Marketer' ],
            [ 'title' => 'Multi Sport Athlete' ],
            [ 'title' => 'National Board Certified Teacher' ],
            [ 'title' => 'NERC Certified System Operator' ],
            [ 'title' => 'Planning & Scheduling Professional' ],
            [ 'title' => 'Portfolio Management Professional' ],
            [ 'title' => 'Professional Certified Investigator' ],
            [ 'title' => 'Professional Manager Certification' ],
            [ 'title' => 'Program Management Professional' ],
            [ 'title' => 'Project Management Professional' ],
            [ 'title' => 'Professional Science Masters' ],
            [ 'title' => 'Qualified SWPPP Designer' ],
            [ 'title' => 'Qualified SWPPP Practitioner' ],
            [ 'title' => 'Registered Business Analyst' ],
            [ 'title' => 'Registered Construction Inspector' ],
            [ 'title' => 'Registered Professional Archaeologist' ],
            [ 'title' => 'RETA Authorized Instructor' ],
            [ 'title' => 'Systems Security Certified Practitioner' ],
            [ 'title' => 'Web Accessibility Specialist' ],
            [ 'title' => 'Licensed Vocational Nurse' ]
        ];

        DB::table('certifications')->insert($data);*/
    }
}
