<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DegreesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('degrees')->delete();
        DB::statement('ALTER TABLE degrees AUTO_INCREMENT = 1');

        $data = [
            [ "title" => "Associate Degree in Administration of Justice", "title_fr" => "Associate Degree en administration de la justice" ],
            [ "title" => "Associate Degree in Advertising", "title_fr" => "Associate Degree en Publicité" ],
            [ "title" => "Associate Degree in Agribusiness", "title_fr" => "Diplôme d'associé en agrobusiness" ],
            [ "title" => "Associate Degree in Animal Management", "title_fr" => "Diplôme d'associé en gestion des animaux" ],
            [ "title" => "Associate Degree in Architectural Building Engineering Technology", "title_fr" => "Diplôme d'associé en technologie du génie architectural du bâtiment" ],
            [ "title" => "Associate Degree in Architecture and Career Options", "title_fr" => "Diplôme d'associé en architecture et options de carrière" ],
            [ "title" => "Associate Degree in Art", "title_fr" => "Associate Degree en Art" ],
            [ "title" => "Associate Degree in Automotive Maintenance Technology", "title_fr" => "Diplôme d'associé en technologie de maintenance automobile" ],
            [ "title" => "Associate Degree in Aviation Mechanics", "title_fr" => "Diplôme d'associé en mécanique aéronautique" ],
            [ "title" => "Associate Degree in Behavioral Science", "title_fr" => "Diplôme d'Associé en Science du Comportement" ],
            [ "title" => "Associate Degree in Boat Mechanics", "title_fr" => "Diplôme d'Associé en Mécanique de Bateau" ],
            [ "title" => "Associate Degree in Boat Repair and Maintenance", "title_fr" => "Diplôme d'associé en réparation et entretien de bateaux" ],
            [ "title" => "Associate Degree in Cabinet Design Technology", "title_fr" => "Diplôme d'associé en technologie de conception de cabinet" ],
            [ "title" => "Associate Degree in Child Development: Program Summary", "title_fr" => "Associate Degree in Child Development: Résumé du programme" ],
            [ "title" => "Associate Degree in Christian Ministry", "title_fr" => "Diplôme d'associé en ministère chrétien" ],
            [ "title" => "Associate Degree in Cosmetology Business", "title_fr" => "Diplôme d'associé en affaires de cosmétologie" ],
            [ "title" => "Associate Degree in Digital Media", "title_fr" => "Associate Degree en médias numériques" ],
            [ "title" => "Associate Degree in Early Childhood Special Education", "title_fr" => "Diplôme d'associé en éducation spécialisée de la petite enfance" ],
            [ "title" => "Associate Degree in Elementary Education", "title_fr" => "Diplôme d'associé en éducation élémentaire" ],
            [ "title" => "Associate Degree in English", "title_fr" => "Associate Degree en anglais" ],
            [ "title" => "Associate Degree in Environmental Science", "title_fr" => "Diplôme d'associé en sciences de l'environnement" ],
            [ "title" => "Associate Degree in Environmental Studies", "title_fr" => "Diplôme d'associé en études environnementales" ],
            [ "title" => "Associate Degree in General Psychology", "title_fr" => "Associate Degree en psychologie générale" ],
            [ "title" => "Associate Degree in History and Information", "title_fr" => "Associate Degree en histoire et information" ],
            [ "title" => "Associate Degree in Interdisciplinary Studies", "title_fr" => "Associé en études interdisciplinaires" ],
            [ "title" => "Associate Degree in International Relations", "title_fr" => "Associate Degree en relations internationales" ],
            [ "title" => "Associate Degree in Landscape Architecture", "title_fr" => "Diplôme d'associé en architecture de paysage" ],
            [ "title" => "Associate Degree in Landscaping Design", "title_fr" => "Diplôme d'associé en aménagement paysager" ],
            [ "title" => "Associate Degree in Library Science", "title_fr" => "Diplôme d'associé en bibliothéconomie" ],
            [ "title" => "Associate Degree in Music", "title_fr" => "Diplôme d'associé en musique" ],
            [ "title" => "Associate Degree in Wildlife Management", "title_fr" => "Diplôme d'associé en gestion de la faune" ],
            [ "title" => "Associate Degree in Education", "title_fr" => "Diplôme d'associé en éducation" ],
            [ "title" => "Associate of Applied Sciencein Accelerated Culinary Arts", "title_fr" => "Associé des sciences appliquées dans les arts culinaires accélérés" ],
            [ "title" => "Associate of Applied Sciencein Accounting Specialist", "title_fr" => "Associé de science appliquée en comptabilité" ],
            [ "title" => "Associate of Applied Sciencein Administrative Support", "title_fr" => "Associé des sciences appliquées dans le soutien administratif" ],
            [ "title" => "Associate of Applied Sciencein Baking and Pastry", "title_fr" => "Associé de la science appliquée à la cuisson et à la pâtisserie" ],
            [ "title" => "Associate of Applied Sciencein Business Administration", "title_fr" => "Associé d'Applied Science in Business Administration" ],
            [ "title" => "Associate of Applied Sciencein Business Administration - Finance", "title_fr" => "Associé d'Applied Science in Business Administration - Finance" ],
            [ "title" => "Associate of Applied Sciencein Business Information Systems", "title_fr" => "Associé des sciences appliquées dans les systèmes d'information d'affaires" ],
            [ "title" => "Associate of Applied Sciencein Civil Justice - Law Enforcement", "title_fr" => "Associé des sciences appliquées en justice civile - Application de la loi" ],
            [ "title" => "Associate of Applied Sciencein Clinical Medical Assisting", "title_fr" => "Associé de Sciences Appliquées en Assistance Médicale Clinique" ],
            [ "title" => "Associate of Applied Sciencein Computer Applications", "title_fr" => "Associé de la science appliquée aux applications informatiques" ],
            [ "title" => "Associate of Applied Sciencein Computer Electronics", "title_fr" => "Associé de Science Appliquée en Électronique Informatique" ],
            [ "title" => "Associate of Applied Sciencein Computer Game Design", "title_fr" => "Associé de science appliquée dans la conception de jeux informatiques" ],
            [ "title" => "Associate of Applied Sciencein Computer Information Systems", "title_fr" => "Associé des sciences appliquées dans les systèmes informatiques" ],
            [ "title" => "Associate of Applied Sciencein Culinary Arts", "title_fr" => "Associé des sciences appliquées en arts culinaires" ],
            [ "title" => "Associate of Applied Sciencein Digital Media Communications", "title_fr" => "Associé de science appliquée aux communications médias numériques" ],
            [ "title" => "Associate of Applied Sciencein Digital Photography", "title_fr" => "Associé de science appliquée à la photographie numérique" ],
            [ "title" => "Associate of Applied Sciencein Electronic Engineering", "title_fr" => "Associé des sciences appliquées en ingénierie électronique" ],
            [ "title" => "Associate of Applied Sciencein Emergency Medical Services", "title_fr" => "Associé des sciences appliquées dans les services médicaux d'urgence" ],
            [ "title" => "Associate of Applied Sciencein Health Care Management", "title_fr" => "Associé des sciences appliquées en gestion des soins de santé" ],
            [ "title" => "Associate of Applied Sciencein Health Information Management", "title_fr" => "Associé des sciences appliquées à la gestion de l'information sur la santé" ],
            [ "title" => "Associate of Applied Sciencein Healthcare Administration", "title_fr" => "Associé d'Applied Science in Healthcare Administration" ],
            [ "title" => "Associate of Applied Sciencein Legal Office E-ministration", "title_fr" => "Associé de Sciences Appliquées au Bureau Légal E-ministration" ],
            [ "title" => "Associate of Applied Sciencein Telecommunications Technology", "title_fr" => "Associé des sciences appliquées dans la technologie des télécommunications" ],
            [ "title" => "Associate of Applied Sciencein Television Production", "title_fr" => "Associé de la science appliquée à la production télévisuelle" ],
            [ "title" => "Associate of Applied Sciencein Visual Communications", "title_fr" => "Associé de Science Appliquée en Communications Visuelles" ],
            [ "title" => "Associate of Artsin Computer Information Systems", "title_fr" => "Associé de Artsin Computer Information Systems" ],
            [ "title" => "Associate of Artsin Internetworking Technology", "title_fr" => "Associé d'Artsin Internetworking Technology" ],
            [ "title" => "Associate of Artsin Psychology", "title_fr" => "Associé de Artsin Psychology" ],
            [ "title" => "Associate of Artsin Interior Architecture and Design", "title_fr" => "Associé d'Artsin Architecture d'intérieur et Design" ],
            [ "title" => "Associate of Biotechnology", "title_fr" => "Associé de la biotechnologie" ],
            [ "title" => "Associate of Business Sciencein Individualized Studies", "title_fr" => "Associé de Business Science dans les études individualisées" ],
            [ "title" => "Associate of Early Childhood Education", "title_fr" => "Associé de l'éducation de la petite enfance" ],
            [ "title" => "Associate of Occupational Studiesin Legal Office Administration", "title_fr" => "Associé d'études professionnelles en administration juridique" ],
            [ "title" => "Associate of Sciencein Computer Information Science", "title_fr" => "Associé de Science en Informatique Science de l'Information" ],
            [ "title" => "Associate of Sciencein Computer Science", "title_fr" => "Associé de Science en Informatique" ],
            [ "title" => "Associate of Sciencein Corrections, Probation, & Parole", "title_fr" => "Associé de la science dans les services correctionnels, la probation et la libération conditionnelle" ],
            [ "title" => "Associate of Sciencein Electronics Engineering Technology", "title_fr" => "Associé de Science en technologie de génie électronique" ],
            [ "title" => "Associate of Sciencein Interactive & Graphic Art", "title_fr" => "Associé de Sciencein Interactive & Graphic Art" ],
            [ "title" => "Associate of Sciencein Industrial Maintenance Technology", "title_fr" => "Associé de Science dans la technologie de maintenance industrielle" ],
            [ "title" => "Bachelor of Architecture", "title_fr" => "bachelier en architecture" ],
            [ "title" => "Bachelor of Biomedical Science", "title_fr" => "Baccalauréat en sciences biomédicales" ],
            [ "title" => "Bachelor of Business Administration", "title_fr" => "Diplôme d'Administration d'Entreprise" ],
            [ "title" => "Bachelor of Clinical Science", "title_fr" => "Baccalauréat en sciences cliniques" ],
            [ "title" => "Bachelor of Commerce", "title_fr" => "Diplômé de l'école de commerce" ],
            [ "title" => "Bachelor of Computer Applications", "title_fr" => "Baccalauréat en informatique" ],
            [ "title" => "Bachelor of Computer Information Systems", "title_fr" => "Baccalauréat en informatique" ],
            [ "title" => "Bachelor of Science in Construction Technology", "title_fr" => "Baccalauréat en sciences de la construction" ],
            [ "title" => "Bachelor of Criminal Justice", "title_fr" => "Baccalauréat en justice pénale" ],
            [ "title" => "Bachelor of Divinity", "title_fr" => "Baccalauréat en divinité" ],
            [ "title" => "Bachelor of Economics", "title_fr" => "Baccalauréat en Économie" ],
            [ "title" => "Bachelor of Education", "title_fr" => "Baccalauréat en éducation" ],
            [ "title" => "Bachelor of Engineering", "title_fr" => "Baccalauréat en génie" ],
            [ "title" => "Bachelor of Fine Arts", "title_fr" => "Baccalauréat en beaux-arts" ],
            [ "title" => "Bachelor of Letters", "title_fr" => "Baccalauréat en lettres" ],
            [ "title" => "Bachelor of Information Systems", "title_fr" => "Baccalauréat en systèmes d'information" ],
            [ "title" => "Bachelor of Management", "title_fr" => "Baccaulauréat en administration" ],
            [ "title" => "Bachelor of Music", "title_fr" => "Baccalauréat en musique" ],
            [ "title" => "Bachelor of Pharmacy", "title_fr" => "Baccalauréat en pharmacie" ],
            [ "title" => "Bachelor of Philosophy", "title_fr" => "Baccalauréat en philosophie" ],
            [ "title" => "Bachelor of Social Work", "title_fr" => "Baccalauréat en travail social" ],
            [ "title" => "Bachelor of Technology", "title_fr" => "Baccalauréat en technologie" ],
            [ "title" => "Bachelor of Accountancy", "title_fr" => "Baccalauréat en comptabilité" ],
            [ "title" => "Bachelor of Arts in American Studies", "title_fr" => "Baccalauréat ès arts en études américaines" ],
            [ "title" => "Bachelor of Arts in American Indian Studies", "title_fr" => "Baccalauréat ès arts en études indiennes américaines" ],
            [ "title" => "Bachelor of Arts in Applied Psychology", "title_fr" => "Baccalauréat ès arts en psychologie appliquée" ],
            [ "title" => "Bachelor of Arts in Biology", "title_fr" => "Baccalauréat en biologie" ],
            [ "title" => "Bachelor of Arts in Anthropology", "title_fr" => "Baccalauréat en anthropologie" ],
            [ "title" => "Bachelor of Arts in Child Advocacy", "title_fr" => "Baccalauréat ès arts en défense des droits des enfants" ],
            [ "title" => "Bachelor of Arts in Clinical Psychology", "title_fr" => "Baccalauréat ès arts en psychologie clinique" ],
            [ "title" => "Bachelor of Arts in Forensic Psychology", "title_fr" => "Baccalauréat ès arts en psychologie légale" ],
            [ "title" => "Bachelor of Arts in Organizational Psychology", "title_fr" => "Baccalauréat ès arts en psychologie organisationnelle" ],
            [ "title" => "Bachelor of Science in Aerospace Engineering", "title_fr" => "Baccalauréat ès sciences en génie aérospatial" ],
            [ "title" => "Bachelor of Science in Actuarial", "title_fr" => "Baccalauréat en sciences actuarielles" ],
            [ "title" => "Bachelor of Science in Agriculture", "title_fr" => "Baccalauréat en sciences de l'agriculture" ],
            [ "title" => "Bachelor of Science in Architecture", "title_fr" => "Baccalauréat en sciences de l'architecture" ],
            [ "title" => "Bachelor of Science in Architectural Engineering", "title_fr" => "Baccalauréat ès sciences en ingénierie architecturale" ],
            [ "title" => "Bachelor of Science in Athletic Training", "title_fr" => "Baccalauréat en sciences en entraînement sportif" ],
            [ "title" => "Bachelor of Science in Biology", "title_fr" => "Baccalauréat en sciences en biologie" ],
            [ "title" => "Bachelor of Science in Biomedical Engineering", "title_fr" => "Baccalauréat en sciences en génie biomédical" ],
            [ "title" => "Bachelor of Science in Bible", "title_fr" => "Baccalauréat en sciences dans la Bible" ],
            [ "title" => "Bachelor of Science in Business Administration", "title_fr" => "Baccalauréat ès sciences en administration des affaires" ],
            [ "title" => "Bachelor of Science in Business and Technology", "title_fr" => "Baccalauréat ès sciences en affaires et en technologie" ],
            [ "title" => "Bachelor of Science in Chemical Engineering", "title_fr" => "Baccalauréat en sciences en génie chimique" ],
            [ "title" => "Bachelor of Science in Chemistry", "title_fr" => "Baccalauréat en sciences de la chimie" ],
            [ "title" => "Bachelor of Science in Civil Engineering", "title_fr" => "Baccalauréat en sciences en génie civil" ],
            [ "title" => "Bachelor of Science in Clinical Laboratory Science", "title_fr" => "Baccalauréat ès sciences en science clinique de laboratoire" ],
            [ "title" => "Bachelor of Science in Cognitive Science", "title_fr" => "Baccalauréat en sciences cognitives" ],
            [ "title" => "Bachelor of Science in Computer Engineering", "title_fr" => "Baccalauréat en sciences en génie informatique" ],
            [ "title" => "Bachelor of Science in Computer Science", "title_fr" => "Baccalauréat en sciences informatiques" ],
            [ "title" => "Bachelor of Science in Construction Engineering", "title_fr" => "Baccalauréat en sciences de la construction" ],
            [ "title" => "Bachelor of Science in Construction Management", "title_fr" => "Baccalauréat ès sciences en gestion de la construction" ],
            [ "title" => "Bachelor of Science in Criminal Justice", "title_fr" => "Baccalauréat en sciences en justice pénale" ],
            [ "title" => "Bachelor of Science in Criminology", "title_fr" => "Baccalauréat ès sciences en criminologie" ],
            [ "title" => "Bachelor of Science in Diagnostic Radiography", "title_fr" => "Baccalauréat ès sciences en radiographie diagnostique" ],
            [ "title" => "Bachelor of Science in Education", "title_fr" => "Baccalauréat en sciences de l'éducation" ],
            [ "title" => "Bachelor of Science in Electrical Engineering", "title_fr" => "Baccalauréat en sciences en génie électrique" ],
            [ "title" => "Bachelor of Science in Engineering Physics", "title_fr" => "Baccalauréat ès sciences en génie physique" ],
            [ "title" => "Bachelor of Science in Engineering Science", "title_fr" => "Baccalauréat en sciences de l'ingénieur" ],
            [ "title" => "Bachelor of Science in Engineering Technology", "title_fr" => "Baccalauréat en sciences de la technologie" ],
            [ "title" => "Bachelor of Science in English Literature", "title_fr" => "Baccalauréat en sciences de la littérature anglaise" ],
            [ "title" => "Bachelor of Science in Environmental Engineering", "title_fr" => "Baccalauréat en sciences de l'environnement" ],
            [ "title" => "Bachelor of Science in Environmental Science", "title_fr" => "Baccalauréat en sciences de l'environnement" ],
            [ "title" => "Bachelor of Science in Environmental Studies", "title_fr" => "Baccalauréat en sciences de l'environnement" ],
            [ "title" => "Bachelor of Science in Food Science", "title_fr" => "Baccalauréat en sciences de l'alimentation" ],
            [ "title" => "Bachelor of Science in Foreign Service", "title_fr" => "Baccalauréat ès sciences en service extérieur" ],
            [ "title" => "Bachelor of Science in Forensic Science", "title_fr" => "Baccalauréat en science médico-légale" ],
            [ "title" => "Bachelor of Science in Forestry", "title_fr" => "Baccalauréat en sciences forestières" ],
            [ "title" => "Bachelor of Science in History", "title_fr" => "Baccalauréat en sciences de l'histoire" ],
            [ "title" => "Bachelor of Science in Hospitality Management", "title_fr" => "Baccalauréat ès sciences en gestion hôtelière" ],
            [ "title" => "Bachelor of Science in Human Resources Management", "title_fr" => "Baccalauréat ès sciences en gestion des ressources humaines" ],
            [ "title" => "Bachelor of Science in Industrial Engineering", "title_fr" => "Baccalauréat en sciences en génie industriel" ],
            [ "title" => "Bachelor of Science in Information Technology", "title_fr" => "Baccalauréat en sciences de la technologie de l'information" ],
            [ "title" => "Bachelor of Science in Information Systems", "title_fr" => "Baccalauréat ès sciences en systèmes d'information" ],
            [ "title" => "Bachelor of Science in Integrated Science", "title_fr" => "Baccalauréat ès sciences en sciences intégrées" ],
            [ "title" => "Bachelor of Science in International Relations", "title_fr" => "Baccalauréat en sciences en relations internationales" ],
            [ "title" => "Bachelor of Science in Journalism", "title_fr" => "Baccalauréat en journalisme" ],
            [ "title" => "Bachelor of Science in Legal Management", "title_fr" => "Baccalauréat ès sciences en gestion juridique" ],
            [ "title" => "Bachelor of Science in Management", "title_fr" => "Baccalauréat en sciences de la gestion" ],
            [ "title" => "Bachelor of Science in Manufacturing Engineering", "title_fr" => "Baccalauréat ès sciences en génie de la fabrication" ],
            [ "title" => "Bachelor of Science in Marketing", "title_fr" => "Baccalauréat en sciences en marketing" ],
            [ "title" => "Bachelor of Science in Mathematics", "title_fr" => "Baccalauréat en sciences en mathématiques" ],
            [ "title" => "Bachelor of Science in Mechanical Engineering", "title_fr" => "Baccalauréat en sciences en génie mécanique" ],
            [ "title" => "Bachelor of Science in Medical Technology", "title_fr" => "Baccalauréat en sciences de la technologie médicale" ],
            [ "title" => "Bachelor of Science in Metallurgical Engineering", "title_fr" => "Baccalauréat ès sciences en génie métallurgique" ],
            [ "title" => "Bachelor of Science in Meteorology", "title_fr" => "Baccalauréat en sciences de la météorologie" ],
            [ "title" => "Bachelor of Science in Microbiology", "title_fr" => "Baccalauréat en sciences en microbiologie" ],
            [ "title" => "Bachelor of Science in Mining Engineering", "title_fr" => "Baccalauréat ès sciences en génie minier" ],
            [ "title" => "Bachelor of Science in Molecular Biology", "title_fr" => "Baccalauréat ès sciences en biologie moléculaire" ],
            [ "title" => "Bachelor of Science in Neuroscience", "title_fr" => "Baccalauréat en sciences en neuroscience" ],
            [ "title" => "Bachelor of Science in Nursing", "title_fr" => "Baccalauréat en sciences infirmières" ],
            [ "title" => "Bachelor of Science in Nutrition science", "title_fr" => "Baccalauréat en sciences de la nutrition" ],
            [ "title" => "Bachelor of Science in Software Engineering", "title_fr" => "Baccalauréat en sciences en génie logiciel" ],
            [ "title" => "Bachelor of Science in Petroleum Engineering", "title_fr" => "Baccalauréat ès sciences en génie pétrolier" ],
            [ "title" => "Bachelor of Science in Podiatry", "title_fr" => "Baccalauréat ès sciences en podiatrie" ],
            [ "title" => "Bachelor of Science in Pharmacology", "title_fr" => "Baccalauréat ès sciences en pharmacologie" ],
            [ "title" => "Bachelor of Science in Pharmacy", "title_fr" => "Baccalauréat en sciences en pharmacie" ],
            [ "title" => "Bachelor of Science in Physical Therapy", "title_fr" => "Baccalauréat en sciences en physiothérapie" ],
            [ "title" => "Bachelor of Science in Physics", "title_fr" => "Baccalauréat en sciences physiques" ],
            [ "title" => "Bachelor of Science in Plant Science", "title_fr" => "Baccalauréat en sciences végétales" ],
            [ "title" => "Bachelor of Science in Politics", "title_fr" => "Baccalauréat en sciences politiques" ],
            [ "title" => "Bachelor of Science in Psychology", "title_fr" => "Baccalauréat en sciences psychologiques" ],
            [ "title" => "Bachelor of Science in Public Safety", "title_fr" => "Baccalauréat ès sciences en sécurité publique" ],
            [ "title" => "Bachelor of Science in Quantity Surveying Engineering", "title_fr" => "Baccalauréat ès sciences en ingénierie de la métrologie quantitative" ],
            [ "title" => "Bachelor of Science in Radiologic Technology", "title_fr" => "Baccalauréat ès sciences en technologie radiologique" ],
            [ "title" => "Bachelor of Science in Real-Time Interactive Simulation", "title_fr" => "Baccalauréat ès sciences en simulation interactive en temps réel" ],
            [ "title" => "Bachelor of Science in Religion", "title_fr" => "Baccalauréat en sciences en religion" ],
            [ "title" => "Bachelor of Science in Respiratory Therapy", "title_fr" => "Baccalauréat en sciences en thérapie respiratoire" ],
            [ "title" => "Bachelor of Science in Risk Management and Insurance", "title_fr" => "Baccalauréat ès sciences en gestion des risques et assurance" ],
            [ "title" => "Bachelor of Science in Science Education", "title_fr" => "Baccalauréat ès sciences en éducation scientifique" ],
            [ "title" => "Bachelor of Science in Sports Management", "title_fr" => "Baccalauréat ès sciences en gestion du sport" ],
            [ "title" => "Bachelor of Science in Systems Engineering", "title_fr" => "Baccalauréat ès sciences en génie des systèmes" ],
            [ "title" => "Bachelor of Music in Jazz Studies", "title_fr" => "Baccalauréat en musique en études de jazz" ],
            [ "title" => "Bachelor of Music in Composition", "title_fr" => "Baccalauréat en musique en composition" ],
            [ "title" => "Bachelor of Music in Performance", "title_fr" => "Baccalauréat en musique en performance" ],
            [ "title" => "Bachelor of Music in Theory", "title_fr" => "Baccalauréat en musique en théorie" ],
            [ "title" => "Bachelor of Music in Music Education", "title_fr" => "Baccalauréat en musique en éducation musicale" ],
            [ "title" => "Bachelor of Science in Veterinary Technology", "title_fr" => "Baccalauréat en sciences vétérinaires" ],
            [ "title" => "Master of Accountancy", "title_fr" => "Maître de la comptabilité" ],
            [ "title" => "Master of Accounting and Information Systems", "title_fr" => "Maître des systèmes de comptabilité et d'information" ],
            [ "title" => "Master of Advanced Study", "title_fr" => "Maître de l'étude avancée" ],
            [ "title" => "Master of Applied Finance", "title_fr" => "Master de Finance Appliquée" ],
            [ "title" => "Master of Applied Mathematical Sciences", "title_fr" => "Maître des Sciences Mathématiques Appliquées" ],
            [ "title" => "Master of Applied Psychology", "title_fr" => "Maître de Psychologie Appliquée" ],
            [ "title" => "Master of Applied Science", "title_fr" => "Master de Science Appliquée" ],
            [ "title" => "Master of Architecture", "title_fr" => "Maître de l'architecture" ],
            [ "title" => "Master of Arts", "title_fr" => "Maître des arts" ],
            [ "title" => "Master of Arts in Archives and Records Management", "title_fr" => "Maîtrise en archivistique et gestion des documents" ],
            [ "title" => "Master of Arts in Liberal Studies", "title_fr" => "Master of Arts en études libérales" ],
            [ "title" => "Master of Arts in Museum Studies", "title_fr" => "Maîtrise en études muséales" ],
            [ "title" => "Master of Arts in Strategic Communication Management", "title_fr" => "Maîtrise en gestion de la communication stratégique" ],
            [ "title" => "Master of Arts in Teaching", "title_fr" => "Master of Arts en enseignement" ],
            [ "title" => "Master of Athletic Training", "title_fr" => "Maître de la formation athlétique" ],
            [ "title" => "Master of Bioinformatics", "title_fr" => "Master de Bioinformatique" ],
            [ "title" => "Master of Biotechnology", "title_fr" => "Master de Biotechnologie" ],
            [ "title" => "Master of Business Administration", "title_fr" => "Master en administration des affaires" ],
            [ "title" => "Master of Business Administration Management of Technology", "title_fr" => "Master of Business Administration Management de la Technologie" ],
            [ "title" => "Master of Business", "title_fr" => "Maître des affaires" ],
            [ "title" => "Master of Business Economics", "title_fr" => "Master en économie d'entreprise" ],
            [ "title" => "Master of Business Engineering", "title_fr" => "Master en Ingénierie Commerciale" ],
            [ "title" => "Master of Business Informatics", "title_fr" => "Master en informatique d'entreprise" ],
            [ "title" => "Master of Chemistry", "title_fr" => "Master de Chimie" ],
            [ "title" => "Master of City Planning", "title_fr" => "Maître de la planification urbaine" ],
            [ "title" => "Master of Commerce", "title_fr" => "Maître de commerce" ],
            [ "title" => "Master of Computational Finance", "title_fr" => "Master en Finance Computationnelle" ],
            [ "title" => "Master of Computer Applications", "title_fr" => "Maître des applications informatiques" ],
            [ "title" => "Master of Computer Science", "title_fr" => "Master en Informatique" ],
            [ "title" => "Master of Communication", "title_fr" => "Maître de Communication" ],
            [ "title" => "Master of Counseling", "title_fr" => "Maître de Counseling" ],
            [ "title" => "Master of Criminal Justice", "title_fr" => "Maître de la justice pénale" ],
            [ "title" => "Master in Creative Technologies", "title_fr" => "Master en technologies créatives" ],
            [ "title" => "Master of Design", "title_fr" => "Maître du Design" ],
            [ "title" => "Master of Divinity", "title_fr" => "Maître de la Divinité" ],
            [ "title" => "Master of Economics", "title_fr" => "Master d'Economie" ],
            [ "title" => "Master of Education", "title_fr" => "Master d'éducation" ],
            [ "title" => "Master of Educational Technology", "title_fr" => "Maître de la technologie éducative" ],
            [ "title" => "Master of Engineering", "title_fr" => "Maître de l'ingénierie" ],
            [ "title" => "Master of Engineering Management", "title_fr" => "Master de gestion d'ingénierie" ],
            [ "title" => "Master of Enterprise", "title_fr" => "Maître de l'entreprise" ],
            [ "title" => "Master of European Law", "title_fr" => "Master de Droit Européen" ],
            [ "title" => "Master of Finance", "title_fr" => "Maître des finances" ],
            [ "title" => "Master of Financial Economics", "title_fr" => "Master en économie financière" ],
            [ "title" => "Master of Financial Engineering", "title_fr" => "Master en Ingénierie Financière" ],
            [ "title" => "Master of Financial Mathematics", "title_fr" => "Master de mathématiques financières" ],
            [ "title" => "Master of Fine Arts", "title_fr" => "Maître des Beaux-Arts" ],
            [ "title" => "Master of Health Administration", "title_fr" => "Maître de l'administration de la santé" ],
            [ "title" => "Master of Health Science", "title_fr" => "Master en sciences de la santé" ],
            [ "title" => "Master of Humanities", "title_fr" => "Master en sciences humaines" ],
            [ "title" => "Master of Industrial and Labor Relations", "title_fr" => "Maître des Relations Industrielles et de Travail" ],
            [ "title" => "Master of International Affairs", "title_fr" => "Maître des affaires internationales" ],
            [ "title" => "Master of International Business", "title_fr" => "Maître des affaires internationales" ],
            [ "title" => "Master of International Economics", "title_fr" => "Master d'économie internationale" ],
            [ "title" => "Master of International Public Policy", "title_fr" => "Master de politique publique internationale" ],
            [ "title" => "Master of International Studies", "title_fr" => "Master d'études internationales" ],
            [ "title" => "Master of Information", "title_fr" => "Maître de l'information" ],
            [ "title" => "Master of Information Management", "title_fr" => "Master de gestion de l'information" ],
            [ "title" => "Master of Information Systems", "title_fr" => "Maître des systèmes d'information" ],
            [ "title" => "Master of Information System Management", "title_fr" => "Master en gestion de système d'information" ],
            [ "title" => "Master of Islamic Studies", "title_fr" => "Maître des études islamiques" ],
            [ "title" => "Master of IT", "title_fr" => "Maître de l'informatique" ],
            [ "title" => "Master of Jurisprudence", "title_fr" => "Maître de jurisprudence" ],
            [ "title" => "Master of Laws", "title_fr" => "Maître des lois" ],
            [ "title" => "Master of Studies in Law", "title_fr" => "Maîtrise d'études en droit" ],
            [ "title" => "Master of Landscape Architecture", "title_fr" => "Maître de l'architecture de paysage" ],
            [ "title" => "Master of Letters", "title_fr" => "Maître des Lettres" ],
            [ "title" => "Master of Liberal Arts", "title_fr" => "Maître des Arts Libéraux" ],
            [ "title" => "Master of Library and Information Science", "title_fr" => "Master en bibliothéconomie et sciences de l'information" ],
            [ "title" => "Master of Management", "title_fr" => "Master de Management" ],
            [ "title" => "Master of Mass Communication and Journalism", "title_fr" => "Maître de la communication de masse et du journalisme" ],
            [ "title" => "Master of Mathematical Finance", "title_fr" => "Master de Finance Mathématique" ],
            [ "title" => "Master of Mathematics", "title_fr" => "Maître des mathématiques" ],
            [ "title" => "Master of Mathematics and Computer Science", "title_fr" => "Master en Mathématiques et Informatique" ],
            [ "title" => "Master of Mathematics and Philosophy", "title_fr" => "Master de Mathématiques et de Philosophie" ],
            [ "title" => "Master of Medical Science", "title_fr" => "Maître de Science Médicale" ],
            [ "title" => "Master of Medicine", "title_fr" => "Maître de Médecine" ],
            [ "title" => "Master of Military Art and Science", "title_fr" => "Maître de l'art militaire et de la science" ],
            [ "title" => "Master of Music", "title_fr" => "Maître de la musique" ],
            [ "title" => "Master of Network and Communications Management", "title_fr" => "Master de gestion de réseau et de communication" ],
            [ "title" => "Master of Occupational Therapy", "title_fr" => "Maître de l'ergothérapie" ],
            [ "title" => "Master of Pharmacy", "title_fr" => "Maître de pharmacie" ],
            [ "title" => "Master of Philosophy", "title_fr" => "Maître de Philosophie" ],
            [ "title" => "Master of Physician Assistant Studies", "title_fr" => "Maître des études d'adjoint au médecin" ],
            [ "title" => "Master of Physics", "title_fr" => "Maître de Physique" ],
            [ "title" => "Master of Political Science", "title_fr" => "Maître de Science Politique" ],
            [ "title" => "Master of Professional Studies", "title_fr" => "Master d'études professionnelles" ],
            [ "title" => "Master of Psychology", "title_fr" => "Maître de Psychologie" ],
            [ "title" => "Master of Public Administration", "title_fr" => "Maître de l'administration publique" ],
            [ "title" => "Master of Public Affairs", "title_fr" => "Maître des Affaires Publiques" ],
            [ "title" => "Master of Public Diplomacy", "title_fr" => "Maître de la Diplomatie Publique" ],
            [ "title" => "Master of Public Health", "title_fr" => "Master de Santé Publique" ],
            [ "title" => "Master of Public Management", "title_fr" => "Master de gestion publique" ],
            [ "title" => "Master of Public Policy", "title_fr" => "Maître de politique publique" ],
            [ "title" => "Master of Public Relations", "title_fr" => "Maître des relations publiques" ],
            [ "title" => "Master of Public Service", "title_fr" => "Maître de Service Public" ],
            [ "title" => "Master of Quantitative Finance", "title_fr" => "Master de Finance Quantitative" ],
            [ "title" => "Master of Rabbinic Studies", "title_fr" => "Maître des études rabbiniques" ],
            [ "title" => "Master of Real Estate Development", "title_fr" => "Master en développement immobilier" ],
            [ "title" => "Master of Religious Education", "title_fr" => "Maître de l'éducation religieuse" ],
            [ "title" => "Master of Research", "title_fr" => "Maître de recherche" ],
            [ "title" => "Master of Sacred Music", "title_fr" => "Maître de la musique sacrée" ],
            [ "title" => "Master of Sacred Theology", "title_fr" => "Maître de théologie sacrée" ],
            [ "title" => "Master of Science", "title_fr" => "Master of Science" ],
            [ "title" => "Master of Science in Applied Cognition and Neuroscience", "title_fr" => "Master of Science en Cognition Appliquée et Neuroscience" ],
            [ "title" => "Master of Science in Athletic Training", "title_fr" => "Master of Science en Entraînement Athlétique" ],
            [ "title" => "Master of Science in Bioinformatics", "title_fr" => "Master of Science en Bioinformatique" ],
            [ "title" => "Master of Science in Clinical Epidemiology", "title_fr" => "Master of Science en épidémiologie clinique" ],
            [ "title" => "Master of Science in Computing Research", "title_fr" => "Maîtrise en sciences de la recherche en informatique" ],
            [ "title" => "Master of Science in Cyber Security", "title_fr" => "Master of Science en cybersécurité" ],
            [ "title" => "Master of Science in Education", "title_fr" => "Master of Science en éducation" ],
            [ "title" => "Master of Science in Engineering", "title_fr" => "Master of Science en Ingénierie" ],
            [ "title" => "Master of Science in Development Administration", "title_fr" => "Master of Science en Administration du Développement" ],
            [ "title" => "Master of Science in Finance", "title_fr" => "Master of Science en Finance" ],
            [ "title" => "Master of Science in Governance & Organizational Sciences", "title_fr" => "Master of Science en Gouvernance et Sciences de l'Organisation" ],
            [ "title" => "Master of Science in Government Contracts", "title_fr" => "Master of Science en contrats gouvernementaux" ],
            [ "title" => "Master of Science in Health Informatics", "title_fr" => "Master of Science en informatique de la santé" ],
            [ "title" => "Master of Science in Human Resource Development", "title_fr" => "Maîtrise en sciences en développement des ressources humaines" ],
            [ "title" => "Master of Science in Information Assurance", "title_fr" => "Master of Science en assurance de l'information" ],
            [ "title" => "Master of Science in Information Systems", "title_fr" => "Master of Science en Systèmes d'Information" ],
            [ "title" => "Master of Science in Information Technology", "title_fr" => "Master of Science en technologie de l'information" ],
            [ "title" => "Master of Science in Leadership", "title_fr" => "Master of Science en Leadership" ],
            [ "title" => "Master of Science in Management", "title_fr" => "Master of Science en Management" ],
            [ "title" => "Master of Science in Nursing", "title_fr" => "Master of Science en sciences infirmières" ],
            [ "title" => "Master of Science in Project Management", "title_fr" => "Master of Science en gestion de projet" ],
            [ "title" => "Master of Science in Quality Assurance", "title_fr" => "Master of Science en assurance qualité" ],
            [ "title" => "Master of Science in Risk Management", "title_fr" => "Master of Science en gestion des risques" ],
            [ "title" => "Master of Science in Supply Chain Management", "title_fr" => "Master of Science en gestion de la chaîne d'approvisionnement" ],
            [ "title" => "Master of Science in Teaching", "title_fr" => "Master of Science en Enseignement" ],
            [ "title" => "Master of Science in Taxation", "title_fr" => "Master of Science en fiscalité" ],
            [ "title" => "Master of Social Science", "title_fr" => "Master en sciences sociales" ],
            [ "title" => "Master of Social Work", "title_fr" => "Maître du travail social" ],
            [ "title" => "Master of Statistics", "title_fr" => "Maître des statistiques" ],
            [ "title" => "Master of Strategic Studies", "title_fr" => "Master d'études stratégiques" ],
            [ "title" => "Master of Studies", "title_fr" => "Maître des études" ],
            [ "title" => "Master of Surgery", "title_fr" => "Maître de chirurgie" ],
            [ "title" => "Master of Theological Studies", "title_fr" => "Maître des études théologiques" ],
            [ "title" => "Master of Technology", "title_fr" => "Maître de la technologie" ],
            [ "title" => "Master of Theology", "title_fr" => "Maître de Théologie" ],
            [ "title" => "Master of Urban Planning", "title_fr" => "Maître de l'urbanisme" ],
            [ "title" => "Master of Veterinary Science", "title_fr" => "Maître des sciences vétérinaires" ],
            [ "title" => "Doctor of Aviation", "title_fr" => "Docteur en aviation" ],
            [ "title" => "Doctor of Business Administration", "title_fr" => "Docteur en administration des affaires" ],
            [ "title" => "Doctor of Canon Law", "title_fr" => "Docteur en droit canonique" ],
            [ "title" => "Doctor of Chiropractic", "title_fr" => "Docteur en chiropratique" ],
            [ "title" => "Doctor of Commerce", "title_fr" => "Docteur en commerce" ],
            [ "title" => "Doctor of Dental Surgery", "title_fr" => "Docteur en chirurgie dentaire" ],
            [ "title" => "Doctor of Divinity", "title_fr" => "Docteur en Divinité" ],
            [ "title" => "Doctor of Education", "title_fr" => "Docteur en éducation" ],
            [ "title" => "Doctor of Engineering", "title_fr" => "Docteur en génie" ],
            [ "title" => "Doctor of Health Administration", "title_fr" => "Docteur en administration de la santé" ],
            [ "title" => "Doctor of Health Science", "title_fr" => "Docteur en science de la santé" ],
            [ "title" => "Doctor of Juridical Science; Juris Doctor", "title_fr" => "Docteur en sciences juridiques; Juris Docteur" ],
            [ "title" => "Doctor of Law; Legum Doctor", "title_fr" => "Docteur en droit Docteur Legum" ],
            [ "title" => "Doctor of Liberal Studies", "title_fr" => "Docteur en études libérales" ],
            [ "title" => "Doctor of Management", "title_fr" => "Docteur en gestion" ],
            [ "title" => "Doctor of Medicine", "title_fr" => "Docteur en médecine" ],
            [ "title" => "Doctor of Ministry", "title_fr" => "Docteur du Ministère" ],
            [ "title" => "Doctor of Modern Languages", "title_fr" => "Docteur en langues modernes" ],
            [ "title" => "Doctor of Musical Arts", "title_fr" => "Docteur en arts musicaux" ],
            [ "title" => "Doctor of Naturopathic Medicine", "title_fr" => "Docteur en médecine naturopathique" ],
            [ "title" => "Doctor of Optometry", "title_fr" => "Docteur en optométrie" ],
            [ "title" => "Doctor of Osteopathic Medicine", "title_fr" => "Docteur en médecine ostéopathique" ],
            [ "title" => "Doctor of Pharmacy", "title_fr" => "Docteur en pharmacie" ],
            [ "title" => "Doctor of Philosophy", "title_fr" => "Docteur en philosophie" ],
            [ "title" => "Doctor of Public Administration", "title_fr" => "Docteur en administration publique" ],
            [ "title" => "Doctor of Science", "title_fr" => "Docteur en Science" ],
            [ "title" => "Doctor of Theology", "title_fr" => "Docteur en théologie" ],
            [ "title" => "Doctor of Veterinary Medicine", "title_fr" => "Docteur en médecine vétérinaire" ],
            [ "title" => "Doctor of Radio oncology", "title_fr" => "Docteur en radio-oncologie" ],
            [ "title" => "New Zealand Diploma in Embalming", "title_fr" => "Diplôme de Nouvelle-Zélande en embaumement" ],
            [ "title" => "New Zealand Diploma in Funeral Directing", "title_fr" => "Diplôme de Nouvelle-Zélande en réalisation de funérailles" ],
            [ "title" => "Masters in Biology", "title_fr" => "Maîtrise en biologie" ],
            [ "title" => "Accounting", "title_fr" => "Comptabilité" ],
            [ "title" => "Aerospace Studies", "title_fr" => "Etudes aérospatiales" ],
            [ "title" => "Agribusiness", "title_fr" => "Secteur agroalimentaire" ],
            [ "title" => "Agricultural Communication and Journalism", "title_fr" => "Communication agricole et journalisme" ],
            [ "title" => "Agricultural Education", "title_fr" => "Éducation agricole" ],
            [ "title" => "Agricultural Machinery Technology", "title_fr" => "Technologie des machines agricoles" ],
            [ "title" => "Agricultural Science", "title_fr" => "Science agricole" ],
            [ "title" => "Agricultural Systems Technology", "title_fr" => "Technologie des systèmes agricoles" ],
            [ "title" => "Agricultural Systems Technology and Agribusiness", "title_fr" => "Technologie des systèmes agricoles et agro-industrie" ],
            [ "title" => "Aircraft Maintenance Technician - Airframe and Powerplant", "title_fr" => "Technicien d'entretien d'aéronefs - Cellule et groupe motopropulseur" ],
            [ "title" => "American Studies", "title_fr" => "Études américaines" ],
            [ "title" => "Animal, Dairy, and Veterinary Sciences", "title_fr" => "Sciences animales, laitières et vétérinaires" ],
            [ "title" => "Anthropology", "title_fr" => "Anthropologie" ],
            [ "title" => "Applied Economics", "title_fr" => "Économie appliquée" ],
            [ "title" => "Art", "title_fr" => "Art" ],
            [ "title" => "Art History", "title_fr" => "Histoire de l'art" ],
            [ "title" => "Asian Studies", "title_fr" => "des études asiatiques" ],
            [ "title" => "Automotive Technology", "title_fr" => "Technologie automobile" ],
            [ "title" => "Aviation Technology - Maintenance Management", "title_fr" => "Technologie aéronautique - Gestion de la maintenance" ],
            [ "title" => "Aviation Technology - Professional Pilot", "title_fr" => "Technologie de l'aviation - Pilote professionnel" ],
            [ "title" => "Biochemistry", "title_fr" => "Biochimie" ],
            [ "title" => "Biological Engineering", "title_fr" => "Génie biologique" ],
            [ "title" => "Biological Science", "title_fr" => "Biologie" ],
            [ "title" => "Biology", "title_fr" => "La biologie" ],
            [ "title" => "Building Construction and Construction Management", "title_fr" => "Construction de bâtiments et gestion de la construction" ],
            [ "title" => "Business", "title_fr" => "Entreprise" ],
            [ "title" => "Business Administration", "title_fr" => "Administration des affaires" ],
            [ "title" => "Business Education", "title_fr" => "Éducation d'affaires" ],
            [ "title" => "Certified Nursing Assistant", "title_fr" => "Assistante infirmière certifiée" ],
            [ "title" => "Chemistry", "title_fr" => "Chimie" ],
            [ "title" => "Chemistry Endorsement", "title_fr" => "Approbation de la chimie" ],
            [ "title" => "Chemistry Teaching", "title_fr" => "Enseignement de la chimie" ],
            [ "title" => "Civil Engineering", "title_fr" => "Génie civil" ],
            [ "title" => "Climate Science", "title_fr" => "Science du climat" ],
            [ "title" => "Communication Studies", "title_fr" => "Études de communication" ],
            [ "title" => "Communicative Disorders and Deaf Education", "title_fr" => "Troubles communicatifs et éducation des sourds" ],
            [ "title" => "Communicative Disorders and Deaf Education", "title_fr" => "Troubles communicatifs et éducation des sourds" ],
            [ "title" => "Computer Engineering", "title_fr" => "Ingénierie informatique" ],
            [ "title" => "Computer Science", "title_fr" => "L'informatique" ],
            [ "title" => "Conservation and Restoration Ecology", "title_fr" => "Écologie de la conservation et de la restauration" ],
            [ "title" => "Cosmetology", "title_fr" => "Cosmétologie" ],
            [ "title" => "Criminal Justice", "title_fr" => "Justice criminelle" ],
            [ "title" => "Deafblind Intervener Training", "title_fr" => "Formation d'intervenant sourd-aveugle" ],
            [ "title" => "Diesel and Heavy Equipment Mechanics", "title_fr" => "Mécaniciens de moteurs diesel et d'équipement lourd" ],
            [ "title" => "Digital Design", "title_fr" => "Conception numérique" ],
            [ "title" => "Early Childhood Education", "title_fr" => "L'éducation de la petite enfance" ],
            [ "title" => "Early Childhood Education and Deaf Education", "title_fr" => "Éducation de la petite enfance et éducation des Sourds" ],
            [ "title" => "Early Childhood Education and Special Education", "title_fr" => "Éducation de la petite enfance et éducation spécialisée" ],
            [ "title" => "Earth Science", "title_fr" => "sciences de la Terre" ],
            [ "title" => "Economics", "title_fr" => "Économie" ],
            [ "title" => "Electrical Apprentice", "title_fr" => "Apprenti électrique" ],
            [ "title" => "Electrical Engineering", "title_fr" => "Ingénierie électrique" ],
            [ "title" => "Electronics", "title_fr" => "Électronique" ],
            [ "title" => "Elementary Education", "title_fr" => "Enseignement primaire" ],
            [ "title" => "Elementary Education", "title_fr" => "Enseignement primaire" ],
            [ "title" => "Elementary Education and Deaf Education", "title_fr" => "Éducation élémentaire et éducation des Sourds" ],
            [ "title" => "Elementary Education and Special Education", "title_fr" => "Éducation élémentaire et éducation spécialisée" ],
            [ "title" => "Engineering Drafting and Design Technology", "title_fr" => "Ingénierie de dessin et technologie de conception" ],
            [ "title" => "English", "title_fr" => "Anglais" ],
            [ "title" => "Environmental and Natural Resource Economics", "title_fr" => "Économie de l'environnement et des ressources naturelles" ],
            [ "title" => "Environmental Engineering", "title_fr" => "Génie de l'environnement" ],
            [ "title" => "Environmental Studies", "title_fr" => "Études environnementales" ],
            [ "title" => "Family and Consumer Sciences Education", "title_fr" => "Éducation aux sciences de la famille et de la consommation" ],
            [ "title" => "Family Life Studies", "title_fr" => "Études de la vie familiale" ],
            [ "title" => "Family, Consumer, and Human Development", "title_fr" => "Famille, consommateur et développement humain" ],
            [ "title" => "Finance", "title_fr" => "La finance" ],
            [ "title" => "Fisheries and Aquatic Sciences", "title_fr" => "Pêches et sciences aquatiques" ],
            [ "title" => "Forest Ecology and Management", "title_fr" => "Écologie forestière et gestion" ],
            [ "title" => "French", "title_fr" => "français" ],
            [ "title" => "General Studies", "title_fr" => "Études générales" ],
            [ "title" => "General Studies: Agriculture", "title_fr" => "Études générales: Agriculture" ],
            [ "title" => "General Studies: Arts and Humanities", "title_fr" => "Études générales: Arts et sciences humaines" ],
            [ "title" => "General Studies: Arts and Humanities", "title_fr" => "Études générales: Arts et sciences humaines" ],
            [ "title" => "General Studies: Human Services", "title_fr" => "Études générales: Services à la personne" ],
            [ "title" => "General Studies: Natural Resources", "title_fr" => "Études générales: Ressources naturelles" ],
            [ "title" => "General Studies: Policy and Administration", "title_fr" => "Études générales: politique et administration" ],
            [ "title" => "General Studies: Science", "title_fr" => "Études générales: Science" ],
            [ "title" => "General Studies: Social Sciences", "title_fr" => "Études générales: sciences sociales" ],
            [ "title" => "General Studies: Technology", "title_fr" => "Études générales: Technologie" ],
            [ "title" => "General Technology", "title_fr" => "Technologie générale" ],
            [ "title" => "Geography", "title_fr" => "Géographie" ],
            [ "title" => "Geology", "title_fr" => "Géologie" ],
            [ "title" => "German", "title_fr" => "allemand" ],
            [ "title" => "Gerontology", "title_fr" => "Gérontologie" ],
            [ "title" => "Global Communication", "title_fr" => "Communication globale" ],
            [ "title" => "Health Education and Promotion", "title_fr" => "Éducation et promotion de la santé" ],
            [ "title" => "Heavy Equipment and Trucking", "title_fr" => "Équipement lourd et camionnage" ],
            [ "title" => "History", "title_fr" => "Histoire" ],
            [ "title" => "Horticulture", "title_fr" => "Horticulture" ],
            [ "title" => "Human Movement Science", "title_fr" => "Science du mouvement humain" ],
            [ "title" => "Interdisciplinary Studies", "title_fr" => "études interdisciplinaires" ],
            [ "title" => "Interior Design", "title_fr" => "Design d'intérieur" ],
            [ "title" => "International Agribusiness", "title_fr" => "Agroalimentaire international" ],
            [ "title" => "International Business", "title_fr" => "Commerce international" ],
            [ "title" => "International Studies", "title_fr" => "Études internationales" ],
            [ "title" => "IT Support and Web Development", "title_fr" => "Support informatique et développement Web" ],
            [ "title" => "Journalism", "title_fr" => "Journalisme" ],
            [ "title" => "Land, Plant and Climate Systems", "title_fr" => "Systèmes terrestres, végétaux et climatiques" ],
            [ "title" => "Landscape Architecture", "title_fr" => "Architecture de paysage" ],
            [ "title" => "Landscape Management", "title_fr" => "Gestion du paysage" ],
            [ "title" => "Law and Constitutional Studies", "title_fr" => "Droit et études constitutionnelles" ],
            [ "title" => "Law and Society Area Studies", "title_fr" => "Études du droit et de la société" ],
            [ "title" => "Liberal Arts", "title_fr" => "Arts libéraux" ],
            [ "title" => "Machine Tool Technology", "title_fr" => "Technologie de la machine-outil" ],
            [ "title" => "Management and Restoration of Aquatic Ecosystems", "title_fr" => "Gestion et restauration des écosystèmes aquatiques" ],
            [ "title" => "Management Information Systems", "title_fr" => "Système de gestion d'informations" ],
            [ "title" => "Marketing", "title_fr" => "Commercialisation" ],
            [ "title" => "Mathematics", "title_fr" => "Mathématiques" ],
            [ "title" => "Mathematics Education", "title_fr" => "Éducation mathématique" ],
            [ "title" => "Mathematics- Level II Endorsement", "title_fr" => "Mathématiques - Approbation de niveau II" ],
            [ "title" => "Mathematics- Level III/IV Endorsement", "title_fr" => "Mathématiques - Approbation de niveau III / IV" ],
            [ "title" => "Mathematics/Statistics", "title_fr" => "Mathématiques / Statistiques" ],
            [ "title" => "Mathematics/Statistics Education", "title_fr" => "Mathématiques / Statistiques Education" ],
            [ "title" => "Mechanical Engineering", "title_fr" => "Ingénierie mécanique" ],
            [ "title" => "Medical Assistant", "title_fr" => "Assistant médical" ],
            [ "title" => "Medical Laboratory Technician", "title_fr" => "Technicien de laboratoire médical" ],
            [ "title" => "Military Science", "title_fr" => "Science militaire" ],
            [ "title" => "Museum Studies", "title_fr" => "Etudes muséales" ],
            [ "title" => "Music", "title_fr" => "La musique" ],
            [ "title" => "Music Therapy", "title_fr" => "Musicothérapie" ],
            [ "title" => "Nursing", "title_fr" => "Allaitement" ],
            [ "title" => "Nursing", "title_fr" => "Allaitement" ],
            [ "title" => "Nutrition, Dietetics, and Food Sciences", "title_fr" => "Nutrition, diététique et sciences de l'alimentation" ],
            [ "title" => "Office Computer Systems", "title_fr" => "Systèmes informatiques de bureau" ],
            [ "title" => "Ornamental Horticulture", "title_fr" => "Horticulture ornementale" ],
            [ "title" => "Outdoor Product Design and Development", "title_fr" => "Conception et développement de produits d'extérieur" ],
            [ "title" => "Parks and Recreation", "title_fr" => "Parcs et loisirs" ],
            [ "title" => "Philosophy", "title_fr" => "Philosophie" ],
            [ "title" => "Phlebotomy", "title_fr" => "Phlébotomie" ],
            [ "title" => "Physical Science", "title_fr" => "Science physique" ],
            [ "title" => "Physics", "title_fr" => "La physique" ],
            [ "title" => "Physics Teaching", "title_fr" => "Enseignement de la physique" ],
            [ "title" => "Plant Science", "title_fr" => "Science des plantes" ],
            [ "title" => "Political Science", "title_fr" => "Science politique" ],
            [ "title" => "Practical Nursing", "title_fr" => "Soins infirmiers pratiques" ],
            [ "title" => "Professional Bookkeeper", "title_fr" => "Comptable professionnel" ],
            [ "title" => "Professional Bookkeeping", "title_fr" => "Tenue de livres professionnelle" ],
            [ "title" => "Psychology", "title_fr" => "Psychologie" ],
            [ "title" => "Public Health", "title_fr" => "Santé publique" ],
            [ "title" => "Rangeland Ecology and Management", "title_fr" => "Écologie et gestion des parcours" ],
            [ "title" => "Recreation Resource Management", "title_fr" => "Gestion des ressources récréatives" ],
            [ "title" => "Religious Studies", "title_fr" => "Études religieuses" ],
            [ "title" => "Residential Landscape Design and Construction", "title_fr" => "Conception et aménagement paysager résidentiel" ],
            [ "title" => "Secondary Education", "title_fr" => "Éducation secondaire" ],
            [ "title" => "Secondary Teacher Education Program Licensure", "title_fr" => "Licence du programme de formation des enseignants du secondaire" ],
            [ "title" => "Small Business Operations", "title_fr" => "Opérations de petites entreprises" ],
            [ "title" => "Social Studies", "title_fr" => "Études sociales" ],
            [ "title" => "Social Work", "title_fr" => "Travail social" ],
            [ "title" => "Sociology", "title_fr" => "Sociologie" ],
            [ "title" => "Spanish", "title_fr" => "Espanol" ],
            [ "title" => "Special Education", "title_fr" => "Éducation spéciale" ],
            [ "title" => "Statistics", "title_fr" => "Statistiques" ],
            [ "title" => "Technology and Engineering Education", "title_fr" => "Enseignement de la technologie et de l'ingénierie" ],
            [ "title" => "Technology Systems", "title_fr" => "Systèmes de technologie" ],
            [ "title" => "Theatre Arts", "title_fr" => "Théâtre Arts" ],
            [ "title" => "USU/Hadley Online Program of Study in Blindness", "title_fr" => "USU / Hadley Online Programme d'études sur la cécité" ],
            [ "title" => "Utah Mathematics Endorsement Project", "title_fr" => "Projet d'endossement mathématique de l'Utah" ],
            [ "title" => "Web Business", "title_fr" => "Affaires Web" ],
            [ "title" => "Welding", "title_fr" => "Soudage" ],
            [ "title" => "Welding Technology", "title_fr" => "Technologie de soudage" ],
            [ "title" => "Wildlife Ecology and Management", "title_fr" => "Écologie et gestion de la faune" ],
            [ "title" => "Women and Gender Studies Area Studies", "title_fr" => "Études sur les femmes et les études de genre" ],
            [ "title" => "Accounting", "title_fr" => "Comptabilité" ],
            [ "title" => "Administrative Supervisory Licensure", "title_fr" => "Licence administrative de surveillance" ],
            [ "title" => "Administrative/Supervisory Concentration", "title_fr" => "Concentration administrative / de surveillance" ],
            [ "title" => "Aerospace Engineering", "title_fr" => "Génie aérospatial" ],
            [ "title" => "Agricultural Extension and Education", "title_fr" => "Vulgarisation agricole et éducation" ],
            [ "title" => "Alternative Teacher Preparation Licensure", "title_fr" => "Permis de préparation à l'enseignement alternatif" ],
            [ "title" => "American Studies", "title_fr" => "Études américaines" ],
            [ "title" => "Animal, Dairy, and Veterinary Sciences", "title_fr" => "Sciences animales, laitières et vétérinaires" ],
            [ "title" => "Anthropology", "title_fr" => "Anthropologie" ],
            [ "title" => "Applied Economics", "title_fr" => "Économie appliquée" ],
            [ "title" => "Applied Environmental Geoscience", "title_fr" => "Géoscience environnementale appliquée" ],
            [ "title" => "Archiving and Public Programming", "title_fr" => "Archivage et programmation publique" ],
            [ "title" => "Art", "title_fr" => "Art" ],
            [ "title" => "Audiology", "title_fr" => "Audiologie" ],
            [ "title" => "Aviation Science", "title_fr" => "Science de l'aviation" ],
            [ "title" => "Biochemistry", "title_fr" => "Biochimie" ],
            [ "title" => "Biological Engineering", "title_fr" => "Génie biologique" ],
            [ "title" => "Biology", "title_fr" => "La biologie" ],
            [ "title" => "Business Administration", "title_fr" => "Administration des affaires" ],
            [ "title" => "Career and Technical Education", "title_fr" => "Carrière et éducation technique" ],
            [ "title" => "Chemistry", "title_fr" => "Chimie" ],
            [ "title" => "Civil and Environmental Engineering", "title_fr" => "Génie civil et environnemental" ],
            [ "title" => "Climate Sciences", "title_fr" => "Sciences du climat" ],
            [ "title" => "Communicative Disorders and Deaf Education", "title_fr" => "Troubles communicatifs et éducation des sourds" ],
            [ "title" => "Computer Engineering", "title_fr" => "Ingénierie informatique" ],
            [ "title" => "Computer Science", "title_fr" => "L'informatique" ],
            [ "title" => "Curriculum and Instruction", "title_fr" => "Curriculum et Instruction" ],
            [ "title" => "Deaf Education - Listening and Spoken Language Endorsement", "title_fr" => "Éducation des Sourds - Écoute et approbation de la langue parlée" ],
            [ "title" => "Dietetic Internship", "title_fr" => "Stage diététique" ],
            [ "title" => "Dietetics Administration", "title_fr" => "Administration diététique" ],
            [ "title" => "Disability Disciplines", "title_fr" => "Disciplines d'invalidité" ],
            [ "title" => "Dual Language Immersion Endorsement", "title_fr" => "Approbation d'immersion bilingue" ],
            [ "title" => "Early Childhood Endorsement", "title_fr" => "Approbation de la petite enfance" ],
            [ "title" => "Ecology", "title_fr" => "Écologie" ],
            [ "title" => "Economics", "title_fr" => "Économie" ],
            [ "title" => "Economics", "title_fr" => "Économie" ],
            [ "title" => "Economics and Statistics", "title_fr" => "Économie et statistiques" ],
            [ "title" => "Education", "title_fr" => "Éducation" ],
            [ "title" => "Educational Technology and Learning Sciences", "title_fr" => "Technologie éducative et sciences de l'apprentissage" ],
            [ "title" => "Electrical Engineering", "title_fr" => "Ingénierie électrique" ],
            [ "title" => "Elementary Education", "title_fr" => "Enseignement primaire" ],
            [ "title" => "Elementary Mathematics Endorsement", "title_fr" => "Approbation des mathématiques élémentaires" ],
            [ "title" => "Engineering", "title_fr" => "Ingénierie" ],
            [ "title" => "Engineering Education", "title_fr" => "Enseignement de l'ingénierie" ],
            [ "title" => "English", "title_fr" => "Anglais" ],
            [ "title" => "English as a Second Language Endorsement", "title_fr" => "Approbation de l'anglais comme langue seconde" ],
            [ "title" => "Environment and Society", "title_fr" => "Environnement et Société" ],
            [ "title" => "Family and Consumer Science Education and Extension", "title_fr" => "Éducation et vulgarisation en sciences de la famille et de la consommation" ],
            [ "title" => "Family and Human Development", "title_fr" => "Famille et développement humain" ],
            [ "title" => "Family, Consumer, and Human Development", "title_fr" => "Famille, consommateur et développement humain" ],
            [ "title" => "Financial Economics", "title_fr" => "Économie financière" ],
            [ "title" => "Fisheries Biology", "title_fr" => "Biologie de la pêche" ],
            [ "title" => "Fitness Promotion", "title_fr" => "Promotion de fitness" ],
            [ "title" => "Food and Agribusiness", "title_fr" => "Alimentation et agroalimentaire" ],
            [ "title" => "Food Safety and Quality", "title_fr" => "Sécurité alimentaire et qualité" ],
            [ "title" => "Forestry", "title_fr" => "Sylviculture" ],
            [ "title" => "Geographic Information Science", "title_fr" => "Science de l'information géographique" ],
            [ "title" => "Geography", "title_fr" => "Géographie" ],
            [ "title" => "Geology", "title_fr" => "Géologie" ],
            [ "title" => "Gifted and Talented Endorsement", "title_fr" => "Approbation douée et talentueuse" ],
            [ "title" => "Health and Human Movement", "title_fr" => "Santé et mouvement humain" ],
            [ "title" => "Health Promotion", "title_fr" => "Promotion de la santé" ],
            [ "title" => "History", "title_fr" => "Histoire" ],
            [ "title" => "Horticulture", "title_fr" => "Horticulture" ],
            [ "title" => "Human Resources", "title_fr" => "Ressources humaines" ],
            [ "title" => "Industrial Mathematics", "title_fr" => "Mathématiques industrielles" ],
            [ "title" => "Instructional Leadership", "title_fr" => "Leadership pédagogique" ],
            [ "title" => "Instructional Technology and Learning Sciences", "title_fr" => "Technologie pédagogique et sciences de l'apprentissage" ],
            [ "title" => "International Food and Agribusiness", "title_fr" => "Alimentation internationale et agro-alimentaire" ],
            [ "title" => "Irrigation Engineering", "title_fr" => "Ingénierie de l'irrigation" ],
            [ "title" => "Landscape Architecture", "title_fr" => "Architecture de paysage" ],
            [ "title" => "Landscape Architecture", "title_fr" => "Architecture de paysage" ],
            [ "title" => "Management Information Systems", "title_fr" => "Système de gestion d'informations" ],
            [ "title" => "Marriage and Family Therapy", "title_fr" => "Mariage et thérapie familiale" ],
            [ "title" => "Mathematical Sciences", "title_fr" => "Sciences mathématiques" ],
            [ "title" => "Mathematics", "title_fr" => "Mathématiques" ],
            [ "title" => "Mathematics", "title_fr" => "Mathématiques" ],
            [ "title" => "Mechanical Engineering", "title_fr" => "Ingénierie mécanique" ],
            [ "title" => "Music", "title_fr" => "La musique" ],
            [ "title" => "National Environmental Policy Act", "title_fr" => "Loi nationale sur la politique environnementale" ],
            [ "title" => "Natural Resources", "title_fr" => "Ressources naturelles" ],
            [ "title" => "Natural Resources and Environmental Education", "title_fr" => "Ressources naturelles et éducation environnementale" ],
            [ "title" => "Neuroscience", "title_fr" => "Neuroscience" ],
            [ "title" => "Nutrition and Food Sciences", "title_fr" => "Nutrition et sciences alimentaires" ],
            [ "title" => "Physical and Sport Education", "title_fr" => "Éducation physique et sportive" ],
            [ "title" => "Physics", "title_fr" => "Physique" ],
            [ "title" => "Plant Science", "title_fr" => "Science des plantes" ],
            [ "title" => "Political Science", "title_fr" => "Science politique" ],
            [ "title" => "Psychology", "title_fr" => "Psychologie" ],
            [ "title" => "Public Health Nutrition", "title_fr" => "Nutrition santé publique" ],
            [ "title" => "Range Science", "title_fr" => "Science de la gamme" ],
            [ "title" => "Reading Endorsement", "title_fr" => "Lecture Approbation" ],
            [ "title" => "Recreation Resource Management", "title_fr" => "Gestion des ressources récréatives" ],
            [ "title" => "Rehabilitation Counseling", "title_fr" => "Counseling en réadaptation" ],
            [ "title" => "Rehabilitation Counseling Certificate", "title_fr" => "Certificat de counseling en réadaptation" ],
            [ "title" => "School Library Media Administration Endorsement", "title_fr" => "Approbation de l'administration des médias de la bibliothèque scolaire" ],
            [ "title" => "Second Language Teaching", "title_fr" => "Enseignement de la langue seconde" ],
            [ "title" => "Secondary Education", "title_fr" => "Éducation secondaire" ],
            [ "title" => "Secondary Education- Alternative Route to Licensure", "title_fr" => "Enseignement secondaire - Itinéraire alternatif à l'obtention d'un permis" ],
            [ "title" => "Social Work", "title_fr" => "Travail social" ],
            [ "title" => "Sociology", "title_fr" => "Sociologie" ],
            [ "title" => "Soil Science", "title_fr" => "La science du sol" ],
            [ "title" => "Special Education", "title_fr" => "Éducation spéciale" ],
            [ "title" => "Statistics", "title_fr" => "Statistiques" ],
            [ "title" => "Technical Communication", "title_fr" => "Communication technique" ],
            [ "title" => "Technical Communication and Rhetoric", "title_fr" => "Communication technique et rhétorique" ],
            [ "title" => "Technology and Engineering Education", "title_fr" => "Enseignement de la technologie et de l'ingénierie" ],
            [ "title" => "Theatre Arts", "title_fr" => "Théâtre Arts" ],
            [ "title" => "Toxicology", "title_fr" => "Toxicologie" ],
            [ "title" => "Veterinary Medicine", "title_fr" => "Médecine vétérinaire" ],
            [ "title" => "Veterinary Public Health", "title_fr" => "Santé publique vétérinaire" ],
            [ "title" => "Watershed Science", "title_fr" => "Science des bassins versants" ],
            [ "title" => "Wildlife Biology", "title_fr" => "Biologie de la faune" ],
            [ "title" => "Women and Gender Studies", "title_fr" => "Femmes et études de genre" ],
            [ "title" => "Accounting", "title_fr" => "Comptabilité" ],
            [ "title" => "Aerospace Studies", "title_fr" => "Etudes aérospatiales" ],
            [ "title" => "Agribusiness", "title_fr" => "Secteur agroalimentaire" ],
            [ "title" => "Agricultural Economics", "title_fr" => "Économie agricole" ],
            [ "title" => "Agricultural Systems Technology", "title_fr" => "Technologie des systèmes agricoles" ],
            [ "title" => "Agronomy", "title_fr" => "Agronomie" ],
            [ "title" => "American Sign Language", "title_fr" => "Langue des signes américaine" ],
            [ "title" => "American Sign Language Teaching", "title_fr" => "Enseignement de la langue des signes américaine" ],
            [ "title" => "American Studies", "title_fr" => "Études américaines" ],
            [ "title" => "Animal and Dairy Sciences", "title_fr" => "Sciences animales et laitières" ],
            [ "title" => "Anthropology", "title_fr" => "Anthropologie" ],
            [ "title" => "Art", "title_fr" => "Art" ],
            [ "title" => "Art History", "title_fr" => "Histoire de l'art" ],
            [ "title" => "Asian Studies", "title_fr" => "des études asiatiques" ],
            [ "title" => "Basic Music", "title_fr" => "Musique de base" ],
            [ "title" => "Behavioral Health", "title_fr" => "Santé comportementale" ],
            [ "title" => "Biology", "title_fr" => "La biologie" ],
            [ "title" => "Biomathematics", "title_fr" => "Biomathématique" ],
            [ "title" => "Business", "title_fr" => "Entreprise" ],
            [ "title" => "Chemistry", "title_fr" => "Chimie" ],
            [ "title" => "Chemistry Teaching", "title_fr" => "Enseignement de la chimie" ],
            [ "title" => "Chinese", "title_fr" => "chinois" ],
            [ "title" => "Chinese Teaching", "title_fr" => "Enseignement chinois" ],
            [ "title" => "Classics with Emphasis in Civilization", "title_fr" => "Classiques avec emphase dans la civilisation" ],
            [ "title" => "Classics with Emphasis in Greek Language", "title_fr" => "Classiques avec emphase en langue grecque" ],
            [ "title" => "Classics with Emphasis in Latin Language", "title_fr" => "Classiques avec emphase en langue latine" ],
            [ "title" => "Classics with Emphasis in Latin Teaching", "title_fr" => "Classiques avec emphase en enseignement latin" ],
            [ "title" => "Climate Change and Energy", "title_fr" => "Changement climatique et énergie" ],
            [ "title" => "Computer Science", "title_fr" => "L'informatique" ],
            [ "title" => "Criminal Justice", "title_fr" => "Justice criminelle" ],
            [ "title" => "Crop Biotechnology", "title_fr" => "Biotechnologie des cultures" ],
            [ "title" => "Economics", "title_fr" => "Économie" ],
            [ "title" => "Elementary School Music Teaching", "title_fr" => "Enseignement de la musique à l'école élémentaire" ],
            [ "title" => "English", "title_fr" => "Anglais" ],
            [ "title" => "English as a Second Language", "title_fr" => "Anglais en seconde langue" ],
            [ "title" => "English Teaching", "title_fr" => "Enseignement de l'anglais" ],
            [ "title" => "Entrepreneurship", "title_fr" => "Entrepreneuriat" ],
            [ "title" => "Environmental and Natural Resource Economics", "title_fr" => "Économie de l'environnement et des ressources naturelles" ],
            [ "title" => "Environmental Studies", "title_fr" => "Études environnementales" ],
            [ "title" => "Equine", "title_fr" => "Equine" ],
            [ "title" => "Equine Assisted Activities and Therapies", "title_fr" => "Activités et thérapies assistées par les chevaux" ],
            [ "title" => "Family and Human Development", "title_fr" => "Famille et développement humain" ],
            [ "title" => "Family Finance", "title_fr" => "Finance familiale" ],
            [ "title" => "Finance", "title_fr" => "La finance" ],
            [ "title" => "Fisheries Science", "title_fr" => "Science de la pêche" ],
            [ "title" => "Folklore", "title_fr" => "Folklore" ],
            [ "title" => "Food Science", "title_fr" => "Science culinaire" ],
            [ "title" => "French", "title_fr" => "français" ],
            [ "title" => "French Teaching", "title_fr" => "Enseignement du français" ],
            [ "title" => "General Theatre Studies", "title_fr" => "Études générales de théâtre" ],
            [ "title" => "Geographic Information Science", "title_fr" => "Science de l'information géographique" ],
            [ "title" => "Geography", "title_fr" => "Géographie" ],
            [ "title" => "Geography Teaching", "title_fr" => "Enseignement de la géographie" ],
            [ "title" => "Geology", "title_fr" => "Géologie" ],
            [ "title" => "German", "title_fr" => "allemand" ],
            [ "title" => "German Teaching", "title_fr" => "Enseignement de l'allemand" ],
            [ "title" => "History", "title_fr" => "Histoire" ],
            [ "title" => "History Teaching", "title_fr" => "Enseignement de l'histoire" ],
            [ "title" => "Horticulture", "title_fr" => "Horticulture" ],
            [ "title" => "Hospitality and Tourism Management", "title_fr" => "Gestion de l'accueil et du tourisme" ],
            [ "title" => "Human Resource Management", "title_fr" => "Gestion des ressources humaines" ],
            [ "title" => "International Business", "title_fr" => "Commerce international" ],
            [ "title" => "International Studies", "title_fr" => "Études internationales" ],
            [ "title" => "Japanese", "title_fr" => "Japonais" ],
            [ "title" => "Journalism", "title_fr" => "Journalisme" ],
            [ "title" => "Landscape Architecture", "title_fr" => "Architecture de paysage" ],
            [ "title" => "Latin American Studies", "title_fr" => "Études latino-américaines" ],
            [ "title" => "Linguistics", "title_fr" => "Linguistique" ],
            [ "title" => "Management", "title_fr" => "La gestion" ],
            [ "title" => "Management Information Systems", "title_fr" => "Système de gestion d'informations" ],
            [ "title" => "Marketing", "title_fr" => "Commercialisation" ],
            [ "title" => "Mathematics", "title_fr" => "Mathématiques" ],
            [ "title" => "Mathematics Education", "title_fr" => "Éducation mathématique" ],
            [ "title" => "Mental Health Advocacy and Awareness", "title_fr" => "Sensibilisation et sensibilisation en matière de santé mentale" ],
            [ "title" => "Military Science", "title_fr" => "Science militaire" ],
            [ "title" => "Multimedia Development", "title_fr" => "Développement multimédia" ],
            [ "title" => "Music Studies", "title_fr" => "Études musicales" ],
            [ "title" => "Native American Studies", "title_fr" => "Études amérindiennes" ],
            [ "title" => "Operations Management", "title_fr" => "Gestion des opérations" ],
            [ "title" => "Organizational Communication", "title_fr" => "Communication organisationnelle" ],
            [ "title" => "Ornamental Horticulture", "title_fr" => "Horticulture ornementale" ],
            [ "title" => "Parks and Recreation", "title_fr" => "Parcs et loisirs" ],
            [ "title" => "Personal Financial Planning", "title_fr" => "Planification financière personnelle" ],
            [ "title" => "Philosophy", "title_fr" => "Philosophie" ],
            [ "title" => "Physical Education Coaching", "title_fr" => "Coaching en éducation physique" ],
            [ "title" => "Physics", "title_fr" => "La physique" ],
            [ "title" => "Physics Teaching", "title_fr" => "Enseignement de la physique" ],
            [ "title" => "Political Science", "title_fr" => "Science politique" ],
            [ "title" => "Political Science Teaching", "title_fr" => "Enseignement des sciences politiques" ],
            [ "title" => "Portuguese", "title_fr" => "Portugais" ],
            [ "title" => "Psychology", "title_fr" => "Psychologie" ],
            [ "title" => "Psychology Teaching", "title_fr" => "Enseignement de la psychologie" ],
            [ "title" => "Public Health", "title_fr" => "Santé publique" ],
            [ "title" => "Quantitative Finance", "title_fr" => "Finance quantitative" ],
            [ "title" => "Real Estate", "title_fr" => "Immobilier" ],
            [ "title" => "Recreation Resources", "title_fr" => "Ressources récréatives" ],
            [ "title" => "Religious Studies", "title_fr" => "Études religieuses" ],
            [ "title" => "Residential Landscape Design", "title_fr" => "Conception de paysage résidentiel" ],
            [ "title" => "Russian", "title_fr" => "russe" ],
            [ "title" => "School Library Media Administration", "title_fr" => "Administration des médias de la bibliothèque scolaire" ],
            [ "title" => "Sociology", "title_fr" => "Sociologie" ],
            [ "title" => "Sociology Teaching", "title_fr" => "Enseignement de la sociologie" ],
            [ "title" => "Soil Science", "title_fr" => "La science du sol" ],
            [ "title" => "Spanish", "title_fr" => "Espanol" ],
            [ "title" => "Spanish Teaching", "title_fr" => "Enseignement de l'espagnol" ],
            [ "title" => "Speech Communication Teaching", "title_fr" => "Discours Communication Enseignement" ],
            [ "title" => "Statistics", "title_fr" => "Statistiques" ],
            [ "title" => "Sustainable Systems", "title_fr" => "Systèmes durables" ],
            [ "title" => "Technology and Engineering Education", "title_fr" => "Enseignement de la technologie et de l'ingénierie" ],
            [ "title" => "Theatre Arts Teaching", "title_fr" => "Enseignement des arts du théâtre" ],
            [ "title" => "Watershed Science", "title_fr" => "Science des bassins versants" ],
            [ "title" => "Wildlife Science", "title_fr" => "Science de la faune" ],
            [ "title" => "Women and Gender Studies", "title_fr" => "Femmes et études de genre" ],
            [ "title" => "Yoga Studies", "title_fr" => "Études de yoga" ],
        ];

        DB::table('degrees')->insert($data);
    }
}
