<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InterestsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('interests')->delete();
        DB::statement('ALTER TABLE interests AUTO_INCREMENT = 1');

        $data = [
            [ "title" => "3D printing", "title_fr" => "impression en 3D" ],
            [ "title" => "Acting", "title_fr" => "Agissant" ],
            [ "title" => "Amateur radio", "title_fr" => "Radio amateur" ],
            [ "title" => "Aquascaping", "title_fr" => "Aquascaping" ],
            [ "title" => "Baking", "title_fr" => "Cuisson" ],
            [ "title" => "Baton twirling", "title_fr" => "Baton virevoltant" ],
            [ "title" => "Board/tabletop games", "title_fr" => "Jeux de société / de table" ],
            [ "title" => "Book restoration", "title_fr" => "Restauration de livre" ],
            [ "title" => "Cabaret", "title_fr" => "Cabaret" ],
            [ "title" => "Calligraphy", "title_fr" => "Calligraphie" ],
            [ "title" => "Candle making", "title_fr" => "Fabrication de bougies" ],
            [ "title" => "Coffee roasting", "title_fr" => "Torréfaction de café" ],
            [ "title" => "Coloring", "title_fr" => "Coloration" ],
            [ "title" => "Computer programming", "title_fr" => "Programmation informatique" ],
            [ "title" => "Cooking", "title_fr" => "Cuisine" ],
            [ "title" => "Cosplaying", "title_fr" => "Cosplay" ],
            [ "title" => "Couponing", "title_fr" => "Couponing" ],
            [ "title" => "Creative writing", "title_fr" => "Écriture créative" ],
            [ "title" => "Crocheting", "title_fr" => "Crocheting" ],
            [ "title" => "Cross-stitch", "title_fr" => "Point de croix" ],
            [ "title" => "Crossword puzzles", "title_fr" => "Mots croisés" ],
            [ "title" => "Cryptography", "title_fr" => "Cryptographie" ],
            [ "title" => "Dance", "title_fr" => "Danse" ],
            [ "title" => "Digital arts", "title_fr" => "Arts numériques" ],
            [ "title" => "Do it yourself", "title_fr" => "Fais le toi-même" ],
            [ "title" => "Drama", "title_fr" => "Drame" ],
            [ "title" => "Drawing", "title_fr" => "Dessin" ],
            [ "title" => "Electronics", "title_fr" => "Électronique" ],
            [ "title" => "Embroidery", "title_fr" => "Broderie" ],
            [ "title" => "Fantasy sports", "title_fr" => "Sports fantastiques" ],
            [ "title" => "Fashion", "title_fr" => "Mode" ],
            [ "title" => "Fishkeeping", "title_fr" => "Pêche" ],
            [ "title" => "Flower arranging", "title_fr" => "Arrangement floral" ],
            [ "title" => "Foreign language learning", "title_fr" => "Apprentissage des langues étrangères" ],
            [ "title" => "Gaming (tabletop games and role-playing games)", "title_fr" => "Jeux (jeux de table et jeux de rôle)" ],
            [ "title" => "Genealogy", "title_fr" => "Généalogie" ],
            [ "title" => "Glassblowing", "title_fr" => "Soufflage de verre" ],
            [ "title" => "Gunsmithing", "title_fr" => "Armurier" ],
            [ "title" => "Herp keeping", "title_fr" => "Herp gardant" ],
            [ "title" => "Homebrewing", "title_fr" => "Homebrewing" ],
            [ "title" => "Hydroponics", "title_fr" => "Hydroponique" ],
            [ "title" => "Ice skating", "title_fr" => "Patinage sur glace" ],
            [ "title" => "Jewelry making", "title_fr" => "Fabrication de bijoux" ],
            [ "title" => "Jigsaw puzzles", "title_fr" => "Puzzles" ],
            [ "title" => "Juggling", "title_fr" => "Jonglerie" ],
            [ "title" => "Knife making", "title_fr" => "Couteau" ],
            [ "title" => "Knitting", "title_fr" => "Tricot" ],
            [ "title" => "Kombucha brewing", "title_fr" => "Kombucha brassage" ],
            [ "title" => "Lace making", "title_fr" => "Fabrication de dentelle" ],
            [ "title" => "Lapidary", "title_fr" => "Lapidaire" ],
            [ "title" => "Leather crafting", "title_fr" => "L'artisanat du cuir" ],
            [ "title" => "Lego building", "title_fr" => "Lego" ],
            [ "title" => "Listening to music", "title_fr" => "Écouter de la musique" ],
            [ "title" => "Machining", "title_fr" => "Usinage" ],
            [ "title" => "Macrame", "title_fr" => "Macramé" ],
            [ "title" => "Magic", "title_fr" => "la magie" ],
            [ "title" => "Metalworking", "title_fr" => "Travail des métaux" ],
            [ "title" => "Model building", "title_fr" => "Bâtiment modèle" ],
            [ "title" => "Origami", "title_fr" => "Origami" ],
            [ "title" => "Painting", "title_fr" => "La peinture" ],
            [ "title" => "Pet", "title_fr" => "Animal de compagnie" ],
            [ "title" => "Philately", "title_fr" => "Philatélie" ],
            [ "title" => "Photography", "title_fr" => "La photographie" ],
            [ "title" => "Playing musical instruments", "title_fr" => "Jouer des instruments de musique" ],
            [ "title" => "Poi", "title_fr" => "Poi" ],
            [ "title" => "Pottery", "title_fr" => "Poterie" ],
            [ "title" => "Puzzles", "title_fr" => "Puzzles" ],
            [ "title" => "Quilling", "title_fr" => "Quilling" ],
            [ "title" => "Quilting", "title_fr" => "Quilting" ],
            [ "title" => "Reading", "title_fr" => "En train de lire" ],
            [ "title" => "Scrapbooking", "title_fr" => "Scrapbooking" ],
            [ "title" => "Sculpting", "title_fr" => "Sculpture" ],
            [ "title" => "Sewing", "title_fr" => "Couture" ],
            [ "title" => "Singing", "title_fr" => "En chantant" ],
            [ "title" => "Sketching", "title_fr" => "Esquisse" ],
            [ "title" => "Soapmaking", "title_fr" => "Fabrication de savon" ],
            [ "title" => "Stand-up comedy", "title_fr" => "Comédie stand-up" ],
            [ "title" => "Table tennis", "title_fr" => "Tennis de table" ],
            [ "title" => "Taxidermy", "title_fr" => "Empaillage" ],
            [ "title" => "Video gaming", "title_fr" => "Jeux vidéo" ],
            [ "title" => "Watching movies", "title_fr" => "Regarder des films" ],
            [ "title" => "Watching television", "title_fr" => "Regarder la télévision" ],
            [ "title" => "Video Game Creation", "title_fr" => "Création de jeux vidéo" ],
            [ "title" => "Web surfing", "title_fr" => "surfer sur le web" ],
            [ "title" => "Whittling", "title_fr" => "Whittling" ],
            [ "title" => "Wood carving", "title_fr" => "Sculpture sur bois" ],
            [ "title" => "Woodworking", "title_fr" => "Travail du bois" ],
            [ "title" => "Worldbuilding", "title_fr" => "Worldbuilding" ],
            [ "title" => "Writing", "title_fr" => "L'écriture" ],
            [ "title" => "Yo-yoing", "title_fr" => "Yo-yoing" ],
            [ "title" => "Yoga", "title_fr" => "Yoga" ],
            [ "title" => "Air sports", "title_fr" => "Sports aériens" ],
            [ "title" => "Archery", "title_fr" => "Tir à l'arc" ],
            [ "title" => "Astronomy", "title_fr" => "Astronomie" ],
            [ "title" => "BASE jumping", "title_fr" => "Saut de base" ],
            [ "title" => "Baseball", "title_fr" => "Base-ball" ],
            [ "title" => "Basketball", "title_fr" => "Basketball" ],
            [ "title" => "Beekeeping", "title_fr" => "Apiculture" ],
            [ "title" => "Bird watching", "title_fr" => "Observation des oiseaux" ],
            [ "title" => "Blacksmithing", "title_fr" => "Forge" ],
            [ "title" => "Board sports", "title_fr" => "Sports de société" ],
            [ "title" => "Bodybuilding", "title_fr" => "La musculation" ],
            [ "title" => "Brazilian jiu-jitsu", "title_fr" => "Jiu Jitsu brésilien" ],
            [ "title" => "Camping", "title_fr" => "Camping" ],
            [ "title" => "Canyoning", "title_fr" => "Canyoning" ],
            [ "title" => "Dowsing", "title_fr" => "Radiesthésie" ],
            [ "title" => "Driving", "title_fr" => "Conduite" ],
            [ "title" => "Fishing", "title_fr" => "Pêche" ],
            [ "title" => "Flag football", "title_fr" => "Football de drapeau" ],
            [ "title" => "Flying", "title_fr" => "En volant" ],
            [ "title" => "Flying disc", "title_fr" => "Disque volant" ],
            [ "title" => "Foraging", "title_fr" => "Chercher de la nourriture" ],
            [ "title" => "Freestyle football", "title_fr" => "Football Freestyle" ],
            [ "title" => "Gardening", "title_fr" => "Jardinage" ],
            [ "title" => "Geocaching", "title_fr" => "Géocaching" ],
            [ "title" => "Ghost hunting", "title_fr" => "La chasse aux fantômes" ],
            [ "title" => "Graffiti", "title_fr" => "Graffiti" ],
            [ "title" => "Handball", "title_fr" => "Handball" ],
            [ "title" => "High-power rocketry", "title_fr" => "Fusée à haute puissance" ],
            [ "title" => "Hiking", "title_fr" => "Randonnée" ],
            [ "title" => "Hooping", "title_fr" => "Hooping" ],
            [ "title" => "Horseback riding", "title_fr" => "Monter à cheval" ],
            [ "title" => "Hunting", "title_fr" => "Chasse" ],
            [ "title" => "Inline skating", "title_fr" => "Patin à roues alignées" ],
            [ "title" => "Jogging", "title_fr" => "Le jogging" ],
            [ "title" => "Kayaking", "title_fr" => "Kayak" ],
            [ "title" => "Kite flying", "title_fr" => "cerf-volant" ],
            [ "title" => "Kitesurfing", "title_fr" => "Kite surf" ],
            [ "title" => "LARPing", "title_fr" => "LARPing" ],
            [ "title" => "Letterboxing", "title_fr" => "Letterboxing" ],
            [ "title" => "Martial arts", "title_fr" => "Arts martiaux" ],
            [ "title" => "Metal detecting", "title_fr" => "Détection de métaux" ],
            [ "title" => "Motor sports", "title_fr" => "Sports motorisés" ],
            [ "title" => "Mountain biking", "title_fr" => "vélo de montagne" ],
            [ "title" => "Mountaineering", "title_fr" => "Alpinisme" ],
            [ "title" => "Mushroom hunting/mycology", "title_fr" => "Chasse aux champignons / mycologie" ],
            [ "title" => "Netball", "title_fr" => "Netball" ],
            [ "title" => "Nordic skating", "title_fr" => "Patinage nordique" ],
            [ "title" => "Orienteering", "title_fr" => "Orientation" ],
            [ "title" => "Paintball", "title_fr" => "Paintball" ],
            [ "title" => "Parkour", "title_fr" => "Parkour" ],
            [ "title" => "Photography", "title_fr" => "La photographie" ],
            [ "title" => "Polo", "title_fr" => "Polo" ],
            [ "title" => "Powerlifting", "title_fr" => "Powerlifting" ],
            [ "title" => "Rafting", "title_fr" => "Rafting" ],
            [ "title" => "Rappelling", "title_fr" => "En rappel" ],
            [ "title" => "Road biking", "title_fr" => "Vélo de route" ],
            [ "title" => "Rock climbing", "title_fr" => "Escalade" ],
            [ "title" => "Roller skating", "title_fr" => "Roller" ],
            [ "title" => "Rugby", "title_fr" => "Le rugby" ],
            [ "title" => "Running", "title_fr" => "Fonctionnement" ],
            [ "title" => "Sailing", "title_fr" => "Voile" ],
            [ "title" => "Sand art", "title_fr" => "Art de sable" ],
            [ "title" => "Scouting", "title_fr" => "Scoutisme" ],
            [ "title" => "Scuba diving", "title_fr" => "Plongée sous-marine" ],
            [ "title" => "Sculling or rowing", "title_fr" => "Sculling ou aviron" ],
            [ "title" => "Shooting", "title_fr" => "Tournage" ],
            [ "title" => "Shopping", "title_fr" => "Achats" ],
            [ "title" => "Skateboarding", "title_fr" => "Faire de la planche à roulettes" ],
            [ "title" => "Skiing", "title_fr" => "Ski" ],
            [ "title" => "Skimboarding", "title_fr" => "Skimboard" ],
            [ "title" => "Skydiving", "title_fr" => "Parachutisme" ],
            [ "title" => "Slacklining", "title_fr" => "Slackline" ],
            [ "title" => "Snowboarding", "title_fr" => "Snowboard" ],
            [ "title" => "Stone skipping", "title_fr" => "Pierre sautant" ],
            [ "title" => "Sun bathing", "title_fr" => "bain de soleil" ],
            [ "title" => "Surfing", "title_fr" => "Surfant" ],
            [ "title" => "Swimming", "title_fr" => "La natation" ],
            [ "title" => "Taekwondo", "title_fr" => "Taekwondo" ],
            [ "title" => "Tai chi", "title_fr" => "Taï chi" ],
            [ "title" => "Topiary", "title_fr" => "Art topiaire" ],
            [ "title" => "Travel", "title_fr" => "Voyage" ],
            [ "title" => "Urban exploration", "title_fr" => "Exploration Urbaine" ],
            [ "title" => "Vacation", "title_fr" => "Vacances" ],
            [ "title" => "Vehicle restoration", "title_fr" => "Restauration de véhicule" ],
            [ "title" => "Walking", "title_fr" => "En marchant" ],
            [ "title" => "Water sports", "title_fr" => "Sports nautiques" ],
            [ "title" => "Action figure", "title_fr" => "Figurine" ],
            [ "title" => "Antiquing", "title_fr" => "Antiquité" ],
            [ "title" => "Art collecting", "title_fr" => "Collection d'art" ],
            [ "title" => "Book collecting", "title_fr" => "Collection de livres" ],
            [ "title" => "Card collecting", "title_fr" => "Collection de cartes" ],
            [ "title" => "Coin collecting", "title_fr" => "Collecte de pièces" ],
            [ "title" => "Comic book collecting", "title_fr" => "Bande dessinée" ],
            [ "title" => "Deltiology (postcard collecting)", "title_fr" => "Deltiologie (collection de cartes postales)" ],
            [ "title" => "Die-cast toy", "title_fr" => "Jouet moulé sous pression" ],
            [ "title" => "Element collecting", "title_fr" => "Elément de collecte" ],
            [ "title" => "Movie and movie memorabilia collecting", "title_fr" => "Collecte de souvenirs de films et de films" ],
            [ "title" => "Record collecting", "title_fr" => "Collecte d'enregistrements" ],
            [ "title" => "Stamp collecting", "title_fr" => "Philatélie" ],
            [ "title" => "Video game collecting", "title_fr" => "Collecte de jeux vidéo" ],
            [ "title" => "Vintage cars", "title_fr" => "Voitures anciennes" ],
            [ "title" => "Antiquities", "title_fr" => "Antiquités" ],
            [ "title" => "Auto audiophilia", "title_fr" => "Audiophilie automatique" ],
            [ "title" => "Flower collecting and pressing", "title_fr" => "Fleur de collecte et de pressage" ],
            [ "title" => "Fossil hunting", "title_fr" => "Chasse fossile" ],
            [ "title" => "Insect collecting", "title_fr" => "Collecte d'insectes" ],
            [ "title" => "Magnet fishing", "title_fr" => "Aimant de pêche" ],
            [ "title" => "Metal detecting", "title_fr" => "Détection de métaux" ],
            [ "title" => "Mineral collecting", "title_fr" => "Collecte de minéraux" ],
            [ "title" => "Rock balancing", "title_fr" => "Équilibrage rocheux" ],
            [ "title" => "Sea glass collecting", "title_fr" => "Collecte de verre de mer" ],
            [ "title" => "Seashell collecting", "title_fr" => "Collecte de coquillages" ],
            [ "title" => "Stone collecting", "title_fr" => "Collecte de pierre" ],
            [ "title" => "Animal fancy", "title_fr" => "Fantaisie animale" ],
            [ "title" => "Badminton", "title_fr" => "Badminton" ],
            [ "title" => "Baton twirling", "title_fr" => "Baton virevoltant" ],
            [ "title" => "Billiards", "title_fr" => "Billard" ],
            [ "title" => "Bowling", "title_fr" => "Bowling" ],
            [ "title" => "Boxing", "title_fr" => "Boxe" ],
            [ "title" => "Bridge", "title_fr" => "Pont" ],
            [ "title" => "Cheerleading", "title_fr" => "Cheerleading" ],
            [ "title" => "Chess", "title_fr" => "Échecs" ],
            [ "title" => "Color guard", "title_fr" => "Garde de couleur" ],
            [ "title" => "Curling", "title_fr" => "Curling" ],
            [ "title" => "Dancing", "title_fr" => "Dansant" ],
            [ "title" => "Darts", "title_fr" => "Fléchettes" ],
            [ "title" => "Debate", "title_fr" => "Débat" ],
            [ "title" => "Fencing", "title_fr" => "Escrime" ],
            [ "title" => "Go", "title_fr" => "Aller" ],
            [ "title" => "Gymnastics", "title_fr" => "Gymnastique" ],
            [ "title" => "Ice skating", "title_fr" => "Patinage sur glace" ],
            [ "title" => "Kabaddi", "title_fr" => "Kabaddi" ],
            [ "title" => "Laser tag", "title_fr" => "Guerre laser" ],
            [ "title" => "Mahjong", "title_fr" => "Mahjong" ],
            [ "title" => "Marbles", "title_fr" => "marbres" ],
            [ "title" => "Martial arts", "title_fr" => "Arts martiaux" ],
            [ "title" => "Poker", "title_fr" => "Poker" ],
            [ "title" => "Slot car racing", "title_fr" => "Fente de voiture" ],
            [ "title" => "Speedcubing", "title_fr" => "Speedcubing" ],
            [ "title" => "Sport stacking", "title_fr" => "Empilement de sport" ],
            [ "title" => "Table football", "title_fr" => "Babyfoot" ],
            [ "title" => "Volleyball", "title_fr" => "Volley-ball" ],
            [ "title" => "Weightlifting", "title_fr" => "Musculation" ],
            [ "title" => "Wrestling", "title_fr" => "Lutte" ],
            [ "title" => "Airsoft", "title_fr" => "Airsoft" ],
            [ "title" => "American football", "title_fr" => "Football américain" ],
            [ "title" => "Archery", "title_fr" => "Tir à l'arc" ],
            [ "title" => "Association football", "title_fr" => "Association de football" ],
            [ "title" => "Australian rules football", "title_fr" => "Football australien" ],
            [ "title" => "Auto racing", "title_fr" => "Course automobile" ],
            [ "title" => "Baseball", "title_fr" => "Base-ball" ],
            [ "title" => "Beach volleyball", "title_fr" => "Beach-volley" ],
            [ "title" => "Breakdancing", "title_fr" => "Break dance" ],
            [ "title" => "Climbing", "title_fr" => "Escalade" ],
            [ "title" => "Cricket", "title_fr" => "Criquet" ],
            [ "title" => "Cycling", "title_fr" => "Cyclisme" ],
            [ "title" => "Disc golf", "title_fr" => "Disc golf" ],
            [ "title" => "Dog sport", "title_fr" => "Chien sport" ],
            [ "title" => "Equestrianism", "title_fr" => "Équitation" ],
            [ "title" => "Exhibition drill", "title_fr" => "Perceuse d'exposition" ],
            [ "title" => "Field hockey", "title_fr" => "Hockey sur gazon" ],
            [ "title" => "Figure skating", "title_fr" => "Patinage artistique" ],
            [ "title" => "Fishing", "title_fr" => "Pêche" ],
            [ "title" => "Footbag", "title_fr" => "Footbag" ],
            [ "title" => "Golfing", "title_fr" => "Golf" ],
            [ "title" => "Handball", "title_fr" => "Handball" ],
            [ "title" => "Horseback riding", "title_fr" => "Monter à cheval" ],
            [ "title" => "Ice hockey", "title_fr" => "Hockey sur glace" ],
            [ "title" => "Judo", "title_fr" => "Judo" ],
            [ "title" => "Jukskei", "title_fr" => "Jukskei" ],
            [ "title" => "Kart racing", "title_fr" => "Course de kart" ],
            [ "title" => "Knife throwing", "title_fr" => "Lancer de couteau" ],
            [ "title" => "Lacrosse", "title_fr" => "Lacrosse" ],
            [ "title" => "Marching band", "title_fr" => "Fanfare" ],
            [ "title" => "Model aircraft", "title_fr" => "Avion modèle" ],
            [ "title" => "Racquetball", "title_fr" => "Racquetball" ],
            [ "title" => "Radio-controlled car racing", "title_fr" => "Courses de voitures radiocommandées" ],
            [ "title" => "Roller derby", "title_fr" => "Roller derby" ],
            [ "title" => "Rugby league football", "title_fr" => "Football de la ligue de rugby" ],
            [ "title" => "Sculling or rowing", "title_fr" => "Sculling ou aviron" ],
            [ "title" => "Shooting sport", "title_fr" => "Tir sportif" ],
            [ "title" => "Skateboarding", "title_fr" => "Faire de la planche à roulettes" ],
            [ "title" => "Speed skating", "title_fr" => "Patinage de vitesse" ],
            [ "title" => "Squash", "title_fr" => "Écraser" ],
            [ "title" => "Surfing", "title_fr" => "Surfant" ],
            [ "title" => "Swimming", "title_fr" => "La natation" ],
            [ "title" => "Table tennis", "title_fr" => "Tennis de table" ],
            [ "title" => "Tennis", "title_fr" => "Tennis" ],
            [ "title" => "Tennis polo", "title_fr" => "Tennis de polo" ],
            [ "title" => "Tour skating", "title_fr" => "Tour de patinage" ],
            [ "title" => "Triathlon", "title_fr" => "Triathlon" ],
            [ "title" => "Ultimate frisbee ", "title_fr" => "Frisbee ultime" ],
            [ "title" => "Volleyball", "title_fr" => "Volley-ball" ],
            [ "title" => "Water polo", "title_fr" => "Water polo" ],
            [ "title" => "Fishkeeping", "title_fr" => "Pêche" ],
            [ "title" => "Learning", "title_fr" => "Apprentissage" ],
            [ "title" => "Microscopy", "title_fr" => "Microscopie" ],
            [ "title" => "Reading", "title_fr" => "En train de lire" ],
            [ "title" => "Shortwave listening", "title_fr" => "Écoute à ondes courtes" ],
            [ "title" => "Videophilia", "title_fr" => "Videophilie" ],
            [ "title" => "Aircraft spotting", "title_fr" => "Repérage des aéronefs" ],
            [ "title" => "Amateur astronomy", "title_fr" => "Astronomie amateur" ],
            [ "title" => "Astrology", "title_fr" => "Astrologie" ],
            [ "title" => "Birdwatching", "title_fr" => "Observation des oiseaux" ],
            [ "title" => "Bus spotting", "title_fr" => "Spotting bus" ],
            [ "title" => "Geocaching", "title_fr" => "Géocaching" ],
            [ "title" => "Gongoozling", "title_fr" => "Gongoozling" ],
            [ "title" => "Herping", "title_fr" => "Herping" ],
            [ "title" => "Hiking/backpacking", "title_fr" => "Randonnée / randonnée" ],
            [ "title" => "Meteorology", "title_fr" => "Météorologie" ],
            [ "title" => "Photography", "title_fr" => "La photographie" ],
            [ "title" => "Satellite watching", "title_fr" => "Regarder par satellite" ],
            [ "title" => "Trainspotting", "title_fr" => "Trainspotting" ],
            [ "title" => "Traveling", "title_fr" => "En voyageant" ],
            [ "title" => "Whale watching", "title_fr" => "L'observation des baleines" ],
        ];

        DB::table('interests')->insert($data);
    }
}
