<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('skills')->delete();
        DB::statement('ALTER TABLE skills AUTO_INCREMENT = 1');

        $data = [
            [ "title" => "Analyzing", "title_fr" => "en cours d'analyse" ],
            [ "title" => "Auditing", "title_fr" => "Audit" ],
            [ "title" => "Budgeting", "title_fr" => "Budgétisation" ],
            [ "title" => "Calculating", "title_fr" => "Calculateur" ],
            [ "title" => "Computing", "title_fr" => "L'informatique" ],
            [ "title" => "Checking for accuracy", "title_fr" => "Vérification de l'exactitude" ],
            [ "title" => "Classifying", "title_fr" => "Classement" ],
            [ "title" => "Collect information", "title_fr" => "Collecter des informations" ],
            [ "title" => "Communication", "title_fr" => "la communication" ],
            [ "title" => "Comparing", "title_fr" => "Comparant" ],
            [ "title" => "Compiling", "title_fr" => "Compiler" ],
            [ "title" => "Cost analysis", "title_fr" => "Analyse de coût" ],
            [ "title" => "Counting", "title_fr" => "Compte" ],
            [ "title" => "Creativity", "title_fr" => "La créativité" ],
            [ "title" => "Critical thinking", "title_fr" => "Pensée critique" ],
            [ "title" => "Data analysis", "title_fr" => "L'analyse des données" ],
            [ "title" => "Data collection", "title_fr" => "Collecte de données" ],
            [ "title" => "Decision making", "title_fr" => "La prise de décision" ],
            [ "title" => "Deductive reasoning", "title_fr" => "Raisonnement déductif" ],
            [ "title" => "Diagnosis", "title_fr" => "Diagnostic" ],
            [ "title" => "Evaluating", "title_fr" => "Évaluer" ],
            [ "title" => "Examining", "title_fr" => "Examiner" ],
            [ "title" => "Financial management", "title_fr" => "Direction financière" ],
            [ "title" => "Financial analysis", "title_fr" => "Analyse financière" ],
            [ "title" => "Financial recording", "title_fr" => "Enregistrement financier" ],
            [ "title" => "Investigating", "title_fr" => "Enquêter" ],
            [ "title" => "Judgment", "title_fr" => "Jugement" ],
            [ "title" => "Logical thinking", "title_fr" => "Pensée logique" ],
            [ "title" => "Metrics", "title_fr" => "Métrique" ],
            [ "title" => "Organizing", "title_fr" => "Organiser" ],
            [ "title" => "Planning", "title_fr" => "Planification" ],
            [ "title" => "Prioritization", "title_fr" => "Priorisation" ],
            [ "title" => "Problem solving", "title_fr" => "Résolution de problème" ],
            [ "title" => "Qualitative analysis", "title_fr" => "Analyse qualitative" ],
            [ "title" => "Quantitative analysis", "title_fr" => "Analyse quantitative" ],
            [ "title" => "Research", "title_fr" => "Recherche" ],
            [ "title" => "Reasoning", "title_fr" => "Raisonnement" ],
            [ "title" => "Recording facts", "title_fr" => "Enregistrement des faits" ],
            [ "title" => "Research", "title_fr" => "Recherche" ],
            [ "title" => "Reporting", "title_fr" => "Reporting" ],
            [ "title" => "Resolution", "title_fr" => "Résolution" ],
            [ "title" => "Surveying", "title_fr" => "Arpentage" ],
            [ "title" => "SWOT", "title_fr" => "BOSSER" ],
            [ "title" => "Synthesizing", "title_fr" => "Synthétiser" ],
            [ "title" => "Taking inventory", "title_fr" => "Faire l'inventaire" ],
            [ "title" => "Troubleshooting", "title_fr" => "Dépannage" ],
            [ "title" => "Able to ignore extraneous information", "title_fr" => "Capable d'ignorer les informations superflues" ],
            [ "title" => "Abstract thinking", "title_fr" => "La pensée abstraite" ],
            [ "title" => "Analytical", "title_fr" => "Analytique" ],
            [ "title" => "Analyze and diagnose complex situations", "title_fr" => "Analyser et diagnostiquer des situations complexes" ],
            [ "title" => "Break down a project into manageable pieces", "title_fr" => "Décomposer un projet en morceaux gérables" ],
            [ "title" => "Broad thinking", "title_fr" => "Pensée générale" ],
            [ "title" => "Cognitive abilities", "title_fr" => "Capacités cognitives" ],
            [ "title" => "Committed to achieving company goals", "title_fr" => "Engagé à atteindre les objectifs de l'entreprise" ],
            [ "title" => "Communication", "title_fr" => "la communication" ],
            [ "title" => "Contextualize problems", "title_fr" => "Contextualiser les problèmes" ],
            [ "title" => "Creative thinking", "title_fr" => "La pensée créative" ],
            [ "title" => "Critical thinking", "title_fr" => "Pensée critique" ],
            [ "title" => "Decision making", "title_fr" => "La prise de décision" ],
            [ "title" => "Define strategies for reaching goals", "title_fr" => "Définir des stratégies pour atteindre les objectifs" ],
            [ "title" => "Delegation", "title_fr" => "Délégation" ],
            [ "title" => "Diagnose problems within the company", "title_fr" => "Diagnostiquer les problèmes au sein de l'entreprise" ],
            [ "title" => "Effectively communicate strategy", "title_fr" => "Communiquer efficacement la stratégie" ],
            [ "title" => "Examine complex issues", "title_fr" => "Examiner les problèmes complexes" ],
            [ "title" => "Execute solutions", "title_fr" => "Exécuter des solutions" ],
            [ "title" => "Formulate effective course of action", "title_fr" => "Formuler un plan d'action efficace" ],
            [ "title" => "Formulate ideas", "title_fr" => "Formuler des idées" ],
            [ "title" => "Formulate processes", "title_fr" => "Formuler des processus" ],
            [ "title" => "Implement thinking", "title_fr" => "Appliquer la pensée" ],
            [ "title" => "Innovation", "title_fr" => "Innovation" ],
            [ "title" => "Intuitive thinking", "title_fr" => "Pensée intuitive" ],
            [ "title" => "Interrelational", "title_fr" => "Interrelationnel" ],
            [ "title" => "Leadership", "title_fr" => "Direction" ],
            [ "title" => "Logical thinking", "title_fr" => "Pensée logique" ],
            [ "title" => "Management", "title_fr" => "La gestion" ],
            [ "title" => "Motivation", "title_fr" => "Motivation" ],
            [ "title" => "Multitasking", "title_fr" => "Multitâche" ],
            [ "title" => "Organization", "title_fr" => "Organisation" ],
            [ "title" => "Persuasive", "title_fr" => "Persuasif" ],
            [ "title" => "Predict the future of the business or department", "title_fr" => "Prédire l'avenir de l'entreprise ou du département" ],
            [ "title" => "Presentation", "title_fr" => "Présentation" ],
            [ "title" => "Prioritization", "title_fr" => "Priorisation" ],
            [ "title" => "Problem-solving", "title_fr" => "Résolution de problème" ],
            [ "title" => "Question the connection between new initiatives and the strategic plan", "title_fr" => "Questionner le lien entre les nouvelles initiatives et le plan stratégique" ],
            [ "title" => "Recognize opportunities for improvement", "title_fr" => "Reconnaître les opportunités d'amélioration" ],
            [ "title" => "Resolve industry problems", "title_fr" => "Résoudre les problèmes de l'industrie" ],
            [ "title" => "See the key elements in any situation", "title_fr" => "Voir les éléments clés dans n'importe quelle situation" ],
            [ "title" => "Select important information from large amounts of data", "title_fr" => "Sélectionnez des informations importantes parmi de grandes quantités de données" ],
            [ "title" => "Stability", "title_fr" => "La stabilité" ],
            [ "title" => "Strategic planning", "title_fr" => "Planification stratégique" ],
            [ "title" => "Task direction", "title_fr" => "Direction de tâche" ],
            [ "title" => "Task implementation", "title_fr" => "Mise en œuvre" ],
            [ "title" => "Team building", "title_fr" => "Construction d'équipe" ],
            [ "title" => "Understand relationships between departments", "title_fr" => "Comprendre les relations entre les départements" ],
            [ "title" => "Understand relationships between ideas, concepts, and patterns", "title_fr" => "Comprendre les relations entre les idées, les concepts et les modèles" ],
            [ "title" => "Understand the organization’s business model", "title_fr" => "Comprendre le modèle d'affaires de l'organisation" ],
            [ "title" => "Verbal communication", "title_fr" => "Communication verbale" ],
            [ "title" => "Vision", "title_fr" => "Vision" ],
            [ "title" => "Visualize the company as a whole", "title_fr" => "Visualisez l'entreprise dans son ensemble" ],
            [ "title" => "Arranging a retail display for maximum impact", "title_fr" => "Organiser un affichage de détail pour un impact maximal" ],
            [ "title" => "Brainstorming at a staff meeting to set a strategy for the next year", "title_fr" => "Brainstorming lors d'une réunion du personnel pour définir une stratégie pour l'année prochaine" ],
            [ "title" => "Brainstorming ways to cut energy use", "title_fr" => "Brainstorming façons de réduire la consommation d'énergie" ],
            [ "title" => "Coming up with new procedures to improve quality", "title_fr" => "Venir avec de nouvelles procédures pour améliorer la qualité" ],
            [ "title" => "Composing a new fundraising script for volunteers", "title_fr" => "Composer un nouveau script de collecte de fonds pour les bénévoles" ],
            [ "title" => "Composing dialogue for a television or radio commercial", "title_fr" => "Composer un dialogue pour une publicité télévisée ou radiophonique" ],
            [ "title" => "Constructing a research model to test a hypothesis", "title_fr" => "Construire un modèle de recherche pour tester une hypothèse" ],
            [ "title" => "Creating an exam to test student knowledge", "title_fr" => "Créer un examen pour tester les connaissances des élèves" ],
            [ "title" => "Creating packaging for a product", "title_fr" => "Création d'un emballage pour un produit" ],
            [ "title" => "Designing a logo", "title_fr" => "Concevoir un logo" ],
            [ "title" => "Developing a lesson plan for the U.S. election process that will captivate students", "title_fr" => "Élaborer un plan de leçon pour le processus électoral américain qui captivera les étudiants" ],
            [ "title" => "Developing a litigation strategy to defend a client", "title_fr" => "Développer une stratégie de contentieux pour défendre un client" ],
            [ "title" => "Devising a computer program to automate the billing process", "title_fr" => "Concevoir un programme informatique pour automatiser le processus de facturation" ],
            [ "title" => "Devising a more efficient way to process travel reimbursements", "title_fr" => "Concevoir un moyen plus efficace de traiter les remboursements de voyage" ],
            [ "title" => "Devising a social media platform for a cell phone", "title_fr" => "Concevoir une plate-forme de médias sociaux pour un téléphone cellulaire" ],
            [ "title" => "Generating themes for a fundraising campaign", "title_fr" => "Générer des thèmes pour une campagne de collecte de fonds" ],
            [ "title" => "Generating unusual interview questions to assess candidate skills", "title_fr" => "Générer des questions d'entrevue inhabituelles pour évaluer les compétences des candidats" ],
            [ "title" => "Identifying ways to cut costs during a budget crisis", "title_fr" => "Identifier des moyens de réduire les coûts pendant une crise budgétaire" ],
            [ "title" => "Increasing staff productivity by devising performance incentives", "title_fr" => "Augmenter la productivité du personnel en concevant des incitations à la performance" ],
            [ "title" => "Pitching retail products to customers in an innovative way", "title_fr" => "Transporter les produits de détail aux clients de manière innovante" ],
            [ "title" => "Proposing a new look for a clothing line", "title_fr" => "Proposer un nouveau look pour une ligne de vêtements" ],
            [ "title" => "Proposing behavioral changes for a patient who is overweight", "title_fr" => "Proposer des changements de comportement pour un patient en surpoids" ],
            [ "title" => "Redefining job responsibilities for an employee who is out sick", "title_fr" => "Redéfinir les responsabilités professionnelles d'un employé qui est malade" ],
            [ "title" => "Redesigning machinery on an assembly line to enhance productivity", "title_fr" => "Redéfinir les machines sur une chaîne de montage pour améliorer la productivité" ],
            [ "title" => "Restructuring a filing system to facilitate easier retrieval of information", "title_fr" => "Restructurer un système de classement pour faciliter la récupération de l'information" ],
            [ "title" => "Revising the construction process when a contractor fails to show up", "title_fr" => "Réviser le processus de construction lorsqu'un entrepreneur ne se présente pas" ],
            [ "title" => "Suggesting a way to improve customer service", "title_fr" => "Suggérer un moyen d'améliorer le service client" ],
            [ "title" => "Suggesting new ways of communication to alleviate marital conflict", "title_fr" => "Suggérer de nouvelles façons de communiquer pour atténuer les conflits conjugaux" ],
            [ "title" => "Identifying new ways to increase the number of blood donors", "title_fr" => "Identifier de nouvelles façons d'augmenter le nombre de donneurs de sang" ],
            [ "title" => "Writing compelling copy for a print or online advertisement", "title_fr" => "Rédaction d'une copie convaincante pour une publicité imprimée ou en ligne" ],
            [ "title" => "Analytical", "title_fr" => "Analytique" ],
            [ "title" => "Applying Standards", "title_fr" => "Application des normes" ],
            [ "title" => "Asking Thoughtful Questions", "title_fr" => "Poser des questions réfléchies" ],
            [ "title" => "Assessment", "title_fr" => "Évaluation" ],
            [ "title" => "Clarification", "title_fr" => "Clarification" ],
            [ "title" => "Cognitive Flexibility", "title_fr" => "Flexibilité cognitive" ],
            [ "title" => "Communication", "title_fr" => "la communication" ],
            [ "title" => "Conceptualization", "title_fr" => "Conceptualisation" ],
            [ "title" => "Creativity", "title_fr" => "La créativité" ],
            [ "title" => "Curiosity", "title_fr" => "Curiosité" ],
            [ "title" => "Decision Making", "title_fr" => "La prise de décision" ],
            [ "title" => "Embracing Different Cultural Perspectives", "title_fr" => "Adopter différentes perspectives culturelles" ],
            [ "title" => "Evaluation", "title_fr" => "Évaluation" ],
            [ "title" => "Explanation", "title_fr" => "Explication" ],
            [ "title" => "Foresight", "title_fr" => "Prévoyance" ],
            [ "title" => "Identifying Patterns", "title_fr" => "Identifier les motifs" ],
            [ "title" => "Imaginative", "title_fr" => "Imaginatif" ],
            [ "title" => "Information Seeking", "title_fr" => "La recherche d'information" ],
            [ "title" => "Interpretation", "title_fr" => "Interprétation" ],
            [ "title" => "Judgment", "title_fr" => "Jugement" ],
            [ "title" => "Logical Reasoning", "title_fr" => "Raisonnement logique" ],
            [ "title" => "Making Abstract Connections", "title_fr" => "Faire des connexions abstraites" ],
            [ "title" => "Making Inferences", "title_fr" => "Faire des inférences" ],
            [ "title" => "Objectivity", "title_fr" => "Objectivité" ],
            [ "title" => "Observation", "title_fr" => "Observation" ],
            [ "title" => "Open-Minded Thinking", "title_fr" => "Pensée ouverte" ],
            [ "title" => "Predicting", "title_fr" => "Prédire" ],
            [ "title" => "Presentation", "title_fr" => "Présentation" ],
            [ "title" => "Problem Solving", "title_fr" => "Résolution de problème" ],
            [ "title" => "Questioning Evidence", "title_fr" => "Questionner les preuves" ],
            [ "title" => "Reasoning", "title_fr" => "Raisonnement" ],
            [ "title" => "Recognizing Differences and Similarities", "title_fr" => "Reconnaître les différences et les similitudes" ],
            [ "title" => "Reflection", "title_fr" => "Réflexion" ],
            [ "title" => "Skepticism", "title_fr" => "Scepticisme" ],
            [ "title" => "Synthesizing", "title_fr" => "Synthétiser" ],
            [ "title" => "Active Listening", "title_fr" => "Écoute active" ],
            [ "title" => "Anticipating Obstacles to Implementation", "title_fr" => "Anticiper les obstacles à la mise en œuvre" ],
            [ "title" => "Assessing the Effectiveness of Interventions", "title_fr" => "Évaluer l'efficacité des interventions" ],
            [ "title" => "Brainstorming Solutions", "title_fr" => "Solutions de remue-méninges" ],
            [ "title" => "Collaboration", "title_fr" => "Collaboration" ],
            [ "title" => "Determining Factors Impacting Stress", "title_fr" => "Déterminer les facteurs qui influent sur le stress" ],
            [ "title" => "Developing Treatment Plans", "title_fr" => "Développer des plans de traitement" ],
            [ "title" => "Devising a Classroom Management Plan to Address Student Misbehavior", "title_fr" => "Concevoir un plan de gestion de la salle de classe pour contrer le comportement inapproprié des élèves" ],
            [ "title" => "Devising Hypotheses", "title_fr" => "Concevoir des hypothèses" ],
            [ "title" => "Diagnosing Illnesses", "title_fr" => "Diagnostiquer les maladies" ],
            [ "title" => "Drawing Consensus Around a Set of Solutions", "title_fr" => "Dessiner un consensus autour d'un ensemble de solutions" ],
            [ "title" => "Evaluating Alternative Strategies for Reducing Stress", "title_fr" => "Évaluation de stratégies alternatives pour réduire le stress" ],
            [ "title" => "Finding Middle Ground", "title_fr" => "Trouver un terrain d'entente" ],
            [ "title" => "Flexibility to Try New Approaches", "title_fr" => "Flexibilité pour essayer de nouvelles approches" ],
            [ "title" => "Follow Through", "title_fr" => "Suivre à travers" ],
            [ "title" => "Gathering Data", "title_fr" => "Rassembler des données" ],
            [ "title" => "Identifying the Causes for Social Problems", "title_fr" => "Identifier les causes des problèmes sociaux" ],
            [ "title" => "Identifying the Interests of all Parties", "title_fr" => "Identifier les intérêts de toutes les parties" ],
            [ "title" => "Implementing Solutions", "title_fr" => "Implémentation de solutions" ],
            [ "title" => "Interpreting Data to Determine the Scope of Problems", "title_fr" => "Interpréter des données pour déterminer l'étendue des problèmes" ],
            [ "title" => "Mediating Interpersonal Conflicts", "title_fr" => "Conflits interpersonnels médiateurs" ],
            [ "title" => "Pinpointing Behaviors Contributing to Marital Distress", "title_fr" => "Repérer les comportements contribuant à la détresse conjugale" ],
            [ "title" => "Proposing Diplomatic Solutions to Border Disputes", "title_fr" => "Proposer des solutions diplomatiques aux différends frontaliers" ],
            [ "title" => "Recognizing Invalid Research Models", "title_fr" => "Reconnaître des modèles de recherche invalides" ],
            [ "title" => "Recommending Ways to Improve Communication in Relationships", "title_fr" => "Recommander des façons d'améliorer la communication dans les relations" ],
            [ "title" => "Repairing Malfunctioning Machinery", "title_fr" => "Réparation de machines défectueuses" ],
            [ "title" => "Resolving a Customer Complaint", "title_fr" => "Résoudre une plainte d'un client" ],
            [ "title" => "Restructuring a Budget after a Revenue Shortfall", "title_fr" => "Restructurer un budget après un manque à gagner" ],
            [ "title" => "Selecting Employees to Layoff During a Business Downturn", "title_fr" => "Sélection des employés à licencier en période de ralentissement commercial" ],
            [ "title" => "Testing Hypotheses", "title_fr" => "Test d'hypothèses" ],
            [ "title" => "Troubleshooting Computer Malfunctions", "title_fr" => "Dépannage des défaillances de l'ordinateur" ],
            [ "title" => "Validating Data to Correctly Identify Problems", "title_fr" => "Validation des données pour identifier correctement les problèmes" ],
        ];

        DB::table('skills')->insert($data);
    }
}
